Repository senaite/senaite.core, pull requests merged in 2018-07, with the labels that each got.

#857 Fix "other" reasons not being listed on AR rejection notifications
  CHANGES.rst
  bika/lims/browser/analysisrequest/reject.py
  bika/lims/browser/analysisrequest/templates/analysisrequest_retract_mail.pt
  bika/lims/browser/analysisrequest/templates/analysisrequest_retract_pdf.pt
Labels: Bug, P2: Very Important

#878 Fix AR Header Table Styles and Ajax Failures
  CHANGES.rst
  bika/lims/browser/header_table.py
  bika/lims/browser/templates/header_table.pt
  bika/lims/jsonapi/__init__.py
Labels: Bug, Enhancement, P3: Important

#880 Fix message factory
  CHANGES.rst
  bika/lims/__init__.py
  bika/lims/config.py
Labels: Bug

#864 Display Analysis Services sorted ascending
  CHANGES.rst
  bika/lims/browser/bika_listing.py
Labels: Bug, P3: Important

#889 Fix override order of message catalogs
  CHANGES.rst
  bika/lims/browser/jsi18n.py
Labels: Bug, P3: Important

#890 Fixed i18n message handling in listings
  bika/lims/browser/js/bika.lims.bikalisting.js
  bika/lims/browser/js/coffee/bika.lims.bikalisting.coffee
Labels: Bug, P3: Important

#891 Better default styles for listing tables
  CHANGES.rst
  bika/lims/browser/analysisrequest/analysisrequests.py
  bika/lims/browser/analysisrequest/templates/analysisrequests.pt
  bika/lims/browser/analysisrequest/templates/ar_add2.pt
  bika/lims/browser/templates/bika_listing.pt
  bika/lims/browser/templates/bika_listing_table.pt
Labels: P3: Important, P4: Nice To Have

#836 Allow (Multi-)Attachment upload available in AR Add
  CHANGES.rst
  bika/lims/browser/analysisrequest/add2.py
  bika/lims/content/analysisrequest.py
Labels: Addition, Cleanup, P4: Nice To Have

#877 Worksheet's attachments column is empty after results import
  CHANGES.rst
  bika/lims/browser/analyses/view.py
  bika/lims/exportimport/instruments/resultsimport.py
Labels: Bug, P1: Urgent

#892 Display only active Analyses for new Profiles
  CHANGES.rst
  bika/lims/browser/widgets/analysisprofileanalyseswidget.py
Labels: Bug, P3: Important

#893 Allow Client contact to access to batches
  CHANGES.rst
  bika/lims/browser/batchfolder.py
  bika/lims/browser/client/views/batches.py
  bika/lims/permissions.py
  bika/lims/profiles/default/workflows/bika_batch_workflow/definition.xml
  bika/lims/upgrade/v01_02_008.py
Labels: Addition

#894 Fix for error: "AttributeError: allowedRolesAndUsers"
  bika/lims/upgrade/v01_02_008.py
Labels: Bug, P0: Critical

#898 Cannot view/edit Supplier. Tabs for different views now visible.
  CHANGES.rst
  bika/lims/browser/referencesample.py
  bika/lims/browser/supplier.py
Labels: Bug, Issue done, P0: Critical

#901 Remove explicit permission settings for clients
  CHANGES.rst
  bika/lims/api/__init__.py
  bika/lims/browser/analysisrequest/analysisrequests.py
  bika/lims/browser/analysisrequest/templates/analysisrequests.pt
  bika/lims/browser/client/views/analysisprofiles.py
  bika/lims/browser/client/views/analysisrequests.py
  bika/lims/browser/client/views/analysisspecs.py
  bika/lims/browser/client/views/artemplates.py
  bika/lims/browser/client/views/contacts.py
  bika/lims/browser/client/views/orders.py
  bika/lims/browser/client/views/samplepoints.py
  bika/lims/browser/client/views/samplingrounds.py
  bika/lims/browser/clientfolder.py
  bika/lims/browser/templates/bika_listing.pt
  bika/lims/profiles/default/types/Client.xml
  bika/lims/profiles/default/workflows.xml
  bika/lims/profiles/default/workflows/bika_client_workflow/definition.xml
  bika/lims/subscribers/objectmodified.py
  bika/lims/tests/doctests/API.rst
  bika/lims/tests/doctests/IDServer.rst
  bika/lims/tests/doctests/Permissions.rst
  bika/lims/upgrade/v01_02_008.py
  bika/lims/utils/__init__.py
  bika/lims/workflow/__init__.py
Labels: Bug, Cleanup, P2: Very Important

#897 Revert client batches permission (#893)
  CHANGES.rst
  bika/lims/browser/batchfolder.py
  bika/lims/browser/client/views/batches.py
  bika/lims/permissions.py
  bika/lims/profiles/default/workflows/bika_batch_workflow/definition.xml
  bika/lims/upgrade/v01_02_008.py
Labels: P0: Critical

#921 Missing interim fields in worksheet/analyses_transposed view
  CHANGES.rst
  bika/lims/browser/worksheet/templates/analyses_transposed_cell.pt
Labels: Bug

#912 Remove "Default AR Specifications" Selection from Setup
  CHANGES.rst
  bika/lims/browser/client/__init__.py
  bika/lims/browser/client/configure.zcml
  bika/lims/browser/client/views/analysisspecs.py
  bika/lims/config.py
  bika/lims/content/bikasetup.py
  bika/lims/content/client.py
  bika/lims/content/organisation.py
Labels: Cleanup, P3: Important

#924 Added ExtProxyField for its use in SchemaExtender
  CHANGES.rst
  bika/lims/browser/fields/proxyfield.py
Labels: Addition, P0: Critical

#920 Refactored Remarks and created RemarksField and RemarksWidget
  CHANGES.rst
  bika/lims/browser/analysisrequest/add2.py
  bika/lims/browser/analysisrequest/templates/analysisrequest_analyses.pt
  bika/lims/browser/analysisrequest/templates/analysisrequest_analyses_not_requested.pt
  bika/lims/browser/analysisrequest/templates/analysisrequest_manage_results.pt
  bika/lims/browser/analysisrequest/templates/analysisrequest_view.pt
  bika/lims/browser/analysisrequest/templates/analysisrequests.pt
  bika/lims/browser/configure.zcml
  bika/lims/browser/fields/remarksfield.py
  bika/lims/browser/js/bika.lims.loader.js
  bika/lims/browser/js/bika.lims.site.js
  bika/lims/browser/js/coffee/bika.lims.site.coffee
  bika/lims/browser/js/coffee/bika_widgets/remarkswidget.coffee
  bika/lims/browser/remarks.py
  bika/lims/browser/remarks.zcml
  bika/lims/browser/sample/templates/sample.pt
  bika/lims/browser/templates/bika_listing.pt
  bika/lims/browser/templates/pricelist_content.pt
  bika/lims/browser/templates/pricelist_email.pt
  bika/lims/browser/templates/referencesample_view.pt
  bika/lims/browser/widgets/__init__.py
  bika/lims/browser/widgets/remarkswidget.py
  bika/lims/browser/worksheet/templates/add_analyses.pt
  bika/lims/browser/worksheet/templates/add_control.pt
  bika/lims/browser/worksheet/templates/add_duplicate.pt
  bika/lims/browser/worksheet/templates/results.pt
  bika/lims/content/analysisprofile.py
  bika/lims/content/analysisrequest.py
  bika/lims/content/artemplate.py
  bika/lims/content/batch.py
  bika/lims/content/instrumentcertification.py
  bika/lims/content/invoice.py
  bika/lims/content/pricelist.py
  bika/lims/content/referencesample.py
  bika/lims/content/sample.py
  bika/lims/content/supplier.py
  bika/lims/content/supplyorder.py
  bika/lims/content/worksheet.py
  bika/lims/interfaces/__init__.py
  bika/lims/skins/bika/bika_widgets/remarks.js
  bika/lims/skins/bika/bika_widgets/remarks.pt
  bika/lims/skins/bika/bika_widgets/remarkswidget.js
  bika/lims/skins/bika/bika_widgets/remarkswidget.pt
Labels: Cleanup, Enhancement

#913 Refactored Methods Listing View
  CHANGES.rst
  bika/lims/browser/configure.zcml
  bika/lims/browser/method.py
  bika/lims/browser/method.zcml
  bika/lims/browser/methodfolder.py
  bika/lims/browser/methodfolder.zcml
  bika/lims/content/configure.zcml
  bika/lims/content/methods.py
Labels: Bug, Cleanup, P3: Important

#928 Fixed Traceback on AR Template
  bika/lims/content/artemplate.py
Labels: Bug, P0: Critical

#930 Removed remarks.zcml
  bika/lims/browser/configure.zcml
Labels: Bug, P0: Critical

#914 Refactored Sampletypes Listing
  CHANGES.rst
  bika/lims/controlpanel/bika_sampletypes.py
  bika/lims/utils/__init__.py
Labels: Cleanup, P3: Important

#915 Refactored SamplePoints Listing
  CHANGES.rst
  bika/lims/controlpanel/bika_samplepoints.py
Labels: Cleanup, P3: Important

#919 Refactored Profiles Listing
  CHANGES.rst
  bika/lims/controlpanel/bika_analysisprofiles.py
Labels: Cleanup, P3: Important

#916 Refactored Instruments Listing
  CHANGES.rst
  bika/lims/controlpanel/bika_instruments.py
Labels: Cleanup, P3: Important, PR: Rework-requested

#926 Refactored Analysis Services Listing
  CHANGES.rst
  bika/lims/controlpanel/bika_analysisservices.py
Labels: Cleanup, P3: Important

#935 Refactored SamplingDeviations Listing
  CHANGES.rst
  bika/lims/controlpanel/bika_samplingdeviations.py
Labels: Cleanup, P3: Important

#931 Refactored AnalysisSpecs Listing
  CHANGES.rst
  bika/lims/controlpanel/bika_analysisspecs.py
Labels: Cleanup, P3: Important

#932 Refactored Calculation Listing
  CHANGES.rst
  bika/lims/controlpanel/bika_calculations.py
Labels: Cleanup, P3: Important

#933 Refactored SampleConditions Listing
  CHANGES.rst
  bika/lims/controlpanel/bika_sampleconditions.py
Labels: Cleanup, P3: Important

#936 Refactored AR Templates Listing
  CHANGES.rst
  bika/lims/controlpanel/bika_artemplates.py
Labels: Cleanup, P3: Important

#937 Refactored Analysis Specifications Widget
  CHANGES.rst
  bika/lims/browser/widgets/analysisspecificationwidget.py
Labels: Cleanup, P3: Important

#938 Refactored Analysis Profiles Widget
  CHANGES.rst
  bika/lims/browser/widgets/analysisprofileanalyseswidget.py
Labels: Cleanup, P3: Important

#939 Use list of columns keys in review_states configuration
  bika/lims/controlpanel/bika_analysisprofiles.py
  bika/lims/controlpanel/bika_analysisservices.py
  bika/lims/controlpanel/bika_analysisspecs.py
  bika/lims/controlpanel/bika_artemplates.py
  bika/lims/controlpanel/bika_calculations.py
  bika/lims/controlpanel/bika_instruments.py
  bika/lims/controlpanel/bika_sampleconditions.py
  bika/lims/controlpanel/bika_samplepoints.py
  bika/lims/controlpanel/bika_sampletypes.py
  bika/lims/controlpanel/bika_samplingdeviations.py
Labels: Bug, P2: Very Important

#943 AnalysisRequest View Remarks Field Style
  CHANGES.rst
  bika/lims/browser/analysisrequest/templates/analysisrequest_view.pt
  bika/lims/browser/images/remarks.png
  bika/lims/browser/images/remarks_big.png
Labels: Enhancement, P4: Nice To Have

#944 Remarks style in Manage Results/Analyses
  CHANGES.rst
  bika/lims/browser/analysisrequest/templates/analysisrequest_analyses.pt
  bika/lims/browser/analysisrequest/templates/analysisrequest_manage_results.pt
Labels: Cleanup, Enhancement, P4: Nice To Have

#948 Inactive Sample Types shown in Analysis Specifications
  CHANGES.rst
  bika/lims/content/analysisspec.py
Labels: Bug, P1: Urgent
