Repository senaite/senaite.core, pull requests merged in 2018-04, with the labels that each got.

#743 Traceback in Statement view
  CHANGES.rst
  bika/lims/browser/invoicebatch.py
  bika/lims/content/invoice.py
Labels: Bug, P0: Critical

#758 Reload Batch Labels type profile in upgrade step
  bika/lims/upgrade/v01_02_004.py
Labels: Bug, P3: Important

#760 Default to empty the Analysis Specification title
  CHANGES.rst
  bika/lims/content/analysisspec.py
Labels: Bug, P4: Nice To Have

#752 Published Date field of Analyses is never set
  CHANGES.rst
  bika/lims/browser/reports/productivity_samplereceivedvsreported.py
  bika/lims/catalog/analysis_catalog.py
  bika/lims/content/abstractanalysis.py
  bika/lims/content/analysis.py
  bika/lims/upgrade/v01_02_004.py
Labels: Bug, P3: Important

#748 Fix: Interim fields not created for QC Analyses on WSs
  CHANGES.rst
  bika/lims/content/abstractanalysis.py
  bika/lims/content/abstractroutineanalysis.py
  bika/lims/content/referenceanalysis.py
  bika/lims/tests/doctests/QCAnalysesWithInterimFieldsOnAWorksheet.rst
  bika/lims/upgrade/v01_02_004.py
Labels: P3: Important, PR: Rework-requested

#761 Dormant Reference Definitions are listed for selection on WS Templates
  CHANGES.rst
  bika/lims/browser/widgets/worksheettemplatelayoutwidget.py
  bika/lims/content/worksheettemplate.py
  bika/lims/controlpanel/bika_worksheettemplates.py
  bika/lims/skins/bika/bika_widgets/worksheettemplatelayoutwidget.pt
Labels: Bug, P3: Important

#762 Bad import causes tests to fail
  bika/lims/browser/invoicebatch.py
Labels: P0: Critical

#727 Fix interim fields result and calculation updating on the 2-Dimensional-CSV instrument
  CHANGES.rst
  bika/lims/exportimport/instruments/generic/two_dimension.py
  bika/lims/exportimport/instruments/resultsimport.py
  bika/lims/tests/doctests/InstrumentsImportInterface.rst
Labels: Bug, P2: Very Important

#746 'StringField' to 'UIDReferenceField' for Default Department of Lab Contact
  CHANGES.rst
  bika/lims/content/labcontact.py
  bika/lims/skins/bika/portlet_department_filter.pt
  bika/lims/subscribers/dep_cookie.py
Labels: P4: Nice To Have

#763 Datetime conversion error in CSV Importer of Taqman 48
  CHANGES.rst
  bika/lims/exportimport/instruments/rochecobas/taqman/model48.py
Labels: Bug, P1: Urgent

#772 Improved UID check in API
  CHANGES.rst
  bika/lims/api/__init__.py
Labels: Bug, P2: Very Important

#774 When retracting an Analysis Request retract also its Analyses
  CHANGES.rst
  bika/lims/content/analysisrequest.py
  bika/lims/tests/doctests/AnalysisRequestRetract.rst
  bika/lims/utils/__init__.py
  bika/lims/workflow/analysisrequest/events.py
Labels: Bug, P3: Important

#771 Slow Searches in Listing Views
  CHANGES.rst
  RELEASE_NOTES.rst
  bika/lims/api/__init__.py
  bika/lims/browser/bika_listing.py
  bika/lims/catalog/analysisrequest_catalog.py
  bika/lims/catalog/indexers/analysisrequest.py
  bika/lims/catalog/indexers/configure.zcml
  bika/lims/content/analysisrequest.py
  bika/lims/upgrade/v01_02_005.py
  setup.py
Labels: Enhancement, P2: Very Important

#769 Traceback when submitting duplicate when Duplicate Variation is not set
  CHANGES.rst
  bika/lims/content/abstractbaseanalysis.py
  bika/lims/upgrade/v01_02_005.py
Labels: Bug, P0: Critical

#775 Hyperlink Analyses on ARs to their WSs if assigned
  CHANGES.rst
  bika/lims/browser/analyses.py
Labels: Bug, P3: Important

#782 Fix Travis Buildout
  buildout.cfg
  travis.cfg
Labels: Bug

#786 Fix inactive services listed in AR "Manage Analyses" forms
  CHANGES.rst
  bika/lims/browser/analysisrequest/manage_analyses.py
Labels: Bug, P3: Important

#784 Fix workflow state filter not kept when expanding categories in AS listing
  CHANGES.rst
  bika/lims/browser/js/bika.lims.bikalisting.js
  bika/lims/browser/js/coffee/bika.lims.bikalisting.coffee
Labels: Bug, P3: Important

#765 Department Filtering Improvements
  CHANGES.rst
  bika/lims/browser/analysisrequest/analysisrequests.py
  bika/lims/skins/bika/portlet_department_filter.pt
  bika/lims/subscribers/configure.zcml
  bika/lims/subscribers/dep_cookie.py
Labels: Enhancement, P2: Very Important, PR: Rework-requested

#781 Delete Permission on ARs for Lab Managers
  CHANGES.rst
  bika/lims/subscribers/objectmodified.py
  bika/lims/upgrade/v01_02_005.py
Labels: P3: Important

#802 Remove dry matter remainders
  CHANGES.rst
  bika/lims/browser/analysisrequest/add2.py
Labels: Bug, Cleanup

#809 AR 'listing_searchable_text' indexer optimization.
  bika/lims/catalog/indexers/analysisrequest.py
Labels: Cleanup, P3: Important

#806 Include Client ID when setting up ARReport on the IDServer
  CHANGES.rst
  bika/lims/idserver.py
Labels: Enhancement, PR: Rework-requested

#777 Delay option for searches in Reference widget combos
  CHANGES.rst
  bika/lims/browser/widgets/referencewidget.py
Labels: P4: Nice To Have

#726 Solve 404 error when clicking Print Samples Sheets from within a client
  CHANGES.rst
  bika/lims/browser/client/configure.zcml
  bika/lims/browser/js/bika.lims.loader.js
  bika/lims/browser/js/bika.lims.samples.js
  bika/lims/browser/js/bika.lims.samples.print.js
  bika/lims/browser/sample/printform.py
  bika/lims/browser/sample/templates/print_form.pt
Labels: Bug, P3: Important

#776 Analyses submission in Worksheet is slow
  CHANGES.rst
  bika/lims/browser/analyses/__init__.py
  bika/lims/browser/analyses/configure.zcml
  bika/lims/browser/analyses/late.py
  bika/lims/browser/analyses/qc.py
  bika/lims/browser/analyses/view.py
  bika/lims/browser/analyses/workflow.py
  bika/lims/browser/analysisrequest/workflow.py
  bika/lims/browser/bika_listing.py
  bika/lims/browser/configure.zcml
  bika/lims/browser/fields/uidreferencefield.py
  bika/lims/browser/worksheet/workflow.py
  bika/lims/content/abstractroutineanalysis.py
  bika/lims/content/analysisrequest.py
  bika/lims/content/instrument.py
  bika/lims/upgrade/v01_02_005.py
  bika/lims/workflow/__init__.py
  bika/lims/workflow/analysis/events.py
  bika/lims/workflow/worksheet/guards.py
Labels: P0: Critical
