Repository senaite/senaite.core, pull requests merged in 2018-08, with the labels that each got.

#960 #942: Traceback on AnalysisSpec Log
  CHANGES.rst
  bika/lims/browser/templates/bika_listing_table_items.pt
Labels: Bug

#954 Refactored Attachment Types Listing
  CHANGES.rst
  bika/lims/controlpanel/bika_attachmenttypes.py
Labels: Cleanup, P3: Important

#955 Refactored Departments Listing
  CHANGES.rst
  bika/lims/controlpanel/bika_departments.py
Labels: Cleanup, P3: Important

#956 Refactored LabContacts Listing
  CHANGES.rst
  bika/lims/controlpanel/bika_labcontacts.py
Labels: Cleanup, P3: Important

#953 Refactored Analysis Categories Listing
  CHANGES.rst
  bika/lims/controlpanel/bika_analysiscategories.py
Labels: Cleanup, P3: Important

#966 Traceback in Analyses listings when analysis unit is a numeric value
  CHANGES.rst
  bika/lims/utils/__init__.py
Labels: Bug, P0: Critical

#963 #961 Client lookups don't work
  bika/lims/browser/clientfolder.py
  bika/lims/content/analysisrequest.py
  bika/lims/content/batch.py
  bika/lims/vocabularies/__init__.py
Labels: Bug, P2: Very Important

#900 Removed basic handling of custom Sample Preparation Workflows
  CHANGES.rst
  bika/lims/browser/dashboard/dashboard.py
  bika/lims/browser/menu.py
  bika/lims/content/abstractanalysis.py
  bika/lims/content/abstractroutineanalysis.py
  bika/lims/content/analysis.py
  bika/lims/content/analysisrequest.py
  bika/lims/content/sample.py
  bika/lims/content/samplepartition.py
  bika/lims/interfaces/__init__.py
  bika/lims/locales/plone-manual.pot
  bika/lims/locales/plone.pot
  bika/lims/locales/senaite.core.pot
  bika/lims/profiles/default/workflows.xml
  bika/lims/profiles/default/workflows/bika_analysis_workflow/definition.xml
  bika/lims/profiles/default/workflows/bika_ar_workflow/definition.xml
  bika/lims/profiles/default/workflows/bika_sample_workflow/definition.xml
  bika/lims/profiles/default/workflows/sampleprep_simple/definition.xml
  bika/lims/tests/doctests/InstrumentsImportInterface.rst
  bika/lims/upgrade/v01_02_008.py
  bika/lims/utils/__init__.py
  bika/lims/workflow/__init__.py
  bika/lims/workflow/analysis/guards.py
  bika/lims/workflow/analysisrequest/guards.py
  bika/lims/workflow/configure.zcml
  bika/lims/workflow/sample/guards.py
Labels: Bug, Cleanup, Issue done

#967 Avoid deepcopy, "Can't pickle acquisition wrappers".
  CHANGES.rst
  bika/lims/utils/analysisrequest.py
Labels: Enhancement, P3: Important

#965 Added operators for max and min values in Specifications
  CHANGES.rst
  RELEASE_NOTES.rst
  bika/lims/api/analysis.py
  bika/lims/browser/analyses/view.py
  bika/lims/browser/calcs.py
  bika/lims/browser/widgets/analysisspecificationwidget.py
  bika/lims/config.py
  bika/lims/content/analysisrequest.py
  bika/lims/content/analysisspec.py
  bika/lims/tests/doctests/API_analysis.rst
  bika/lims/utils/__init__.py
Labels: Addition, P1: Urgent

#945 Show AR Remarks in Worksheet ManageResults views.
  CHANGES.rst
  bika/lims/browser/images/remarks_ico.png
  bika/lims/browser/images/remarks_ico_big.png
  bika/lims/browser/js/bika.lims.worksheet.js
  bika/lims/browser/js/coffee/bika.lims.worksheet.coffee
  bika/lims/browser/worksheet/views/analyses.py
Labels: Enhancement, P4: Nice To Have

#970 Formatted interval not displayed correctly if min/max == 0
  bika/lims/api/analysis.py
  bika/lims/tests/doctests/API_analysis.rst
Labels: Bug, P0: Critical

#971 Refactored Client's Analysis Requests, Samples and Batches listings
  CHANGES.rst
  bika/lims/browser/client/__init__.py
  bika/lims/browser/client/views/analysisrequests.py
  bika/lims/browser/client/views/batches.py
  bika/lims/browser/client/views/samples.py
Labels: Cleanup

#972 Remove "Linked Sample" from Sample
  CHANGES.rst
  bika/lims/content/sample.py
Labels: Cleanup

#973 Fix Department for labcontacts listing
  bika/lims/controlpanel/bika_labcontacts.py
Labels: Bug, P3: Important

#985 Do not display content actions in listings from inside Client
  CHANGES.rst
  bika/lims/browser/analysisrequest/analysisrequests.py
  bika/lims/browser/batchfolder.py
  bika/lims/browser/client/views/contacts.py
  bika/lims/browser/client/views/samplingrounds.py
  bika/lims/browser/sample/view.py
  bika/lims/controlpanel/bika_samplingrounds.py
  bika/lims/controlpanel/bika_srtemplates.py
Labels: Bug, P1: Urgent

#986 Result input fields are not read-only for analyst after submission
  CHANGES.rst
  bika/lims/browser/analyses/view.py
Labels: Bug, P0: Critical

#983 Traceback in Client's Analysis Specs view
  CHANGES.rst
  bika/lims/browser/client/views/analysisspecs.py
  bika/lims/controlpanel/bika_analysisspecs.py
Labels: Bug, P0: Critical

#987 Fix traceback in upgrade 1.2.7 to 1.2.8
  bika/lims/upgrade/v01_02_008.py
Labels: Bug, P0: Critical

#993 Fix Travis Test for "TestAnalysisRequestRetract"
  bika/lims/tests/test_AnalysisRequest_retract.py
Labels: Bug, Cleanup

#992 Removed "Attach" report option for Attachments
  CHANGES.rst
  bika/lims/browser/analysisrequest/templates/reports/bydepartment.pt
  bika/lims/browser/analysisrequest/templates/reports/default.pt
  bika/lims/browser/analysisrequest/templates/reports/example_1.pt
  bika/lims/browser/attachment.py
  bika/lims/browser/viewlets/templates/attachments.pt
  bika/lims/config.py
  bika/lims/upgrade/v01_02_009.py
Labels: Cleanup, Enhancement

#991 Issue 957 New client contacts do not have access to their own AR Templates
  CHANGES.rst
  bika/lims/browser/contact.py
  bika/lims/upgrade/v01_02_009.py
Labels: Bug, P1: Urgent

#1005 Remove databasesanitize package
  CHANGES.rst
  bika/lims/configure.zcml
  bika/lims/databasesanitize/__init__.py
  bika/lims/databasesanitize/analyses.py
  bika/lims/databasesanitize/configure.zcml
  bika/lims/databasesanitize/controller_view.py
  bika/lims/databasesanitize/templates/main_template.pt
Labels: Cleanup

#1003 Alphanumeric numbering in sequential IDs generator
  CHANGES.rst
  bika/lims/alphanumber.py
  bika/lims/api/__init__.py
  bika/lims/content/bikasetup.py
  bika/lims/idserver.py
  bika/lims/tests/doctests/API.rst
  bika/lims/tests/doctests/Alphanumber.rst
  bika/lims/tests/doctests/IDServer.rst
Labels: Addition, P1: Urgent

#1007 Alphanumber's complexity redux + robustness
  bika/lims/alphanumber.py
Labels: Enhancement, P4: Nice To Have

#1012 Refactored Contacts listing
  CHANGES.rst
  bika/lims/browser/client/views/contacts.py
Labels: Cleanup

#1009 Previous results from same batch are always displayed in reports
  CHANGES.rst
  bika/lims/browser/analysisrequest/publish.py
Labels: Bug, P1: Urgent

#1014 ReferenceWidget does not handle searches with null/None
  CHANGES.rst
  bika/lims/adapters/referencewidgetvocabulary.py
Labels: Bug, P0: Critical

#1006 Order of Interim Fields not maintained on ARs
  CHANGES.rst
  bika/lims/browser/analyses/view.py
Labels: Bug, P2: Very Important
