Repository senaite/senaite.core, pull requests merged in 2018-06, with the labels that each got.

#844 Missing interface for AR Report added
  CHANGES.rst
  bika/lims/content/arreport.py
  bika/lims/interfaces/__init__.py
Labels: Addition, Cleanup

#817 Make clearer if transition rejection is due to missing sampler
  CHANGES.rst
  bika/lims/browser/client/workflow.py
Labels: Enhancement, P4: Nice To Have

#859 Only Lab Managers see rejected analysis requests
  CHANGES.rst
  bika/lims/profiles/default/workflows/bika_ar_workflow/definition.xml
  bika/lims/upgrade/v01_02_007.py
Labels: Bug, P3: Important

#868 AR Add Form: Refactoring and Styling
  CHANGES.rst
  bika/lims/browser/analysisrequest/add2.py
  bika/lims/browser/analysisrequest/templates/ar_add2.pt
  bika/lims/browser/css/bika.lims.analysisrequest.add.css
Labels: Cleanup, Enhancement

#873 SampleType field editable in Sample and AR before receive
  CHANGES.rst
  bika/lims/content/analysisrequest.py
  bika/lims/jsonapi/__init__.py
Labels: Enhancement

#869 Fix Profile VAT Amount on when adding an AR
  CHANGES.rst
  bika/lims/browser/analysisrequest/add2.py
Labels: Bug, P2: Very Important

#871 Fixed OpenTagError for i18ndude
  CHANGES.rst
  bika/lims/browser/analysisrequest/templates/ar_add2.pt
Labels: Bug

#855 Dashboard is displayed to Lab clerks after login only
  CHANGES.rst
  bika/lims/browser/senaitefrontpage.py
Labels: Bug

#872 Date format appears wrong in Users history administrative report
  CHANGES.rst
  bika/lims/browser/reports/administration_usershistory.py
Labels: Bug

#875 Fix Batch AR View
  CHANGES.rst
  bika/lims/browser/analysisrequest/add2.py
Labels: Bug, P0: Critical
