Repository senaite/senaite.core, pull requests merged in 2018-02, with the labels that each got.

#642 ReferenceSample Analyses listing broken
  CHANGES.rst
  bika/lims/browser/referenceanalysis.py
  bika/lims/browser/referencesample.py
Labels: Bug, P1: Urgent

#637 Analysis Requests are never transitioned to assigned/unassigned
  CHANGES.rst
  RELEASE_NOTES.rst
  bika/lims/browser/aggregatedanalyses/aggregatedanalyses.py
  bika/lims/browser/analysisrequest/analysisrequests.py
  bika/lims/catalog/analysisrequest_catalog.py
  bika/lims/catalog/indexers/analysisrequest.py
  bika/lims/catalog/indexers/configure.zcml
  bika/lims/content/abstractanalysis.py
  bika/lims/profiles/default/workflows.xml
  bika/lims/subscribers/analysis.py
  bika/lims/upgrade/v01_02_003.py
  bika/lims/workflow/__init__.py
  bika/lims/workflow/analysis/events.py
  bika/lims/workflow/analysisrequest/guards.py
Labels: Bug, P3: Important

#645 Bug in ar workflows
  bika/lims/api.py
  bika/lims/browser/samplinground/analysisrequests.py
  bika/lims/catalog/analysisrequest_catalog.py
  bika/lims/subscribers/analysis.py
  bika/lims/workflow/__init__.py
Labels: Bug, P0: Critical

#647 Refactored bika.lims.bikalisting.js + several functional fixtures
  CHANGES.rst
  bika/lims/browser/js/bika.lims.bikalisting.js
  bika/lims/browser/js/coffee/bika.lims.bikalisting.coffee
  bika/lims/locales/bika-manual.pot
Labels: P3: Important

#654 Traceback in default's Multi AR template report
  CHANGES.rst
  bika/lims/browser/analysisrequest/templates/reports/Multi_AR_default.pt
Labels: Bug, P3: Important

#652 Added Sample Type, Partition ID and Date Sampled in sticker
  CHANGES.rst
  bika/lims/browser/templates/stickers/Code_128_1x48mm.pt
Labels: Enhancement, P4: Nice To Have

#636 Do not display 'Advanced...' option in object's workflow actions selection list
  CHANGES.rst
  bika/lims/browser/contentmenu.py
  bika/lims/browser/overrides.zcml
Labels: Enhancement, P4: Nice To Have

#659 Display the Unit in Profile Analyses Listing
  CHANGES.rst
  bika/lims/browser/widgets/analysisprofileanalyseswidget.py
Labels: Enhancement, P4: Nice To Have

#627 Change unassigned filter
  CHANGES.rst
  bika/lims/browser/analysisrequest/analysisrequests.py
Labels: Enhancement, P4: Nice To Have

#663 Fix: AR Report Listing shows all Reports
  CHANGES.rst
  bika/lims/browser/analysisrequest/published_results.py
Labels: Bug, P1: Urgent

#658 Worksheet listing view shows old- invalid Analysts.
  CHANGES.rst
  bika/lims/content/worksheet.py
Labels: Bug, P3: Important

#664 Improved async transition loading and workflow button rendering in listing tables
  CHANGES.rst
  bika/lims/browser/js/bika.lims.bikalisting.js
  bika/lims/browser/js/coffee/bika.lims.bikalisting.coffee
Labels: Bug, P3: Important

#666 Unpublished filter for AR listing view and display according to the setup
  CHANGES.rst
  bika/lims/browser/analysisrequest/analysisrequests.py
  bika/lims/browser/bika_listing.py
  bika/lims/browser/js/bika.lims.bikalisting.js
  bika/lims/browser/js/coffee/bika.lims.bikalisting.coffee
Labels: Enhancement, P4: Nice To Have

#660 Better style for reference widgets
  CHANGES.rst
  bika/lims/skins/bika/ploneCustom.css.dtml
Labels: Enhancement, P4: Nice To Have

#613 Analyses filter not kept after selecting one in dashboard
  CHANGES.rst
  bika/lims/browser/aggregatedanalyses/aggregatedanalyses.py
  bika/lims/browser/dashboard/dashboard.py
Labels: Bug, P3: Important, PR: Rework-requested

#662 Viewing Cancelled AR's fails.
  CHANGES.rst
  bika/lims/browser/analysisrequest/view.py
Labels: Bug, P3: Important

#653 Points in QC Charts are not displayed in accordance with results capture date
  CHANGES.rst
  bika/lims/api.py
  bika/lims/browser/instrument.py
  bika/lims/browser/referencesample.py
  bika/lims/tests/doctests/API.rst
Labels: Bug, P2: Very Important

#668 AR Add: Debounce expensive XHR calls
  CHANGES.rst
  bika/lims/browser/js/bika.lims.analysisrequest.add.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: P3: Important, P4: Nice To Have

#670 Listings: Fix sort_on change on Show More click
  CHANGES.rst
  bika/lims/browser/templates/bika_listing_table.pt
Labels: Bug, P2: Very Important

#673 QC Analyses and Samples not totaled correctly in Worksheets list
  CHANGES.rst
  bika/lims/content/worksheet.py
  bika/lims/upgrade/v01_02_003.py
Labels: Bug, P1: Urgent

#604 Analyses view refactoring
  CHANGES.rst
  bika/lims/browser/analyses.py
  bika/lims/utils/__init__.py
Labels: Enhancement, P3: Important

#672 Traceback on automatic sticker printing in batch context
  CHANGES.rst
  bika/lims/browser/bika_listing.py
Labels: Bug, P1: Urgent

#677 Fix category toggling when the category name contains spaces
  CHANGES.rst
  bika/lims/browser/js/bika.lims.bikalisting.js
  bika/lims/browser/js/coffee/bika.lims.bikalisting.coffee
Labels: Bug, P1: Urgent

#679 Analysis could not set to "Hidden" in results view
  CHANGES.rst
  bika/lims/browser/js/bika.lims.bikalisting.js
  bika/lims/browser/js/coffee/bika.lims.bikalisting.coffee
  bika/lims/skins/bika/ploneCustom.css.dtml
Labels: Bug, P1: Urgent

#674 Dashboard with slightly better performance
  CHANGES.rst
  bika/lims/browser/dashboard/dashboard.py
  bika/lims/browser/dashboard/templates/dashboard.pt
Labels: Enhancement, P2: Very Important

#684 Aggregated list of analyses set to read-only
  CHANGES.rst
  bika/lims/browser/aggregatedanalyses/aggregatedanalyses.py
  bika/lims/browser/analyses.py
  bika/lims/browser/js/bika.lims.worksheet.js
  bika/lims/browser/templates/bika_listing_table_items.pt
  bika/lims/skins/bika/bika_listing.css.dtml
Labels: Bug, P0: Critical

#685 Display the stacked bars in evo charts sorted by number of occurrences
  CHANGES.rst
  bika/lims/browser/dashboard/dashboard.py
  bika/lims/browser/dashboard/templates/dashboard.pt
Labels: Enhancement, P3: Important

#687 Hide balloon button for remarks when remarks are disabled in setup
  CHANGES.rst
  bika/lims/browser/analyses.py
Labels: Bug, P1: Urgent

#689 Allow to hide Analyses in any AR state
  CHANGES.rst
  bika/lims/browser/analyses.py
Labels: Enhancement, P3: Important

#688 Solve traceback on samples rejected view
  CHANGES.rst
  bika/lims/browser/sample/view.py
Labels: Bug, P1: Urgent

#690 Refactored and improved client folder listing view
  CHANGES.rst
  bika/lims/browser/clientfolder.py
Labels: Enhancement, P4: Nice To Have

#696 Fix worksheet count on dashboard when filtering by department
  CHANGES.rst
  bika/lims/browser/dashboard/dashboard.py
  bika/lims/catalog/worksheet_catalog.py
  bika/lims/upgrade/v01_02_004.py
Labels: Bug

#698 Fix Publish Actions for Batches
  CHANGES.rst
  bika/lims/browser/batch/workflow.py
Labels: Bug, P1: Urgent
