Repository senaite/senaite.core, pull requests merged in 2018-09, with the labels that each got.

#1018 Fix AR Add cleanup after template removal
  CHANGES.rst
  bika/lims/browser/analysisrequest/add2.py
  bika/lims/browser/js/bika.lims.analysisrequest.add.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Bug, P3: Important

#1021 Fix upgrade step for sample preparation workflow
  bika/lims/upgrade/v01_02_008.py
Labels: Bug, P0: Critical

#1019 Support for warn min and max values in range charts
  CHANGES.rst
  bika/lims/browser/analysisrequest/templates/reports/example_1.pt
  bika/lims/browser/js/bika.lims.graphics.range.js
Labels: Bug, P2: Very Important

#1022 Date Received saved as UTC time
  CHANGES.rst
  bika/lims/browser/__init__.py
  bika/lims/browser/fields/datetimefield.py
  bika/lims/browser/widgets/datetimewidget.py
  bika/lims/skins/bika/bika_widgets/datetimewidget.pt
Labels: Bug, P0: Critical

#1024 Function to get all verifiers from Analysis Request
  CHANGES.rst
  bika/lims/content/analysisrequest.py
Labels: Enhancement, P3: Important

#1026 Removed auto-digest of results reports on verify transitions
  CHANGES.rst
  bika/lims/browser/analysisrequest/configure.zcml
  bika/lims/browser/analysisrequest/publish.py
  bika/lims/browser/analysisrequest/workflow.py
  bika/lims/content/analysisrequest.py
Labels: Cleanup, P1: Urgent

#1027 Refactoring of `retract_ar` transition and related fields from Invalidated/Retest Analysis Requests
  CHANGES.rst
  bika/lims/browser/analysisrequest/log.py
  bika/lims/browser/analysisrequest/publish.py
  bika/lims/browser/analysisrequest/published_results.py
  bika/lims/browser/analysisrequest/results_not_requested.py
  bika/lims/browser/analysisrequest/templates/analysisrequest_view.pt
  bika/lims/browser/analysisrequest/templates/reports/bydepartment.pt
  bika/lims/browser/analysisrequest/templates/reports/default.pt
  bika/lims/browser/analysisrequest/templates/reports/example_1.pt
  bika/lims/browser/analysisrequest/view.py
  bika/lims/browser/analysisrequest/workflow.py
  bika/lims/browser/fields/aranalysesfield.py
  bika/lims/content/analysisrequest.py
  bika/lims/profiles/default/workflows/bika_ar_workflow/definition.xml
  bika/lims/tests/doctests/AnalysisRequestInvalidate.rst
  bika/lims/upgrade/v01_02_009.py
  bika/lims/utils/analysisrequest.py
  bika/lims/workflow/analysisrequest/events.py
Labels: Cleanup, P1: Urgent

#1004 Option to show Interim fields on results reports
  CHANGES.rst
  bika/lims/browser/analysisrequest/publish.py
  bika/lims/browser/analysisrequest/templates/reports/Multi_AR_default.css
  bika/lims/browser/analysisrequest/templates/reports/Multi_AR_default.pt
  bika/lims/browser/analysisrequest/templates/reports/default.css
  bika/lims/browser/analysisrequest/templates/reports/default.pt
  bika/lims/browser/fields/interimfieldsfield.py
  bika/lims/setupdata/test/test.xlsx
Labels: Addition, PR: Rework-requested

#1031 Added profiling and timing decorators
  CHANGES.rst
  bika/lims/decorators.py
Labels: Enhancement
