Repository senaite/senaite.core, pull requests merged in 2019-08, with the labels that each got.

#1413 Improved Email Publication
  CHANGES.rst
  bika/lims/api/mail.py
  bika/lims/browser/analysisreport.py
  bika/lims/browser/analysisreport.zcml
  bika/lims/browser/configure.zcml
  bika/lims/browser/images/arreport.png
  bika/lims/browser/images/arreport_big.png
  bika/lims/browser/images/email.png
  bika/lims/browser/images/email_big.png
  bika/lims/browser/publish/emailview.py
  bika/lims/browser/publish/reports_listing.py
  bika/lims/browser/publish/static/img/deleted_attachment.png
  bika/lims/browser/publish/templates/email.pt
  bika/lims/browser/templates/analysisreport_info.pt
  bika/lims/content/arreport.py
  bika/lims/tests/doctests/API_mail.rst
Labels: Cleanup, Enhancement, P3: Important

#1419 Mixed permissions for transitions in client workflow
  CHANGES.rst
  bika/lims/profiles/default/workflows/senaite_client_workflow/definition.xml
  bika/lims/upgrade/v01_03_002.py
Labels: Bug, P3: Important

#1417 Cache allowed transitions for analyses on the request
  CHANGES.rst
  bika/lims/workflow/analysis/guards.py
Labels: Enhancement, P2: Very Important

#1418 Subscriber adapters not supported in clients listing
  CHANGES.rst
  bika/lims/browser/clientfolder.py
Labels: Enhancement, P2: Very Important

#1420 Allow to detach a partition from its primary sample
  CHANGES.rst
  bika/lims/browser/viewlets/analysisrequest.py
  bika/lims/browser/viewlets/configure.zcml
  bika/lims/browser/viewlets/templates/detached_partition_viewlet.pt
  bika/lims/content/analysisrequest.py
  bika/lims/interfaces/__init__.py
  bika/lims/permissions.py
  bika/lims/permissions.zcml
  bika/lims/profiles/default/rolemap.xml
  bika/lims/profiles/default/workflows/bika_ar_workflow/definition.xml
  bika/lims/upgrade/v01_03_002.py
  bika/lims/utils/analysisrequest.py
  bika/lims/workflow/analysisrequest/events.py
  bika/lims/workflow/analysisrequest/guards.py
Labels: Addition, P3: Important

#1421 Fix Search Query for Batches Listing
  CHANGES.rst
  bika/lims/browser/batch/analysisrequests.py
Labels: Bug, P2: Very Important

#1422 Notify user with failing addresses when emailing of results reports
  CHANGES.rst
  bika/lims/browser/publish/emailview.py
Labels: Enhancement, P1: Urgent

#1425 Fix adapter priority for widget visibility
  CHANGES.rst
  bika/lims/adapters/widgetvisibility.py
  bika/lims/monkey/Widget.py
Labels: Bug, P3: Important

#1424 Use the value set for ui_item property when displaying ReferenceWidget
  CHANGES.rst
  bika/lims/skins/bika/bika_widgets/referencewidget.pt
Labels: Bug, P1: Urgent

#1426 Render HTML Texts in Info Popups correctly
  CHANGES.rst
  bika/lims/browser/templates/analysisreport_info.pt
  bika/lims/browser/templates/analysisservice_info.pt
Labels: P4: Nice To Have

#1427 Improved performance of Sample header table rendering
  CHANGES.rst
  bika/lims/browser/analysisrequest/__init__.py
  bika/lims/browser/analysisrequest/configure.zcml
  bika/lims/browser/header_table.py
  bika/lims/browser/templates/header_table.pt
Labels: Cleanup, Enhancement, Performance
