Repository senaite/senaite.core, pull requests merged in 2019-09, with the labels that each got.

#1429 Add2: Do not set template values on already filled fields
  CHANGES.rst
  bika/lims/browser/js/bika.lims.analysisrequest.add.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Enhancement, P1: Urgent

#1433 Added Submitter column in Sample's analysis listing
  CHANGES.rst
  bika/lims/browser/analyses/view.py
  bika/lims/content/abstractanalysis.py
Labels: Enhancement, P1: Urgent

#1443 Fix non-saving checkbox values for manual Interims in Analysis Services
  CHANGES.rst
  bika/lims/browser/js/bika.lims.analysisservice.js
  bika/lims/browser/js/coffee/bika.lims.analysisservice.coffee
Labels: P1: Urgent

#1441 Added Auto ID Behavior for Dexterity Contents
  CHANGES.rst
  bika/lims/configure.zcml
  bika/lims/interfaces/__init__.py
  bika/lims/profiles/default/types/SamplingRound.xml
  bika/lims/subscribers/configure.zcml
  bika/lims/subscribers/objectadded.py
  bika/lims/subscribers/samplinground.py
Labels: Addition

#1444 Fixed Worksheet autofill of wide Iterims
  CHANGES.rst
  bika/lims/browser/js/bika.lims.worksheet.js
  bika/lims/browser/js/coffee/bika.lims.worksheet.coffee
  bika/lims/browser/worksheet/views/results.py
Labels: Bug, P2: Very Important

#1436 Setting in setup for auto-reception of samples upon creation
  CHANGES.rst
  bika/lims/content/bikasetup.py
  bika/lims/workflow/analysisrequest/events.py
Labels: Addition, P4: Nice To Have

#1445 Allow formatted HTML in the other rejection reasons
  CHANGES.rst
  bika/lims/browser/viewlets/templates/rejected_ar_viewlet.pt
Labels: P4: Nice To Have

#1446 Parameter `group` in `contact._addUserToGroup` was not considered
  CHANGES.rst
  bika/lims/content/contact.py
Labels: Bug, P3: Important

#1447 New Client contact has access to last Sample only
  CHANGES.rst
  bika/lims/content/contact.py
Labels: Bug, P3: Important
