Repository senaite/senaite.core, pull requests merged in 2019-06, with the labels that each got.

#1389 Analysts and Labclerks cannot create worksheets
  CHANGES.rst
  bika/lims/subscribers/configure.zcml
  bika/lims/subscribers/setup.py
  bika/lims/upgrade/v01_03_001.py
Labels: Bug

#1391 Samples for internal use (lab personnel) only
  CHANGES.rst
  bika/lims/adapters/configure.zcml
  bika/lims/adapters/widgetvisibility.py
  bika/lims/browser/analysisrequest/analysisrequests.py
  bika/lims/browser/images/locked.png
  bika/lims/browser/images/locked_big.png
  bika/lims/browser/partition_magic.py
  bika/lims/browser/templates/partition_magic.pt
  bika/lims/catalog/analysisrequest_catalog.py
  bika/lims/content/analysisrequest.py
  bika/lims/interfaces/__init__.py
  bika/lims/permissions.py
  bika/lims/permissions.zcml
  bika/lims/profiles/default/rolemap.xml
  bika/lims/profiles/default/workflows/bika_ar_workflow/definition.xml
  bika/lims/subscribers/analysisrequest.py
  bika/lims/subscribers/configure.zcml
  bika/lims/tests/doctests/API_snapshot.rst
  bika/lims/upgrade/v01_03_001.py
  bika/lims/utils/__init__.py
  bika/lims/utils/analysisrequest.py
Labels: Addition

#1392 Hide partitions to clients when "ShowPartitions" setting from setup is disabled
  CHANGES.rst
  bika/lims/browser/analysisrequest/analysisrequests.py
  bika/lims/browser/analysisrequest/templates/analysisrequest_analysisservices.pt
  bika/lims/browser/viewlets/analysisrequest.py
  bika/lims/browser/viewlets/templates/primary_ar_viewlet.pt
  bika/lims/content/bikasetup.py
  bika/lims/workflow/analysisrequest/guards.py
Labels: Enhancement

#1393 Make primary samples to not follow partitions labeled for internal use
  bika/lims/tests/doctests/InternalUse.rst
  bika/lims/workflow/analysisrequest/guards.py
Labels: Enhancement

#1394 Fix unauthorized access when primary has parttitions for internal use
  bika/lims/subscribers/analysisrequest.py
Labels: Bug, P0: Critical

#1395 Make Action Handler Pool Thread-Safe
  CHANGES.rst
  bika/lims/decorators.py
  bika/lims/interfaces/__init__.py
  bika/lims/tests/doctests/ActionHandlerPool.rst
  bika/lims/workflow/__init__.py
Labels: Bug, P0: Critical

#1397 Worksheet does not show the contained analyses
  CHANGES.rst
  bika/lims/content/worksheet.py
  bika/lims/upgrade/v01_03_001.py
Labels: Bug, P0: Critical

#1399 Fix Number Generator Seeding View
  bika/lims/browser/idserver/templates/numbergenerator.pt
  bika/lims/browser/idserver/view.py
Labels: Bug, P0: Critical

#1402 Fix Upgrade step 1.3.1 fails when running multiple times
  bika/lims/upgrade/v01_03_001.py
Labels: Bug, P0: Critical

#1401 Allow capture of text results
  CHANGES.rst
  bika/lims/browser/analyses/view.py
  bika/lims/content/abstractbaseanalysis.py
Labels: Addition

#1403 Also consider the detached states as cancellable
  CHANGES.rst
  bika/lims/workflow/analysisrequest/guards.py
Labels: Bug

#1404 Avoid conflict errors during email publication
  CHANGES.rst
  bika/lims/browser/publish/emailview.py
Labels: Enhancement
