Repository senaite/senaite.core, pull requests merged in 2019-11, with the labels that each got.

#1466 Support for "readonly" and "hidden" visibility modes in ReferenceWidget
  CHANGES.rst
  bika/lims/skins/bika/bika_widgets/referencewidget.pt
Labels: Addition

#1467 Cannot override behavior of Batch folder when using `before_render`
  CHANGES.rst
  bika/lims/browser/batchfolder.py
Labels: Bug, P1: Urgent

#1469 Fix Site Properties Generic Setup Export Step
  CHANGES.rst
  bika/lims/exportimport/genericsetup/configure.zcml
  bika/lims/exportimport/genericsetup/structure.py
  bika/lims/upgrade/v01_03_003.py
Labels: Bug

#1470 Wrong version in upgrade step 1.3.3
  bika/lims/upgrade/v01_03_003.py
Labels: Bug

#1472 Secondary samples - removal of analysis profile not possible
  CHANGES.rst
  bika/lims/browser/analysisrequest/add2.py
Labels: Bug

#1473 Hidden settings of analysis services lost on Sample creation
  CHANGES.rst
  bika/lims/utils/analysisrequest.py
Labels: Bug

#1474 Adding Control Reference to Worksheet causes print fail
  CHANGES.rst
  bika/lims/browser/worksheet/views/printview.py
Labels: Bug

#1475 User with "Analyst" role cannot submit analyses from worksheet
  CHANGES.rst
  bika/lims/content/worksheet.py
  bika/lims/workflow/analysis/guards.py
Labels: Bug

#1480 Worksheet removal results in 404
  CHANGES.rst
  bika/lims/profiles/default/cmfformcontroller.xml
  bika/lims/setuphandlers.py
  bika/lims/upgrade/v01_03_003.py
Labels: Bug

#1479 Error: Labclerks viewing verified worksheets
  CHANGES.rst
  bika/lims/browser/worksheet/configure.zcml
  bika/lims/browser/worksheet/views/results.py
Labels: Bug

#1478 Clients default CC E-Mails missing in Add Sample
  CHANGES.rst
  bika/lims/adapters/acquirefielddefaults.py
  bika/lims/adapters/configure.zcml
  bika/lims/browser/analysisrequest/add2.py
  bika/lims/content/analysisrequest.py
  bika/lims/interfaces/__init__.py
  bika/lims/monkey/Schema.py
  bika/lims/monkey/configure.zcml
Labels: Bug

#1477 Sample edit form - some selection widgets empty
  CHANGES.rst
  bika/lims/adapters/configure.zcml
  bika/lims/adapters/referencewidgetvocabulary.py
  bika/lims/browser/analysisrequest/add2.py
  bika/lims/browser/client/__init__.py
  bika/lims/browser/client/ajax.py
  bika/lims/browser/client/configure.zcml
  bika/lims/browser/js/bika.lims.analysisrequest.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.coffee
  bika/lims/content/abstractroutineanalysis.py
  bika/lims/content/analysisprofile.py
  bika/lims/content/analysisrequest.py
  bika/lims/content/analysisspec.py
  bika/lims/content/arreport.py
  bika/lims/content/artemplate.py
  bika/lims/content/attachment.py
  bika/lims/content/batch.py
  bika/lims/content/clientawaremixin.py
  bika/lims/content/report.py
  bika/lims/content/samplepoint.py
  bika/lims/interfaces/__init__.py
  bika/lims/interfaces/analysis.py
  bika/lims/upgrade/v01_03_003.py
  bika/lims/utils/__init__.py
Labels: Bug

#1483 Added Accredited symbol in Analyses listings
  CHANGES.rst
  bika/lims/browser/analyses/view.py
Labels: Addition

#1481 Filter Templates field when Sample Type is selected in Sample Add form
  CHANGES.rst
  bika/lims/browser/analysisrequest/add2.py
  bika/lims/catalog/indexers/bikasetup.py
  bika/lims/catalog/indexers/configure.zcml
  bika/lims/content/analysisrequest.py
  bika/lims/content/analysisspec.py
  bika/lims/content/artemplate.py
  bika/lims/content/samplepoint.py
  bika/lims/content/sampletype.py
  bika/lims/interfaces/__init__.py
  bika/lims/setuphandlers.py
  bika/lims/upgrade/v01_03_003.py
  bika/lims/vocabularies/__init__.py
  bika/lims/vocabularies/configure.zcml
Labels: Addition

#1482 Remove `senaite.instruments` dependency for instrument import form
  CHANGES.rst
  bika/lims/exportimport/dataimport.py
Labels: Bug, Cleanup

#1484 Skip importer when no xml structure was found
  bika/lims/exportimport/genericsetup/structure.py
Labels: Bug, P0: Critical
