Repository senaite/senaite.core, pull requests merged in 2019-03, with the labels that each got.

#1256 Improve performance of service popups
  bika/lims/browser/templates/analysisservice_info.pt
Labels: Enhancement, P3: Important

#1257 Fix Traceback for MultiSelectionWidgets in View Mode for UIDReferenceFields
  CHANGES.rst
  bika/lims/browser/widgets/uidselectionwidget.py
  bika/lims/content/abstractbaseanalysis.py
  bika/lims/content/analysisservice.py
  bika/lims/content/instrument.py
  bika/lims/content/laboratory.py
  bika/lims/content/method.py
  bika/lims/interfaces/__init__.py
  bika/lims/skins/bika/bika_widgets/uidselection.pt
Labels: Bug, P0: Critical

#1258 Fix widget permissions for Specs/Profiles/Templates Widgets
  CHANGES.rst
  bika/lims/browser/widgets/analysisprofileanalyseswidget.py
  bika/lims/browser/widgets/analysisspecificationwidget.py
  bika/lims/browser/widgets/artemplateanalyseswidget.py
Labels: Bug, P2: Very Important

#1259 Fix remarks popup in Worksheets for published Samples
  bika/lims/browser/js/bika.lims.worksheet.js
  bika/lims/browser/js/coffee/bika.lims.worksheet.coffee
  setup.py
Labels: Bug, P3: Important

#874 Generalize the assignment of values into fields for setup on import
  CHANGES.rst
  bika/lims/exportimport/setupdata/__init__.py
Labels: Enhancement

#1260 Traceback on AR creation with Calculation never edited
  bika/lims/browser/fields/historyawarereferencefield.py
  bika/lims/content/calculation.py
  bika/lims/exportimport/import.pt
  bika/lims/exportimport/setupdata/__init__.py
  bika/lims/profiles/default/rolemap.xml
  bika/lims/setuphandlers.py
  bika/lims/tests/doctests/HistoryAwareReferenceField.rst
  bika/lims/upgrade/v01_03_000.py
Labels: Bug, P0: Critical

#1261 Give priority to Analysis over Service when displaying Calculation information
  bika/lims/browser/analysisservice.py
  bika/lims/browser/templates/analysisservice_info.pt
  bika/lims/content/calculation.py
Labels: Bug, P3: Important

#1273 Disable caching of persistent objects in action pool
  bika/lims/workflow/__init__.py
Labels: Bug

#1274 Unauthorized error in get_method_instrument_constraints
  bika/lims/browser/analysis.zcml
Labels: Bug, P0: Critical

#1275 Action handlers pool code cleanup
  bika/lims/workflow/__init__.py
Labels: Cleanup, P1: Urgent

#1277 Traceback in Manage Analyses
  CHANGES.rst
  bika/lims/browser/workflow/__init__.py
  bika/lims/browser/workflow/analysisrequest.py
Labels: Bug, P0: Critical

#1268 Adding Facscalibur import instrument interface
  CHANGES.rst
  __init__.py
  bika/lims/exportimport/instruments/__init__.py
  bika/lims/exportimport/instruments/facscalibur/__init__.py
  bika/lims/exportimport/instruments/facscalibur/calibur/__init__.py
  bika/lims/exportimport/instruments/facscalibur/calibur/model_e9750.py
  bika/lims/exportimport/instruments/facscalibur/calibur/model_e9750_import.pt
Labels: PR: Rework-requested

#1251 Detection Limit handling in the Frontend/Backend
  bika/lims/browser/analyses/view.py
  bika/lims/browser/js/bika.lims.analysisservice.js
  bika/lims/browser/js/bika.lims.worksheet.js
  bika/lims/browser/js/coffee/bika.lims.analysisservice.coffee
  bika/lims/browser/js/coffee/bika.lims.worksheet.coffee
  bika/lims/browser/worksheet/views/analyses.py
  bika/lims/config.py
  bika/lims/content/abstractanalysis.py
  bika/lims/content/abstractroutineanalysis.py
  bika/lims/tests/test_calculations.py
  bika/lims/tests/test_limitdetections.py
Labels: Bug, Cleanup, P0: Critical, Version 1.3

#1282 Translate "Position" column key in transposed WS layout
  bika/lims/browser/worksheet/views/analyses_transposed.py
Labels: Enhancement, P4: Nice To Have

#1280 Remove bika.lims.utils.calcs.js
  bika/lims/profiles/default/jsregistry.xml
Labels: Cleanup

#1286 Inconsistencies on Detection Limit Operand submission
  bika/lims/browser/workflow/analysis.py
Labels: Bug, P0: Critical

#1287 Minor performance improvements for analysis guards
  bika/lims/content/abstractroutineanalysis.py
  bika/lims/content/analysis.py
Labels: Performance

#1284 Secondary Sample functionality
  bika/lims/adapters/configure.zcml
  bika/lims/adapters/widgetvisibility.py
  bika/lims/browser/analysisrequest/add2.py
  bika/lims/browser/js/bika.lims.analysisrequest.add.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee
  bika/lims/browser/viewlets/analysisrequest.py
  bika/lims/browser/viewlets/configure.zcml
  bika/lims/browser/viewlets/templates/secondary_ar_viewlet.pt
  bika/lims/catalog/analysisrequest_catalog.py
  bika/lims/catalog/indexers/analysisrequest.py
  bika/lims/catalog/indexers/configure.zcml
  bika/lims/content/analysisrequest.py
  bika/lims/content/bikasetup.py
  bika/lims/idserver.py
  bika/lims/interfaces/__init__.py
  bika/lims/tests/doctests/SecondaryAnalysisRequest.rst
  bika/lims/upgrade/v01_03_000.py
  bika/lims/utils/analysisrequest.py
  bika/lims/workflow/__init__.py
  bika/lims/workflow/indexes.py
Labels: Addition, P2: Very Important, PR: Rework-requested, Version 1.3

#1289 Adding Analyses to an existing Worksheet in a non-open status fails
  CHANGES.rst
  bika/lims/content/worksheet.py
  bika/lims/tests/doctests/WorkflowAnalysisAssign.rst
Labels: Bug

#1290 Retracting a calculated Analysis leads to an inconsistent state
  CHANGES.rst
  bika/lims/content/analysis.py
  bika/lims/tests/doctests/WorkflowAnalysisRetract.rst
  bika/lims/tests/doctests/WorkflowDuplicateAnalysisRetract.rst
  bika/lims/workflow/analysis/events.py
Labels: Bug, P2: Very Important

#1291 Allow the removal of empty Worksheets
  CHANGES.rst
  bika/lims/browser/worksheet/views/folder.py
  bika/lims/permissions.py
  bika/lims/permissions.zcml
  bika/lims/profiles/default/rolemap.xml
  bika/lims/profiles/default/workflows/bika_worksheet_workflow/definition.xml
  bika/lims/tests/doctests/WorkflowWorksheetRemove.rst
  bika/lims/workflow/worksheet/events.py
  bika/lims/workflow/worksheet/guards.py
Labels: Enhancement, P4: Nice To Have

#1292 Some labels still display "Analysis Requests"
  bika/lims/browser/publish/reports_listing.py
  bika/lims/content/arreport.py
Labels: P4: Nice To Have, Version 1.3

#1293 Linking LabContacts to LDAP-user not possible
  CHANGES.rst
  bika/lims/api/__init__.py
  bika/lims/browser/contact.py
  bika/lims/browser/templates/login_details.pt
  bika/lims/content/contact.py
  bika/lims/tests/doctests/ContactUser.rst
Labels: Bug, Cleanup, P1: Urgent

#1294 Fix traceback when in Lab Contact view
  bika/lims/content/labcontact.py
Labels: Bug, Cleanup, P0: Critical

#1295 Added WorkflowAnalysisRequestInvalidate doctest
  bika/lims/tests/doctests/WorkflowAnalysisRequestInvalidate.rst
Labels: Addition

#1297 Traceback on instrument results auto-import
  bika/lims/exportimport/instruments/__init__.py
Labels: Bug, P0: Critical

#1302 Fix bad import of API Exception Class
  bika/lims/validators.py
Labels: Bug, P0: Critical

#1303 Preserve review history in 1.3 upgrade
  bika/lims/api/__init__.py
  bika/lims/upgrade/v01_03_000.py
  bika/lims/workflow/__init__.py
Labels: Bug, P0: Critical

#1305 Ensure analyses from primary are removed after being added to partitions
  bika/lims/browser/partition_magic.py
Labels: Bug, P0: Critical

#1304 Some Items show the Display/State/Add menu
  bika/lims/browser/client/views/analysisrequests.py
  bika/lims/browser/methodfolder.py
  bika/lims/browser/pricelist.py
  bika/lims/browser/pricelist.zcml
  bika/lims/browser/referencesample.py
  bika/lims/browser/referencesample.zcml
  bika/lims/browser/templates/pricelist_content.pt
  bika/lims/browser/templates/pricelist_email.pt
  bika/lims/browser/templates/pricelist_email_form.pt
  bika/lims/browser/templates/pricelist_view.pt
  bika/lims/content/bikasetup.py
  bika/lims/content/configure.zcml
  bika/lims/content/laboratory.py
  bika/lims/content/methods.py
  bika/lims/content/organisation.py
  bika/lims/content/person.py
  bika/lims/content/pricelist.py
  bika/lims/content/pricelistfolder.py
  bika/lims/content/referencesamplesfolder.py
  bika/lims/content/supplier.py
  bika/lims/content/suppliercontact.py
  bika/lims/content/supplyorderfolder.py
  bika/lims/controlpanel/bika_identifiertypes.py
  bika/lims/controlpanel/bika_referencedefinitions.py
  bika/lims/exportimport/dataimport.py
  bika/lims/profiles/default/structure/.objects
  bika/lims/profiles/default/structure/arimports/.objects
  bika/lims/profiles/default/structure/arimports/.properties
  bika/lims/profiles/default/types/BikaSetup.xml
  bika/lims/profiles/default/types/Client.xml
  bika/lims/profiles/default/types/Laboratory.xml
  bika/lims/profiles/default/types/Method.xml
  bika/lims/profiles/default/types/Methods.xml
  bika/lims/profiles/default/types/Pricelist.xml
  bika/lims/profiles/default/types/PricelistFolder.xml
  bika/lims/profiles/default/types/ReferenceDefinition.xml
  bika/lims/profiles/default/types/ReferenceSamplesFolder.xml
  bika/lims/profiles/default/types/Supplier.xml
  bika/lims/profiles/default/types/SupplierContact.xml
  bika/lims/profiles/default/types/SupplyOrderFolder.xml
  bika/lims/setuphandlers.py
  bika/lims/subscribers/configure.zcml
  bika/lims/subscribers/pricelist.py
  bika/lims/upgrade/v01_03_000.py
Labels: Cleanup, P4: Nice To Have, UI & UX, Version 1.3

#1307 Traceback when using "Submit" of the global WF menu
  bika/lims/browser/workflow/analysis.py
  bika/lims/tests/doctests/WorkflowAnalysisReject.rst
  bika/lims/workflow/analysis/events.py
Labels: Bug, P0: Critical, PR: Not Ready

#1308 Remove install screen
  CHANGES.rst
  bika/lims/browser/overrides.zcml
  bika/lims/browser/templates/plone-addsite.pt
Labels: Cleanup, UI & UX, Version 1.3

#1309 Samples rejection view
  CHANGES.rst
  bika/lims/browser/analysisrequest/configure.zcml
  bika/lims/browser/analysisrequest/reject_samples.py
  bika/lims/browser/analysisrequest/templates/analysisrequest_analyses.pt
  bika/lims/browser/analysisrequest/templates/analysisrequest_manage_results.pt
  bika/lims/browser/analysisrequest/templates/reject_samples.pt
  bika/lims/browser/templates/header_table.pt
  bika/lims/browser/viewlets/analysisrequest.py
  bika/lims/browser/viewlets/configure.zcml
  bika/lims/browser/viewlets/templates/rejected_ar_viewlet.pt
  bika/lims/browser/workflow/analysisrequest.py
  bika/lims/browser/workflow/configure.zcml
  bika/lims/content/analysisrequest.py
  bika/lims/content/bikasetup.py
  bika/lims/profiles/default/workflows/bika_ar_workflow/definition.xml
  bika/lims/workflow/analysisrequest/events.py
  bika/lims/workflow/analysisrequest/guards.py
Labels: Bug, P2: Very Important

#1310 Support for radio copy in Sample Add view
  CHANGES.rst
  bika/lims/browser/js/bika.lims.analysisrequest.add.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Addition, P1: Urgent

#1311 Removed plone-overview override
  bika/lims/browser/overrides.zcml
  bika/lims/browser/templates/plone-overview.pt
Labels: Cleanup

#1312 Reject adapter does not consider analyses have reject action too
  bika/lims/browser/workflow/__init__.py
  bika/lims/browser/workflow/analysisrequest.py
Labels: Bug, P0: Critical
