Repository senaite/senaite.core, pull requests merged in 2019-05, with the labels that each got.

#1352 Make timeit() to not display args by default
  CHANGES.rst
  bika/lims/decorators.py
Labels: Enhancement

#1355 Use id in api.get_id if a brain and id attribute is present
  CHANGES.rst
  bika/lims/api/__init__.py
Labels: Enhancement, P0: Critical

#1357 Fixed issue with Analysis and Publication Spec on ARs
  CHANGES.rst
  bika/lims/content/analysisrequest.py
Labels: Bug

#1358 Fixed icons for lab contacts
  bika/lims/profiles/default/controlpanel.xml
  bika/lims/profiles/default/types/Department.xml
  bika/lims/profiles/default/types/LabContacts.xml
  bika/lims/upgrade/v01_03_001.py
Labels: Bug, P3: Important

#1342 Instrument result importing changes wrt senaite.instruments
  CHANGES.rst
  bika/lims/content/abstractanalysis.py
  bika/lims/exportimport/instruments/__init__.py
  bika/lims/exportimport/instruments/agilent/__init__.py
  bika/lims/exportimport/instruments/agilent/masshunter/__init__.py
  bika/lims/exportimport/instruments/agilent/masshunter/masshunter.py
  bika/lims/exportimport/instruments/agilent/masshunter/quantitative.py
  bika/lims/exportimport/instruments/agilent/masshunter/quantitative_import.pt
  bika/lims/exportimport/instruments/agilent/masshunter/samples/Agilent-output-edited-by-pkm.csv
  bika/lims/exportimport/instruments/agilent/masshunter/samples/quantitative.csv
  bika/lims/tests/files/instruments/agilent.masshunter.masshunter.csv
Labels: Cleanup, PR: Rework-requested

#1361 Fix leap sample ID sequence after secondary sample
  CHANGES.rst
  bika/lims/content/analysisrequest.py
  bika/lims/idserver.py
Labels: Bug, P1: Urgent

#1362 Remove unnecessary code from worksheet listing that slows down the rendering
  CHANGES.rst
  bika/lims/browser/worksheet/views/folder.py
  bika/lims/catalog/worksheet_catalog.py
  bika/lims/upgrade/v01_03_001.py
Labels: Enhancement, P1: Urgent

#1364 Fix Traceback on the ID Server Seeding View
  bika/lims/browser/idserver/templates/numbergenerator.pt
  bika/lims/browser/idserver/view.py
Labels: Bug

#1363 Slightly better performance when retrieving analysis dependencies
  bika/lims/browser/workflow/__init__.py
  bika/lims/content/abstractroutineanalysis.py
Labels: Enhancement, P1: Urgent

#1367 Clients can see interim values of analyses not yet verified
  CHANGES.rst
  bika/lims/browser/analyses/view.py
Labels: Bug, P1: Urgent

#1359 Remove stale Sample/Partition objects from ZODB
  CHANGES.rst
  bika/lims/browser/fields/aranalysesfield.py
  bika/lims/content/abstractroutineanalysis.py
  bika/lims/content/analysisrequest.py
  bika/lims/content/sample.py
  bika/lims/content/samplepartition.py
  bika/lims/upgrade/v01_03_001.py
Labels: Cleanup

#1369 Add getter to access the title of the sample condition directly
  CHANGES.rst
  bika/lims/content/analysisrequest.py
Labels: Enhancement, P4: Nice To Have

#1373 Reduce the noise in the diff for object paths
  bika/lims/api/snapshot.py
Labels: Enhancement, P3: Important

#1368 Fix WF state propagation on partition verification
  CHANGES.rst
  bika/lims/workflow/analysisrequest/guards.py
Labels: Bug, P1: Urgent

#1371 Allow sample publication without sending Email
  CHANGES.rst
  bika/lims/__init__.py
  bika/lims/browser/publish/reports_listing.py
  bika/lims/browser/workflow/client.py
  bika/lims/browser/workflow/configure.zcml
Labels: Enhancement, P3: Important

#1349 Refactor ajaxGetImportTemplate to find instrument import templates in addons
  bika/lims/exportimport/dataimport.py
Labels: Cleanup

#1382 Fix double publication of the same sample when using multi-reports
  CHANGES.rst
  bika/lims/browser/publish/emailview.py
Labels: Bug, P1: Urgent

#1383 Overcome "Can't delete target" in upgrade step 1.3.1
  bika/lims/upgrade/v01_03_001.py
Labels: Bug, P1: Urgent

#1384 Added missing Html Field to ARReport
  CHANGES.rst
  bika/lims/content/arreport.py
Labels: Bug

#1386 No auto-rejection of Sample when rejection reasons are set in Add form
  CHANGES.rst
  bika/lims/utils/analysisrequest.py
Labels: Bug, P1: Urgent
