Repository senaite/senaite.core, pull requests merged in 2019-01, with the labels that each got.

#1188 Fixed listing item deselection not possible
  bika/lims/browser/listing/src/listing.coffee
  bika/lims/browser/listing/static/js/senaite.core.listing.js
Labels: Bug, P3: Important

#1189 Listing: Skip WS remarks row for reassignable slots
  bika/lims/browser/listing/src/components/TableRows.coffee
  bika/lims/browser/listing/static/js/senaite.core.listing.js
Labels: Bug, P1: Urgent, UI & UX, Version 1.3

#1190 Fixed evolution chart for reference analyses
  CHANGES.rst
  bika/lims/browser/referencesample.py
  bika/lims/browser/referencesample.zcml
  bika/lims/browser/templates/referencesample_analyses.pt
Labels: Bug, P2: Very Important, UI & UX, Version 1.3

#1191 Some worksheets pre-1.3 with published analyses remain in open status
  CHANGES.rst
  bika/lims/profiles/default/workflows/bika_worksheet_workflow/definition.xml
  bika/lims/skins/bika/guard_submit_transition.py
  bika/lims/upgrade/v01_03_000.py
  bika/lims/workflow/worksheet/guards.py
Labels: Version 1.3

#1193 Added viewlets for partition and primary ARs
  CHANGES.rst
  bika/lims/browser/viewlets/analysisrequest.py
  bika/lims/browser/viewlets/configure.zcml
  bika/lims/browser/viewlets/templates/partition_ar_viewlet.pt
  bika/lims/browser/viewlets/templates/primary_ar_viewlet.pt
Labels: Enhancement, Version 1.3

#1192 Integrate Container and Preservation in Partition Magic
  CHANGES.rst
  bika/lims/adapters/widgetvisibility.py
  bika/lims/browser/analysisrequest/workflow.py
  bika/lims/browser/partition_magic.py
  bika/lims/browser/templates/partition_magic.pt
  bika/lims/profiles/default/workflows/bika_ar_workflow/definition.xml
Labels: Enhancement, Version 1.3

#1194 Prevent reseeding of AR when upgrade is run more than once
  bika/lims/upgrade/v01_03_000.py
Labels: Bug, Version 1.3

#1196 Containers and Preservations appear duplicated in selection lists
  bika/lims/browser/templates/partition_magic.pt
Labels: Bug, Version 1.3

#1198 Analysis Requests nav item keeps its old name after upgrade
  bika/lims/upgrade/v01_03_000.py
Labels: Bug, Version 1.3

#1197 Remove old files and directories
  bika/lims/scripts/blis.py
  bika/lims/scripts/id-server.py
  bika/lims/scripts/start-id-server
  bika/lims/scripts/start-id-server.bat
  bika/lims/skins/bika/misc.py
  bika/lims/skins/bika/redirect_to_client_home.py
  docs/resources/Interface_GeneXpert_documentation.pdf
  docs/resources/bika_sample_workflow.dia
  docs/resources/bika_sample_workflow.svg
  docs/resources/imm_results_entry_behavior.png
Labels: Cleanup, Version 1.3

#1199 Add "Auto-partition" bool field in Template
  bika/lims/browser/analysisrequest/workflow.py
  bika/lims/content/artemplate.py
Labels: Enhancement, Version 1.3

#1200 Listing: Set the value directly on the field in the ajax endpoint
  bika/lims/browser/analyses/view.py
  bika/lims/browser/listing/ajax.py
  bika/lims/browser/listing/view.py
Labels: Bug, P0: Critical

#1206 Make use of adapters for import and export instrument interfaces
  CHANGES.rst
  bika/lims/content/instrument.py
  bika/lims/exportimport/dataimport.py
  bika/lims/exportimport/instruments/__init__.py
Labels: Enhancement

#1207 Make use of adapters for instruments results auto-import
  CHANGES.rst
  bika/lims/browser/resultsimport/resultsimport.py
  bika/lims/content/bikasetup.py
  bika/lims/exportimport/instruments/__init__.py
Labels: Enhancement

#1208 Notify object modified event in ajax set field endpoint
  bika/lims/browser/listing/ajax.py
Labels: Bug, P1: Urgent

#1212 Fix typo in SamplingFieldsVisibility
  CHANGES.rst
  bika/lims/adapters/widgetvisibility.py
Labels: Bug

#1213 Fix instrument notification display in Manage Results View
  CHANGES.rst
  bika/lims/browser/analysisrequest/manage_results.py
Labels: Bug

#1215 Do not modify the analysis ID on retraction
  CHANGES.rst
  bika/lims/tests/doctests/WorkflowAnalysisReject.rst
  bika/lims/tests/doctests/WorkflowAnalysisRetract.rst
  bika/lims/tests/test_AnalysisRequest_retract.py
  bika/lims/workflow/analysis/events.py
Labels: Cleanup

#1214 Disallow entry of analysis results if the sample is not yet received
  CHANGES.rst
  bika/lims/browser/analyses/view.py
  bika/lims/browser/analysisrequest/manage_analyses.py
  bika/lims/browser/analysisrequest/tables.py
  bika/lims/browser/fields/aranalysesfield.py
  bika/lims/browser/listing/ajax.py
  bika/lims/browser/listing/view.py
  bika/lims/content/abstractanalysis.py
  bika/lims/content/abstractbaseanalysis.py
  bika/lims/content/worksheet.py
  bika/lims/profiles/default/workflows/bika_analysis_workflow/definition.xml
  bika/lims/profiles/default/workflows/bika_duplicateanalysis_workflow/definition.xml
  bika/lims/profiles/default/workflows/bika_referenceanalysis_workflow/definition.xml
  bika/lims/subscribers/analysis.py
  bika/lims/tests/doctests/AnalysisRequestInvalidate.rst
  bika/lims/tests/doctests/QCAnalysesWithInterimFieldsOnAWorksheet.rst
  bika/lims/tests/doctests/WorkflowAnalysisAssign.rst
  bika/lims/tests/doctests/WorkflowAnalysisSubmit.rst
  bika/lims/tests/test_ARImport.py
  bika/lims/upgrade/v01_03_000.py
  bika/lims/utils/analysisrequest.py
  bika/lims/workflow/analysis/guards.py
  bika/lims/workflow/analysisrequest/events.py
  bika/lims/workflow/analysisrequest/guards.py
Labels: Bug, P2: Very Important, UI & UX, Version 1.3

#1216 Allow manual entry (if granted) of results if instrument is invalid
  CHANGES.rst
  bika/lims/browser/analyses/view.py
Labels: Bug, P1: Urgent

#1217 Added filtering buttons in Analyses listings (Valid, Invalid and All)
  CHANGES.rst
  bika/lims/browser/analyses/view.py
  bika/lims/browser/analysisrequest/tables.py
  bika/lims/browser/fields/aranalysesfield.py
Labels: Enhancement, UI & UX, Version 1.3

#1218 Display "unassign" transition in Worksheet context only
  bika/lims/content/worksheet.py
  bika/lims/workflow/analysis/guards.py
Labels: Enhancement, Version 1.3

#1220 Traceback in Manage Analysis when Specs are disabled in the Setup
  bika/lims/browser/analysisrequest/workflow.py
Labels: Bug

#1221 Fixed Analysis Edit Permission in Registered State
  bika/lims/browser/analyses/view.py
  bika/lims/profiles/default/workflows/bika_analysis_workflow/definition.xml
  bika/lims/tests/doctests/WorkflowAnalysisSubmit.rst
Labels: Bug, P1: Urgent

#1223 Replace "Request ID" header from Samples listings by "Sample ID"
  bika/lims/browser/analysisrequest/analysisrequests.py
Labels: Version 1.3
