Repository senaite/senaite.core, pull requests merged in 2019-02, with the labels that each got.

#1225 Listing calculations performance
  bika/lims/browser/listing/ajax.py
  bika/lims/browser/listing/src/components/Table.coffee
  bika/lims/browser/listing/src/listing.coffee
  bika/lims/browser/listing/static/js/senaite.core.listing.js
Labels: Bug, P3: Important

#1222 Added User and Security API
  CHANGES.rst
  bika/lims/api/__init__.py
  bika/lims/api/security.py
  bika/lims/api/user.py
  bika/lims/tests/doctests/API_security.rst
  bika/lims/tests/doctests/API_user.rst
Labels: Addition, P4: Nice To Have

#1226 Outsourced ReactJS listing component to senaite.core.listing Add-on
  bika/lims/browser/bika_listing.py
  bika/lims/browser/configure.zcml
  bika/lims/browser/listing/.gitignore
  bika/lims/browser/listing/README.md
  bika/lims/browser/listing/__init__.py
  bika/lims/browser/listing/ajax.py
  bika/lims/browser/listing/configure.zcml
  bika/lims/browser/listing/decorators.py
  bika/lims/browser/listing/package.json
  bika/lims/browser/listing/src/api.coffee
  bika/lims/browser/listing/src/components/Button.coffee
  bika/lims/browser/listing/src/components/ButtonBar.coffee
  bika/lims/browser/listing/src/components/CalculatedField.coffee
  bika/lims/browser/listing/src/components/Checkbox.coffee
  bika/lims/browser/listing/src/components/FilterBar.coffee
  bika/lims/browser/listing/src/components/HiddenField.coffee
  bika/lims/browser/listing/src/components/Loader.coffee
  bika/lims/browser/listing/src/components/Loader.css
  bika/lims/browser/listing/src/components/MultiSelect.coffee
  bika/lims/browser/listing/src/components/NumericField.coffee
  bika/lims/browser/listing/src/components/Pagination.coffee
  bika/lims/browser/listing/src/components/ReadonlyField.coffee
  bika/lims/browser/listing/src/components/RemarksField.coffee
  bika/lims/browser/listing/src/components/SearchBox.coffee
  bika/lims/browser/listing/src/components/Select.coffee
  bika/lims/browser/listing/src/components/Table.coffee
  bika/lims/browser/listing/src/components/TableCategoryRow.coffee
  bika/lims/browser/listing/src/components/TableCell.coffee
  bika/lims/browser/listing/src/components/TableCells.coffee
  bika/lims/browser/listing/src/components/TableContextMenu.coffee
  bika/lims/browser/listing/src/components/TableHeaderCell.coffee
  bika/lims/browser/listing/src/components/TableHeaderRow.coffee
  bika/lims/browser/listing/src/components/TableRemarksRow.coffee
  bika/lims/browser/listing/src/components/TableRow.coffee
  bika/lims/browser/listing/src/components/TableRows.coffee
  bika/lims/browser/listing/src/components/TableTransposedCell.coffee
  bika/lims/browser/listing/src/listing.coffee
  bika/lims/browser/listing/src/listing.css
  bika/lims/browser/listing/static/js/senaite.core.listing.js
  bika/lims/browser/listing/templates/contents_table.pt
  bika/lims/browser/listing/templates/listing.pt
  bika/lims/browser/listing/view.py
  bika/lims/browser/listing/webpack.config.js
  bika/lims/profiles/default/jsregistry.xml
  bika/lims/profiles/default/metadata.xml
  bika/lims/upgrade/v01_03_000.py
  buildout.cfg
  setup.py
Labels: Cleanup, Version 1.3

#1224 Replace publication engine with SENAITE IMPRESS
  CHANGES.rst
  bika/lims/browser/analysisrequest/configure.zcml
  bika/lims/browser/analysisrequest/publish.py
  bika/lims/browser/analysisrequest/templates/analysisrequest_publish.pt
  bika/lims/browser/analysisrequest/templates/reports/Multi_AR_default.css
  bika/lims/browser/analysisrequest/templates/reports/Multi_AR_default.pt
  bika/lims/browser/analysisrequest/templates/reports/TAL_field_reference.css
  bika/lims/browser/analysisrequest/templates/reports/TAL_field_reference.pt
  bika/lims/browser/analysisrequest/templates/reports/bydepartment.css
  bika/lims/browser/analysisrequest/templates/reports/bydepartment.pt
  bika/lims/browser/analysisrequest/templates/reports/default.css
  bika/lims/browser/analysisrequest/templates/reports/default.pt
  bika/lims/browser/analysisrequest/templates/reports/example_1.css
  bika/lims/browser/analysisrequest/templates/reports/example_1.pt
  bika/lims/browser/batch/configure.zcml
  bika/lims/browser/batch/publish.py
  bika/lims/browser/configure.zcml
  bika/lims/browser/js/bika.lims.analysisrequest.publish.js
  bika/lims/browser/js/bika.lims.loader.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.publish.coffee
  bika/lims/browser/publish/__init__.py
  bika/lims/browser/publish/configure.zcml
  bika/lims/browser/publish/downloadview.py
  bika/lims/browser/publish/emailview.py
  bika/lims/browser/publish/reports_listing.py
  bika/lims/browser/publish/static/coffee/email.coffee
  bika/lims/browser/publish/static/css/email.css
  bika/lims/browser/publish/static/img/attachment.png
  bika/lims/browser/publish/static/img/pdf.png
  bika/lims/browser/publish/static/js/email.js
  bika/lims/browser/publish/templates/email.pt
  bika/lims/browser/publish/templates/email_template.pt
  bika/lims/config.py
  bika/lims/content/arreport.py
  bika/lims/content/bikasetup.py
  bika/lims/content/client.py
  bika/lims/content/contact.py
  bika/lims/content/labcontact.py
  bika/lims/exportimport/setupdata/__init__.py
  bika/lims/interfaces/__init__.py
  bika/lims/profiles/default/jsregistry.xml
  bika/lims/profiles/default/registry.xml
  bika/lims/profiles/default/types/Client.xml
  bika/lims/upgrade/v01_03_000.py
  bika/lims/vocabularies/__init__.py
  bika/lims/vocabularies/configure.zcml
  setup.py
Labels: Cleanup, Version 1.3

#1228 Partition IDs based on their Parent Analysis Request
  bika/lims/browser/idserver/view.py
  bika/lims/content/analysisrequest.py
  bika/lims/content/bikasetup.py
  bika/lims/idserver.py
  bika/lims/interfaces/__init__.py
  bika/lims/upgrade/v01_03_000.py
Labels: Enhancement, Version 1.3

#1230 Add Client ID Column in Sample Listing
  CHANGES.rst
  bika/lims/browser/analysisrequest/analysisrequests.py
  bika/lims/catalog/analysisrequest_catalog.py
  bika/lims/upgrade/v01_03_000.py
Labels: Enhancement, P3: Important, Version 1.3

#1231 Add Client ID Column in Batch Listing
  CHANGES.rst
  bika/lims/browser/batchfolder.py
  bika/lims/browser/batchfolder.zcml
  bika/lims/setuphandlers.py
  bika/lims/upgrade/v01_03_000.py
Labels: Enhancement, P3: Important, Version 1.3

#1232 Remove `uniquefieldvalidator` for Client Names
  CHANGES.rst
  bika/lims/content/organisation.py
  bika/lims/tests/test_validation.py
Labels: Cleanup, Enhancement, P4: Nice To Have, Version 1.3

#1229 Better handling of IDs without separator
  bika/lims/idserver.py
  bika/lims/tests/doctests/IDServer.rst
Labels: P3: Important, Version 1.3

#1240 Support action-specific `workflow_action` requests with named adapters
  CHANGES.rst
  bika/lims/browser/analyses/workflow.py
  bika/lims/browser/analysisrequest/__init__.py
  bika/lims/browser/analysisrequest/analysisrequests.py
  bika/lims/browser/analysisrequest/configure.zcml
  bika/lims/browser/analysisrequest/manage_analyses.py
  bika/lims/browser/analysisrequest/workflow.py
  bika/lims/browser/batch/configure.zcml
  bika/lims/browser/batch/workflow.py
  bika/lims/browser/bika_listing.py
  bika/lims/browser/bika_listing.zcml
  bika/lims/browser/client/__init__.py
  bika/lims/browser/client/configure.zcml
  bika/lims/browser/client/workflow.py
  bika/lims/browser/configure.zcml
  bika/lims/browser/js/bika.lims.analysisrequest.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.coffee
  bika/lims/browser/workflow/__init__.py
  bika/lims/browser/workflow/analysis.py
  bika/lims/browser/workflow/analysisrequest.py
  bika/lims/browser/workflow/configure.zcml
  bika/lims/browser/workflow/worksheet.py
  bika/lims/browser/worksheet/configure.zcml
  bika/lims/browser/worksheet/workflow.py
  bika/lims/content/analysisrequest.py
  bika/lims/interfaces/__init__.py
  bika/lims/tests/doctests/API.rst
  bika/lims/utils/workflow/__init__.py
  bika/lims/utils/workflow/schedulesampling.py
Labels: P1: Urgent, Version 1.3

#1242 Extend API
  bika/lims/api/__init__.py
  bika/lims/tests/doctests/API.rst
Labels: Addition, Cleanup, Enhancement, P3: Important, Version 1.3

#1244 Added "Body for Sample Invalidation email" field in setup
  CHANGES.rst
  bika/lims/browser/workflow/analysisrequest.py
  bika/lims/content/bikasetup.py
  bika/lims/upgrade/v01_03_000.py
  bika/lims/workflow/analysisrequest/events.py
Labels: P2: Very Important, Version 1.3

#1245 Not all clients are shown in clients drop menu for Productivity Reports
  CHANGES.rst
  bika/lims/browser/reports/selection_macros/__init__.py
Labels: Bug, P1: Urgent

#1243 ID Server Suffix Support for Retested ARs
  CHANGES.rst
  bika/lims/content/bikasetup.py
  bika/lims/idserver.py
  bika/lims/interfaces/__init__.py
  bika/lims/tests/doctests/ARAnalysesField.rst
  bika/lims/tests/doctests/AnalysisRequestInvalidate.rst
  bika/lims/tests/doctests/IDServer.rst
  bika/lims/upgrade/v01_03_000.py
  bika/lims/utils/analysisrequest.py
Labels: Enhancement, P3: Important, Version 1.3

#1246 Allow the creation of empty partitions (without analyses)
  bika/lims/browser/partition_magic.py
  bika/lims/utils/analysisrequest.py
Labels: Version 1.3

#1248 Move create_partitions logic to utils package
  bika/lims/browser/partition_magic.py
  bika/lims/utils/analysisrequest.py
Labels: Cleanup, Version 1.3

#1249 Render attachments in report in worksheets too
  CHANGES.rst
  bika/lims/browser/attachment.py
Labels: Enhancement

#1255 Fix Analyst in Analyses
  bika/lims/content/abstractanalysis.py
  bika/lims/tests/doctests/WorkflowAnalysisAssign.rst
  bika/lims/upgrade/v01_03_000.py
Labels: Bug
