Repository senaite/senaite.core, pull requests merged in 2020-02, with the labels that each got.

#1513 Better Ajax Loader for Sample Add Form
  CHANGES.rst
  bika/lims/browser/bootstrap.py
  bika/lims/browser/bootstrap.zcml
  bika/lims/browser/configure.zcml
  bika/lims/browser/controlpanel.py
  bika/lims/browser/controlpanel.zcml
  bika/lims/browser/js/bika.lims.analysisrequest.add.js
  bika/lims/browser/js/bika.lims.site.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee
  bika/lims/browser/js/coffee/bika.lims.site.coffee
  bika/lims/browser/templates/plone.app.controlpanel.overview.pt
  bika/lims/skins/bika/base_properties.props
  bika/lims/skins/bika/main_template.pt
  bika/lims/skins/bika/ploneCustom.css.dtml
Labels: Cleanup, Enhancement

#1514 Ensure analysis' result range keeps all range subfields
  bika/lims/browser/fields/aranalysesfield.py
Labels: P0: Critical

#1515 Moved Setup View into Core
  CHANGES.rst
  bika/lims/browser/controlpanel.py
  bika/lims/browser/controlpanel.zcml
  bika/lims/browser/css/setupview.css
  bika/lims/browser/images/gears.png
  bika/lims/browser/templates/setupview.pt
  bika/lims/browser/viewlets/configure.zcml
  bika/lims/browser/viewlets/instruments.py
  bika/lims/browser/viewlets/setupbutton.py
  bika/lims/browser/viewlets/templates/setupbutton.pt
Labels: Cleanup

#1516 Consider analyses with result options or string result in duplicate valid range
  CHANGES.rst
  bika/lims/api/analysis.py
  bika/lims/browser/analyses/view.py
  bika/lims/catalog/analysis_catalog.py
  bika/lims/content/duplicateanalysis.py
  bika/lims/content/instrument.py
  bika/lims/tests/doctests/DuplicateResultsRange.rst
  bika/lims/upgrade/v01_03_003.py
Labels: Enhancement, P1: Urgent

#1517 Integrate senaite.core.spotlight
  CHANGES.rst
  bika/lims/profiles/default/actions.xml
  bika/lims/upgrade/v01_03_003.py
  buildout.cfg
  setup.py
Labels: Addition

#1520 JavaScripts/CSS Integration and Cleanup
  CHANGES.rst
  bika/lims/browser/analysisrequest/templates/ar_add2.pt
  bika/lims/browser/bootstrap/__init__.py
  bika/lims/browser/bootstrap/bootstrap.py
  bika/lims/browser/bootstrap/configure.zcml
  bika/lims/browser/bootstrap/static/css/bootstrap-integration.css
  bika/lims/browser/bootstrap/static/css/bootstrap-theme.min.css
  bika/lims/browser/bootstrap/static/css/bootstrap-theme.min.css.map
  bika/lims/browser/bootstrap/static/css/bootstrap.min.css
  bika/lims/browser/bootstrap/static/css/bootstrap.min.css.map
  bika/lims/browser/bootstrap/static/fonts/glyphicons-halflings-regular.eot
  bika/lims/browser/bootstrap/static/fonts/glyphicons-halflings-regular.svg
  bika/lims/browser/bootstrap/static/fonts/glyphicons-halflings-regular.ttf
  bika/lims/browser/bootstrap/static/fonts/glyphicons-halflings-regular.woff
  bika/lims/browser/bootstrap/static/fonts/glyphicons-halflings-regular.woff2
  bika/lims/browser/bootstrap/static/js/bootstrap-integration.js
  bika/lims/browser/bootstrap/static/js/bootstrap.min.js
  bika/lims/browser/configure.zcml
  bika/lims/browser/css/fonts/glyphicons-halflings-regular.eot
  bika/lims/browser/css/fonts/glyphicons-halflings-regular.svg
  bika/lims/browser/css/fonts/glyphicons-halflings-regular.ttf
  bika/lims/browser/css/fonts/glyphicons-halflings-regular.woff
  bika/lims/browser/css/fonts/glyphicons-halflings-regular.woff2
  bika/lims/browser/js/coffee/bootstrap-integration.coffee
  bika/lims/browser/js/thirdparty/README.md
  bika/lims/browser/js/thirdparty/handlebars.min-v4.7.2.js
  bika/lims/browser/js/thirdparty/handlebars/handlebars.js
  bika/lims/browser/js/thirdparty/jquery-2.2.4.min.js
  bika/lims/browser/js/thirdparty/jquery-migrate-1.4.1.min.js
  bika/lims/browser/js/thirdparty/jquery-ui-timepicker-addon-i18n.min.js
  bika/lims/browser/js/thirdparty/jquery-ui-timepicker-addon.min.js
  bika/lims/browser/js/thirdparty/jquery/jquery-query-2.1.7.js
  bika/lims/browser/js/thirdparty/jquery/jquery-timepicker-i18n.js
  bika/lims/browser/js/thirdparty/jquery/jquery-timepicker.js
  bika/lims/profiles/default/cssregistry.xml
  bika/lims/profiles/default/jsregistry.xml
  bika/lims/profiles/default/tinymce.xml
  bika/lims/upgrade/v01_03_003.py
Labels: Addition, Cleanup

#1522 Fix sporadical timeout issue when adding new samples/remarks
  CHANGES.rst
  bika/lims/browser/js/bika.lims.analysisrequest.add.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee
  bika/lims/browser/js/coffee/bika_widgets/remarkswidget.coffee
  bika/lims/skins/bika/bika_widgets/remarkswidget.js
Labels: Bug, P1: Urgent

#1523 Moved Installation Screens into core
  CHANGES.rst
  bika/lims/configure.zcml
  bika/lims/install/__init__.py
  bika/lims/install/adapters.py
  bika/lims/install/configure.zcml
  bika/lims/install/images/favicon.ico
  bika/lims/install/images/icon.png
  bika/lims/install/images/logo.png
  bika/lims/install/templates/senaite-addsite.pt
  bika/lims/install/templates/senaite-overview.pt
Labels: Addition, Cleanup

#1524 Fixed wrong placement of ajax timeout option
  bika/lims/browser/js/coffee/bika_widgets/remarkswidget.coffee
  bika/lims/skins/bika/bika_widgets/remarkswidget.js
Labels: P1: Urgent

#1525 Fix error when creating a partition as analyst user
  CHANGES.rst
  bika/lims/browser/analysisrequest/analysisrequests.py
  bika/lims/browser/configure.zcml
  bika/lims/profiles/default/workflows/bika_ar_workflow/definition.xml
  bika/lims/upgrade/v01_03_003.py
Labels: Bug, P2: Very Important

#1518 Clean some stale indexes from analysis_catalog
  CHANGES.rst
  bika/lims/browser/worksheet/views/add_analyses.py
  bika/lims/catalog/analysis_catalog.py
  bika/lims/content/abstractroutineanalysis.py
  bika/lims/content/analysisrequest.py
  bika/lims/upgrade/v01_03_003.py
  bika/lims/workflow/analysisrequest/events.py
Labels: Cleanup

#1526 Fixed legacy remarks parsing
  bika/lims/browser/fields/remarksfield.py
Labels: Bug, P1: Urgent

#1528 Update translations
  CONTRIBUTORS.rst
  bika/lims/locales/cs/LC_MESSAGES/senaite.core.po
  bika/lims/locales/uk_UA/LC_MESSAGES/senaite.core.po
Labels: Cleanup

#1529 Moved contentmenu provider into core
  CHANGES.rst
  bika/lims/browser/configure.zcml
  bika/lims/browser/contentmenu.py
  bika/lims/browser/contentmenu.zcml
  bika/lims/browser/templates/plone.app.contentmenu.contentmenu.pt
Labels: Cleanup

#1532 Updated jQuery Barcode to version 2.2.0
  CHANGES.rst
  bika/lims/browser/js/thirdparty/README.md
  bika/lims/browser/js/thirdparty/jquery/jquery-barcode-2.0.2.js
  bika/lims/browser/js/thirdparty/jquery/jquery-barcode-2.2.0.min.js
  bika/lims/profiles/default/jsregistry.xml
  bika/lims/upgrade/v01_03_003.py
Labels: Cleanup, Enhancement

#1533 Fix traceback from log when rendering stickers preview
  CHANGES.rst
  bika/lims/browser/templates/stickers_preview.pt
Labels: Cleanup

#1534 Integrate browser resources from senaite.lims
  CHANGES.rst
  bika/lims/monkey/__init__.py
  bika/lims/monkey/add_senaite_site.py
  bika/lims/monkey/configure.zcml
  bika/lims/monkey/overlayhelpers.js
  bika/lims/skins/bika/favicon.ico
  bika/lims/skins/bika/global_statusmessage.pt
  bika/lims/skins/bika/login_form.cpt
  bika/lims/skins/bika/login_form.cpt.metadata
  bika/lims/skins/bika/logo.png
  bika/lims/skins/bika/logo_print.png
Labels: Cleanup

#1535 Remove `zcatalog` monkey (and `getRequestUID` index)
  CHANGES.rst
  bika/lims/browser/analysisrequest/tables.py
  bika/lims/catalog/analysis_catalog.py
  bika/lims/monkey/configure.zcml
  bika/lims/monkey/zcatalog.py
  bika/lims/upgrade/v01_03_003.py
Labels: Cleanup

#1536 Integrated Setup and Profiles from senaite.lims
  CHANGES.rst
  bika/lims/profiles/default/actions.xml
  bika/lims/profiles/default/portal_languages.xml
  bika/lims/profiles/default/portlets.xml
  bika/lims/setuphandlers.py
  bika/lims/upgrade/v01_03_003.py
Labels: Cleanup

#1539 Avoid unnecessary Price recalculations in Sample Add Form
  CHANGES.rst
  bika/lims/browser/js/bika.lims.analysisrequest.add.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Enhancement

#1540 Fix flushing CCEmail fields in Sample Add Form
  CHANGES.rst
  bika/lims/browser/analysisrequest/add2.py
  bika/lims/browser/js/bika.lims.analysisrequest.add.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Bug, P3: Important

#1541 Remove add/edit options of ReferenceWidget
  CHANGES.rst
  bika/lims/browser/bootstrap/static/css/bootstrap-integration.css
  bika/lims/browser/images/edit.png
  bika/lims/browser/images/edit_big.png
  bika/lims/browser/js/bika.lims.site.js
  bika/lims/browser/js/coffee/bika.lims.site.coffee
  bika/lims/browser/widgets/referencewidget.py
  bika/lims/content/analysisrequest.py
  bika/lims/skins/bika/bika_widgets/referencewidget.js
  bika/lims/skins/bika/bika_widgets/referencewidget.pt
Labels: Cleanup

#1542 Fix sporadical errors when contacts do not have a valid email address
  CHANGES.rst
  bika/lims/content/person.py
  bika/lims/upgrade/v01_03_003.py
Labels: Bug, P1: Urgent

#1530 Removed stale type registrations
  CHANGES.rst
  bika/lims/__init__.py
  bika/lims/browser/arimports.py
  bika/lims/browser/arimports.zcml
  bika/lims/browser/configure.zcml
  bika/lims/browser/templates/arimport_add.pt
  bika/lims/config.py
  bika/lims/content/arimport.py
  bika/lims/content/bikacache.py
  bika/lims/content/bikasetup.py
  bika/lims/content/client.py
  bika/lims/content/invoicebatch.py
  bika/lims/content/invoicefolder.py
  bika/lims/content/sample.py
  bika/lims/content/samplepartition.py
  bika/lims/content/samplesfolder.py
  bika/lims/interfaces/__init__.py
  bika/lims/monkey/contentmenu.py
  bika/lims/permissions.py
  bika/lims/permissions.zcml
  bika/lims/profiles/default/factorytool.xml
  bika/lims/profiles/default/propertiestool.xml
  bika/lims/profiles/default/rolemap.xml
  bika/lims/profiles/default/types.xml
  bika/lims/profiles/default/types/ARImport.xml
  bika/lims/profiles/default/types/BikaCache.xml
  bika/lims/profiles/default/types/Client.xml
  bika/lims/profiles/default/types/InvoiceBatch.xml
  bika/lims/profiles/default/types/InvoiceFolder.xml
  bika/lims/profiles/default/types/Sample.xml
  bika/lims/profiles/default/types/SamplePartition.xml
  bika/lims/profiles/default/types/SamplesFolder.xml
  bika/lims/profiles/default/workflows.xml
  bika/lims/profiles/default/workflows/bika_arimport_workflow/definition.xml
  bika/lims/profiles/default/workflows/bika_arimports_workflow/definition.xml
  bika/lims/setuphandlers.py
  bika/lims/skins/bika/cg-images/accept.png
  bika/lims/skins/bika/cg-images/exclamation.png
  bika/lims/skins/bika/cg-images/loading.gif
  bika/lims/skins/bika/cg-images/magnifier.png
  bika/lims/tests/doctests/API_analysis.rst
  bika/lims/tests/doctests/AnalysisTurnaroundTime.rst
  bika/lims/tests/doctests/WorksheetApplyTemplate.rst
  bika/lims/tests/files/BikaARImportTemplate.csv
  bika/lims/tests/test_ARImport.py
  bika/lims/upgrade/v01_03_003.py
Labels: Cleanup

#1543 Sort navigation child-nodes alphabetically
  CHANGES.rst
  bika/lims/browser/portlets/templates/plone.app.portlets.portlets.navigation_recurse.pt
Labels: P4: Nice To Have

#1546 Safe removal of ARImport folder (and keep the type)
  bika/lims/interfaces/__init__.py
  bika/lims/upgrade/v01_03_003.py
Labels: P0: Critical

#1544 Progress indicator for Batch listing
  CHANGES.rst
  bika/lims/browser/analysisrequest/analysisrequests.py
  bika/lims/browser/batchfolder.py
  bika/lims/catalog/__init__.py
  bika/lims/catalog/analysisrequest_catalog.py
  bika/lims/content/analysisrequest.py
  bika/lims/content/batch.py
  bika/lims/setuphandlers.py
  bika/lims/upgrade/v01_03_003.py
Labels: Addition, Enhancement

#1547 Added upgrade step to remove skin layers
  bika/lims/upgrade/v01_03_003.py
Labels: Cleanup

#1549 Added registry profile for jQuery UI settings
  CHANGES.rst
  bika/lims/profiles/default/registry.xml
  bika/lims/upgrade/v01_03_003.py
Labels: Addition

#1550 Fix Uncaught TypeError in combogrid
  CHANGES.rst
  bika/lims/browser/js/thirdparty/jquery/jquery.ui.combogrid-1.6.3.js
Labels: Bug

#1551 Removed dependency to plone.app.iterate
  CHANGES.rst
  bika/lims/profiles/default/metadata.xml
  bika/lims/upgrade/v01_03_003.py
Labels: Cleanup

#1552 Sample rejection during registration is not generating Rejection report/pdf
  CHANGES.rst
  bika/lims/api/mail.py
  bika/lims/browser/analysisrequest/reject_samples.py
  bika/lims/tests/doctests/API_mail.rst
  bika/lims/utils/analysisrequest.py
  bika/lims/workflow/analysisrequest/events.py
Labels: Bug

#1554 Add Form: Recalculate prices on copy
  bika/lims/browser/js/bika.lims.analysisrequest.add.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Bug

#1553 Rejection mail template
  CHANGES.rst
  bika/lims/api/mail.py
  bika/lims/browser/analysisrequest/reject.py
  bika/lims/browser/analysisrequest/templates/analysisrequest_retract_mail.pt
  bika/lims/content/bikasetup.py
  bika/lims/utils/analysisrequest.py
Labels: Enhancement
