Repository senaite/senaite.core, pull requests merged in 2020-10, with the labels that each got.

#1635 Sidebar toggle
  CHANGES.rst
  src/senaite/core/browser/portlets/templates/navigation.pt
  src/senaite/core/browser/static/bundles/main-0610f45.js
  src/senaite/core/browser/static/bundles/main-a32f075.js
  src/senaite/core/browser/static/bundles/main.css
  src/senaite/core/browser/static/resources.pt
  webpack/app/components/sidebar.js
  webpack/app/scss/sidebar.scss
  webpack/app/senaite.core.js
Labels: Enhancement

#1637 Fix "Page not Found" Error for migrated SENAITE Contents with File/Image Fields
  CHANGES.rst
  src/senaite/core/browser/globals/theme.py
Labels: Bug

#1638 Fix Published results tab is not displayed to Client contacts (ported from #1629)
  CHANGES.rst
  src/bika/lims/profiles/default/types/AnalysisRequest.xml
  src/senaite/core/upgrade/v02_00_000.py
Labels: Bug

#1643 Setup View Filter
  CHANGES.rst
  src/senaite/core/browser/controlpanel/templates/setupview.pt
  src/senaite/core/browser/static/js/coffee/senaite.core.setupview.coffee
  src/senaite/core/browser/static/js/senaite.core.setupview.js
Labels: Enhancement

#1645 Allow translation of path bar items
  CHANGES.rst
  src/senaite/core/browser/viewlets/path_bar.py
Labels: Bug

#1648 Fix Unicode Decode Error in Path Bar
  src/senaite/core/browser/viewlets/path_bar.py
Labels: Bug

#1650 Fix Error when invalidating a sample with contained retests
  CHANGES.rst
  src/bika/lims/utils/analysisrequest.py
Labels: Bug

#1649 Improved result handling of multi select/choices fields
  src/bika/lims/content/abstractanalysis.py
Labels: Enhancement

#1653 Maximum length of Choices subfield (interim) is set to 40
  CHANGES.rst
  src/bika/lims/browser/fields/interimfieldsfield.py
  src/senaite/core/skins/senaite_templates/senaite_widgets/recordswidget.pt
Labels: Bug

#1657 Allow to edit Profiles in Samples for pre verified/published states
  CHANGES.rst
  src/bika/lims/content/analysisrequest.py
  src/bika/lims/profiles/default/workflows/bika_ar_workflow/definition.xml
  src/senaite/core/tests/doctests/AnalysisProfile.rst
  src/senaite/core/upgrade/v02_00_000.py
Labels: Enhancement

#1659 Fix language in datepicker widgets
  CHANGES.rst
  src/senaite/core/browser/static/js/bika.lims.site.js
  src/senaite/core/browser/static/js/coffee/bika.lims.site.coffee
Labels: Bug

#1662 Custom view/edit forms for dexterity types
  CHANGES.rst
  src/senaite/core/browser/configure.zcml
  src/senaite/core/browser/dexterity/__init__.py
  src/senaite/core/browser/dexterity/configure.zcml
  src/senaite/core/browser/dexterity/templates/form.pt
  src/senaite/core/browser/dexterity/templates/item.pt
  src/senaite/core/browser/dexterity/templates/macros.pt
  src/senaite/core/browser/dexterity/templates/widget.pt
  src/senaite/core/browser/dexterity/views.py
  src/senaite/core/interfaces/__init__.py
  src/senaite/core/profiles/default/browserlayer.xml
  src/senaite/core/upgrade/v02_00_000.py
Labels: Enhancement

#1664 Display correct icons in listings
  CHANGES.rst
  src/senaite/core/browser/viewlets/listings.py
Labels: Bug

#1665 Display Auditlog listing icon
  CHANGES.rst
  src/bika/lims/browser/auditlog.py
  src/bika/lims/browser/templates/auditlog.pt
Labels: Cleanup, Enhancement

#1667 Fix date widget showing always 1899-12-31
  src/senaite/core/browser/static/js/bika.lims.site.js
  src/senaite/core/browser/static/js/coffee/bika.lims.site.coffee
Labels: Bug

#1666 Added adapter to extend listing_searchable_text index
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/bika/lims/catalog/indexers/__init__.py
  src/bika/lims/catalog/indexers/analysisrequest.py
  src/bika/lims/catalog/indexers/bikasetup.py
  src/bika/lims/interfaces/__init__.py
Labels: Enhancement

#1658 Fix for results managed as strings when importing from CSV files
  bika/lims/exportimport/instruments/resultsimport.py
Labels: Bug

#1669 Fix Generic Setup Content Importer
  CHANGES.rst
  src/senaite/core/exportimport/genericsetup/structure.py
Labels: Bug
