Repository senaite/senaite.core, pull requests merged in 2020-03, with the labels that each got.

#1556 Fix TypeError when retracting analysis with ExtendedField
  CHANGES.rst
  bika/lims/utils/analysis.py
Labels: Bug, P1: Urgent

#1558 Remove the cross-assignment of SampleType--SamplePoint
  bika/lims/browser/client/views/samplepoints.py
  bika/lims/content/samplepoint.py
  bika/lims/content/sampletype.py
  bika/lims/controlpanel/bika_samplepoints.py
  bika/lims/controlpanel/bika_sampletypes.py
  bika/lims/exportimport/setupdata/__init__.py
  bika/lims/utils/__init__.py
Labels: Cleanup

#1560 Fix missing Add Dynamic Analysis Specifications Button for Lab Managers
  bika/lims/controlpanel/dynamic_analysisspecs.py
Labels: Bug

#1563 Client contacts can create samples without contact
  CHANGES.rst
  bika/lims/browser/analysisrequest/add2.py
Labels: Bug

#1564 Pin CSSSelect to < 0.3.0
  setup.py
Labels: Bug, P0: Critical
