Repository senaite/senaite.core, pull requests merged in 2020-12, with the labels that each got.

#1690 Added ContentSectionViewletManager to allow dynamic addition of sections
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/tables.py
  src/bika/lims/browser/analysisrequest/templates/analysisrequest_view.pt
  src/bika/lims/browser/analysisrequest/view.py
  src/senaite/core/browser/viewlets/configure.zcml
  src/senaite/core/browser/viewlets/interfaces.py
  src/senaite/core/browser/viewlets/sampleanalyses.py
  src/senaite/core/browser/viewlets/templates/sampleanalyses.pt
  src/senaite/core/profiles/default/viewlets.xml
  src/senaite/core/upgrade/v02_00_000.py
Labels: Enhancement

#1680 Selected instrument is not assigned to analyses in Worksheet
  bika/lims/browser/js/bika.lims.worksheet.js
  bika/lims/browser/js/coffee/bika.lims.worksheet.coffee
  bika/lims/browser/worksheet/ajax.py
  bika/lims/content/worksheet.py
Labels: To port

#1702 Remove Analysis Specifications from AR Add Form
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
  src/bika/lims/browser/analysisrequest/templates/ar_add2.pt
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.add.js
  src/senaite/core/browser/static/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Cleanup

#1704 Cannot override behavior of LabContacts folder when using `before_render` and added `Roles` column
  CHANGES.rst
  bika/lims/controlpanel/bika_labcontacts.py
Labels: To port

#1705 Migrated instrument locations to Dexterity
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/bika/lims/controlpanel/bika_instrumentlocations.py
  src/bika/lims/controlpanel/configure.zcml
  src/bika/lims/profiles/default/factorytool.xml
  src/bika/lims/profiles/default/structure/bika_setup/.objects
  src/bika/lims/profiles/default/structure/bika_setup/.preserve
  src/bika/lims/profiles/default/structure/bika_setup/instrumentlocations/.properties
  src/bika/lims/profiles/default/types.xml
  src/bika/lims/profiles/default/types/InstrumentLocation.xml
  src/bika/lims/profiles/default/types/InstrumentLocations.xml
  src/bika/lims/profiles/default/workflows.xml
  src/senaite/core/browser/controlpanel/configure.zcml
  src/senaite/core/browser/controlpanel/instrumentlocations.py
  src/senaite/core/content/instrumentlocation.py
  src/senaite/core/content/instrumentlocations.py
  src/senaite/core/profiles/default/types.xml
  src/senaite/core/profiles/default/types/InstrumentLocation.xml
  src/senaite/core/profiles/default/types/InstrumentLocations.xml
  src/senaite/core/profiles/default/workflows.xml
  src/senaite/core/tests/doctests/BatchClientAssignment.rst
  src/senaite/core/upgrade/utils.py
  src/senaite/core/upgrade/v02_00_000.py
Labels: Version 2.0

#1708 Remove auto versioning for Analysis Services
  CHANGES.rst
  src/senaite/core/profiles/default/repositorytool.xml
  src/senaite/core/tests/doctests/API.rst
  src/senaite/core/tests/doctests/Versioning.rst
  src/senaite/core/upgrade/v02_00_000.py
Labels: Cleanup

#1713 JS/CSS resources optimized to increase loading performance
  CHANGES.rst
  src/senaite/core/browser/static/bundles/legacy.css
  src/senaite/core/browser/static/bundles/legacy.js
  src/senaite/core/browser/static/bundles/legacy.js.map
  src/senaite/core/browser/static/bundles/main-8724a1f.js
  src/senaite/core/browser/static/bundles/main-8caae31.js
  src/senaite/core/browser/static/bundles/thirdparty.css
  src/senaite/core/browser/static/bundles/thirdparty.js
  src/senaite/core/browser/static/bundles/thirdparty.js.map
  src/senaite/core/browser/static/js/bika.lims.loader.js
  src/senaite/core/browser/static/resources.pt
  webpack/app/components/sidebar.js
  webpack/app/components/site.js
  webpack/app/resources.pt
  webpack/package.json
  webpack/webpack.config.js
  webpack/yarn.lock
Labels: Cleanup

#1714 Removed add button in auditlog listing view
  CHANGES.rst
  src/bika/lims/browser/auditlog.py
Labels: Bug

#1716 Fix workflow state offset in toolbar when no dropdown is rendered
  CHANGES.rst
  src/senaite/core/browser/contentmenu/templates/contentmenu.pt
  src/senaite/core/browser/static/bundles/main-595991c.js
  src/senaite/core/browser/static/bundles/main-595991c.js.map
  src/senaite/core/browser/static/resources.pt
  webpack/app/scss/toolbar.scss
Labels: Bug
