Repository senaite/senaite.core, pull requests merged in 2020-11, with the labels that each got.

#1673 Fix Samples not sorted in natural order when Worksheet Template is used
  CHANGES.rst
  bika/lims/content/worksheet.py
  bika/lims/tests/doctests/WorksheetApplyTemplate.rst
Labels: Bug

#1674 Fix error in sample view when ccemails is none
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/__init__.py
Labels: Bug, To port

#1675 Fix error when setting WS template layout
  CHANGES.rst
  src/bika/lims/skins/bika/bika_widgets/worksheettemplatelayoutwidget.pt
Labels: Bug

#1676 New Field "Department ID" added to Departments
  CHANGES.rst
  src/bika/lims/catalog/indexers/bikasetup.py
  src/bika/lims/catalog/indexers/configure.zcml
  src/bika/lims/content/department.py
  src/bika/lims/controlpanel/bika_departments.py
  src/bika/lims/setuphandlers.py
  src/senaite/core/upgrade/v02_00_000.py
Labels: Addition

#1678 Improved Generic Setup Content Structure Export/Import
  CHANGES.rst
  src/senaite/core/exportimport/genericsetup/adapters.py
  src/senaite/core/exportimport/genericsetup/configure.zcml
  src/senaite/core/exportimport/genericsetup/structure.py
  src/senaite/core/p3compat.py
Labels: Enhancement

#1683 Fix Attribute Error when creating invoice PDF
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/invoice.py
  src/bika/lims/browser/analysisrequest/templates/invoice_content.pt
Labels: Bug, To port

#1684 Show only active dynamic analysisspecs in reference widget
  CHANGES.rst
  src/bika/lims/content/analysisspec.py
Labels: Bug, To port

#1685 Remove Supply Orders
  CHANGES.rst
  src/bika/lims/__init__.py
  src/bika/lims/browser/client/__init__.py
  src/bika/lims/browser/client/configure.zcml
  src/bika/lims/browser/client/views/orders.py
  src/bika/lims/browser/configure.zcml
  src/bika/lims/browser/invoice.py
  src/bika/lims/browser/supplyorder.py
  src/bika/lims/browser/supplyorder.zcml
  src/bika/lims/browser/supplyorderfolder.py
  src/bika/lims/browser/supplyorderfolder.zcml
  src/bika/lims/browser/templates/supplyorder_content.pt
  src/bika/lims/browser/templates/supplyorder_edit.pt
  src/bika/lims/browser/templates/supplyorder_print.pt
  src/bika/lims/browser/templates/supplyorder_view.pt
  src/bika/lims/content/invoice.py
  src/bika/lims/permissions.py
  src/bika/lims/permissions.zcml
  src/bika/lims/profiles/default/factorytool.xml
  src/bika/lims/profiles/default/propertiestool.xml
  src/bika/lims/profiles/default/rolemap.xml
  src/bika/lims/profiles/default/structure/.objects
  src/bika/lims/profiles/default/structure/supplyorders/.objects
  src/bika/lims/profiles/default/structure/supplyorders/.properties
  src/bika/lims/profiles/default/types.xml
  src/bika/lims/profiles/default/types/Client.xml
  src/bika/lims/profiles/default/types/SupplyOrder.xml
  src/bika/lims/profiles/default/types/SupplyOrderFolder.xml
  src/bika/lims/profiles/default/workflows.xml
  src/bika/lims/profiles/default/workflows/senaite_supplyorder_workflow/definition.xml
  src/bika/lims/setuphandlers.py
  src/bika/lims/utils/__init__.py
  src/senaite/core/browser/static/bundles/main-467d6c2.js
  src/senaite/core/browser/static/js/bika.lims.supplyorder.js
  src/senaite/core/browser/static/resources.pt
  src/senaite/core/upgrade/v02_00_000.py
  webpack/app/resources.pt
Labels: Cleanup

#1682 Fix `LocationError` when editing a entry in the configuration registry
  CHANGES.rst
  src/senaite/core/browser/dexterity/templates/macros.pt
Labels: Bug

#1688 Handle UnicodeDecodeError when generating department IDs
  src/senaite/core/upgrade/v02_00_000.py
Labels: Bug

#1691 Fix immediate logout when timeout exceeds 32 bit integer value
  CHANGES.rst
  webpack/app/senaite.core.js
Labels: Bug, To port

#1695 Fix form submission for required multi-reference fields
  CHANGES.rst
  src/bika/lims/browser/header_table.py
  src/senaite/core/skins/senaite_templates/senaite_widgets/referencewidget.pt
Labels: Bug

#1697 Do a deepcopy of interims instead of a shallow copy
  src/bika/lims/browser/analyses/view.py
Labels: To port
