Repository senaite/senaite.core, pull requests merged in 2020-07, with the labels that each got.

#1604 Analyses from Partitions do not show up when using Worksheet Template
  CHANGES.rst
  bika/lims/utils/analysisrequest.py
Labels: Bug

#1605 Retests are not displayed in Worksheet's print view
  CHANGES.rst
  bika/lims/browser/worksheet/templates/print/ar_by_column.css
  bika/lims/browser/worksheet/templates/print/ar_by_column.pt
  bika/lims/browser/worksheet/templates/print/ar_by_row.css
  bika/lims/browser/worksheet/templates/print/ar_by_row.pt
  bika/lims/browser/worksheet/views/printview.py
Labels: Bug

#1606 Fix Traceback on Dynamic Analysis Specs Edit
  CHANGES.rst
  bika/lims/content/dynamic_analysisspec.py
  bika/lims/controlpanel/dynamic_analysisspecs.py
Labels: Bug, P3: Important

#1607 Allow to set instruments from method edit view
  CHANGES.rst
  bika/lims/browser/js/bika.lims.method.js
  bika/lims/browser/methodfolder.py
  bika/lims/content/method.py
  bika/lims/workflow/instrument/__init__.py
  bika/lims/workflow/instrument/events.py
Labels: Enhancement, P2: Very Important

#1609 Support result options entry for interim values
  CHANGES.rst
  bika/lims/browser/analyses/view.py
  bika/lims/browser/fields/interimfieldsfield.py
  bika/lims/validators.py
Labels: Enhancement
