Repository senaite/senaite.core, pull requests merged in 2020-09, with the labels that each got.

#1613 Compatibility with Plone 5.2.2
  CHANGES.rst
  buildout.cfg
  src/bika/lims/browser/analysisrequest/templates/analysisrequests.pt
  src/bika/lims/browser/analysisrequest/templates/ar_add2.pt
  src/bika/lims/browser/templates/header_table.pt
  src/senaite/core/browser/bootstrap/bootstrap.py
  src/senaite/core/browser/globals/configure.zcml
  src/senaite/core/browser/globals/interfaces.py
  src/senaite/core/browser/globals/view.py
  src/senaite/core/browser/main_template/templates/ajax_main_template.pt
  src/senaite/core/browser/main_template/templates/main_template.pt
  src/senaite/core/skins/senaite_templates/edit_macros.pt
Labels: Bug, Version 2.0

#1616 Fix writing methods on read when reindexing services
  CHANGES.rst
  src/bika/lims/content/analysisservice.py
  src/senaite/core/upgrade/configure.zcml
  src/senaite/core/upgrade/v02_00_000.py
Labels: Bug, P1: Urgent

#1617 Backported #1616: Fix writing methods on read when reindexing services
  CHANGES.rst
  bika/lims/content/analysisservice.py
  bika/lims/upgrade/configure.zcml
  bika/lims/upgrade/v01_03_005.py
  setup.py
Labels: Bug

#1621 Fix instrument import for analyses with result options
  CHANGES.rst
  src/senaite/core/exportimport/instruments/resultsimport.py
Labels: Bug

#1625 Fix assignment of analyses via worksheet template when Worksheet is full
  CHANGES.rst
  bika/lims/content/worksheet.py
  bika/lims/tests/doctests/WorksheetApplyTemplate.rst
Labels: Bug
