Repository senaite/senaite.core, pull requests merged in 2020-06, with the labels that each got.

#1584 Date (yymmdd) support in IDs generation
  CHANGES.rst
  bika/lims/content/bikasetup.py
  bika/lims/idserver.py
Labels: Addition

#1585 Fix wrong label and description for `ShowPartitions` setting from setup
  CHANGES.rst
  bika/lims/content/bikasetup.py
Labels: Bug

#1586 Allow to configure IDServer variables with an adapter
  CHANGES.rst
  bika/lims/idserver.py
  bika/lims/interfaces/__init__.py
Labels: Addition

#1587 Removal of "manage_results" view from Sample
  src/bika/lims/barcode.py
  src/bika/lims/browser/analysisrequest/__init__.py
  src/bika/lims/browser/analysisrequest/configure.zcml
  src/bika/lims/browser/analysisrequest/manage_results.py
  src/bika/lims/browser/analysisrequest/templates/analysisrequest_manage_results.pt
  src/bika/lims/browser/analysisrequest/view.py
  src/bika/lims/profiles/default/types/AnalysisRequest.xml
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.js
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.manageresults.js
  src/senaite/core/browser/static/js/bika.lims.loader.js
  src/senaite/core/browser/static/js/coffee/bika.lims.analysisrequest.coffee
  src/senaite/core/tests/test_barcode_entry.py
Labels: Bug, Cleanup, Version 2.0

#1588 Dynamic Analysis Specs: Lookup dynamic specs only when specification is set and hide spec compliance viewlets
  CHANGES.rst
  bika/lims/browser/viewlets/analysisrequest.py
  bika/lims/browser/viewlets/templates/resultsranges_out_of_date_viewlet.pt
  bika/lims/browser/viewlets/templates/specification_non_compliant_viewlet.pt
  bika/lims/content/abstractroutineanalysis.py
  bika/lims/content/analysisrequest.py
  bika/lims/tests/doctests/DynamicAnalysisSpec.rst
  bika/lims/upgrade/v01_03_004.py
Labels: Enhancement, Performance

#1591 User might accidentally assign a contact from another client while creating a Sample
  CHANGES.rst
  bika/lims/browser/analysisrequest/add2.py
Labels: Bug

#1592 Publisher user cannot publish samples
  CHANGES.rst
  bika/lims/profiles/default/rolemap.xml
  bika/lims/profiles/default/workflows/bika_ar_workflow/definition.xml
  bika/lims/profiles/default/workflows/senaite_clientcontact_workflow/definition.xml
  bika/lims/profiles/default/workflows/senaite_labcontact_workflow/definition.xml
  bika/lims/tests/doctests/Permissions.rst
  bika/lims/upgrade/v01_03_004.py
Labels: Bug

#1593 Out-of-range alert icon is shown to users w/o "View Results" privileges
  CHANGES.rst
  bika/lims/browser/analyses/view.py
Labels: Bug

#1595 Fix Wrong url in client's analyses profiles listing
  CHANGES.rst
  bika/lims/browser/client/views/analysisprofiles.py
Labels: Bug

#1596 Allow to hide actions menu by using new marker interface IHideActionsMenu
  CHANGES.rst
  bika/lims/browser/contentmenu.py
  bika/lims/content/reportfolder.py
  bika/lims/interfaces/__init__.py
Labels: Enhancement

#1594 System does not validate values from Results Options to be different
  CHANGES.rst
  bika/lims/content/abstractbaseanalysis.py
  bika/lims/validators.py
Labels: Bug

#1598 Add "modified" index in Samples (AnalysisRequest) catalog
  CHANGES.rst
  bika/lims/catalog/analysisrequest_catalog.py
  bika/lims/upgrade/v01_03_004.py
Labels: Enhancement

#1600 Fix upgrade step for 1.3.4
  bika/lims/upgrade/v01_03_004.py
Labels: Bug

#1601 Fix wrong url in client's sample templates listing
  CHANGES.rst
  bika/lims/browser/client/views/artemplates.py
Labels: Bug

#1602 Report "Analysis per Service" is always creating the same PDF file
  CHANGES.rst
  bika/lims/browser/reports/selection_macros/__init__.py
Labels: Bug
