Repository senaite/senaite.core, pull requests merged in 2020-01, with the labels that each got.

#1501 Fix Attribute Error in Reference Sample Popup
  CHANGES.rst
  bika/lims/api/__init__.py
  bika/lims/content/referenceanalysis.py
Labels: Bug, P2: Very Important

#1503 Avoid duplicate CSS IDs in multi-column Add form
  CHANGES.rst
  bika/lims/browser/analysisrequest/templates/ar_add2.pt
Labels: Bug, P3: Important

#1502 Improved DateTime Widget
  CHANGES.rst
  bika/lims/browser/js/thirdparty/jquery/jquery-timepicker-i18n.js
  bika/lims/browser/js/thirdparty/jquery/jquery-timepicker.js
  bika/lims/profiles/default/jsregistry.xml
  bika/lims/skins/bika/bika_widgets/datetimewidget.css
  bika/lims/skins/bika/bika_widgets/datetimewidget.js
  bika/lims/skins/bika/bika_widgets/datetimewidget.pt
  bika/lims/upgrade/v01_03_003.py
Labels: Cleanup, Enhancement

#1495 Better handling of RemarksField and friendly display
  CHANGES.rst
  bika/lims/browser/analysisrequest/templates/analysisrequest_manage_results.pt
  bika/lims/browser/analysisrequest/templates/analysisrequest_view.pt
  bika/lims/browser/fields/remarksfield.py
  bika/lims/browser/js/bika.lims.worksheet.js
  bika/lims/browser/js/coffee/bika.lims.worksheet.coffee
  bika/lims/browser/js/coffee/bika_widgets/remarkswidget.coffee
  bika/lims/browser/worksheet/templates/results.pt
  bika/lims/content/analysisprofile.py
  bika/lims/content/analysisrequest.py
  bika/lims/content/artemplate.py
  bika/lims/content/batch.py
  bika/lims/content/instrumentcertification.py
  bika/lims/content/pricelist.py
  bika/lims/content/referencesample.py
  bika/lims/content/sample.py
  bika/lims/content/supplier.py
  bika/lims/content/supplyorder.py
  bika/lims/content/worksheet.py
  bika/lims/events/__init__.py
  bika/lims/events/remarks.py
  bika/lims/skins/bika/bika_widgets/remarkswidget.css
  bika/lims/skins/bika/bika_widgets/remarkswidget.js
  bika/lims/skins/bika/bika_widgets/remarkswidget.pt
  bika/lims/subscribers/configure.zcml
  bika/lims/subscribers/remarks.py
  setup.py
Labels: Enhancement

#1505 Manage Analyses Form re-applies partitioned Analyses back to the Root Sample
  CHANGES.rst
  bika/lims/browser/analyses/view.py
  bika/lims/browser/analysisrequest/manage_analyses.py
  bika/lims/browser/fields/aranalysesfield.py
  bika/lims/monkey/zcatalog.py
  bika/lims/tests/doctests/ARAnalysesField.rst
  bika/lims/tests/doctests/ARAnalysesFieldWithPartitions.rst
  bika/lims/upgrade/v01_03_003.py
Labels: Bug, P0: Critical

#1498 Move all viewlets from senaite.lims to core
  CHANGES.rst
  bika/lims/browser/viewlets/__init__.py
  bika/lims/browser/viewlets/colophon.py
  bika/lims/browser/viewlets/configure.zcml
  bika/lims/browser/viewlets/content_views.py
  bika/lims/browser/viewlets/document_actions.py
  bika/lims/browser/viewlets/footer.py
  bika/lims/browser/viewlets/logo.py
  bika/lims/browser/viewlets/path_bar.py
  bika/lims/browser/viewlets/personal_bar.py
  bika/lims/browser/viewlets/sections.py
  bika/lims/browser/viewlets/site_actions.py
  bika/lims/browser/viewlets/templates/attachments.pt
  bika/lims/browser/viewlets/templates/colophon.pt
  bika/lims/browser/viewlets/templates/document_actions.pt
  bika/lims/browser/viewlets/templates/footer.pt
  bika/lims/browser/viewlets/templates/instrument_qc_failures_viewlet.pt
  bika/lims/browser/viewlets/templates/path_bar.pt
  bika/lims/browser/viewlets/templates/plone.app.i18n.locales.browser.languageselector.pt
  bika/lims/browser/viewlets/templates/plone.app.layout.viewlets.colophon.pt
  bika/lims/browser/viewlets/templates/plone.app.layout.viewlets.contentviews.pt
  bika/lims/browser/viewlets/templates/plone.app.layout.viewlets.documentactions.pt
  bika/lims/browser/viewlets/templates/plone.app.layout.viewlets.footer.pt
  bika/lims/browser/viewlets/templates/plone.app.layout.viewlets.logo.pt
  bika/lims/browser/viewlets/templates/plone.app.layout.viewlets.path_bar.pt
  bika/lims/browser/viewlets/templates/plone.app.layout.viewlets.personal_bar.pt
  bika/lims/browser/viewlets/templates/plone.app.layout.viewlets.sections.pt
  bika/lims/browser/viewlets/templates/plone.app.layout.viewlets.site_actions.pt
  bika/lims/browser/viewlets/templates/sections_dropdown.pt
  bika/lims/browser/viewlets/templates/worksheet_attachments.pt
  bika/lims/profiles/default/viewlets.xml
  bika/lims/upgrade/v01_03_003.py
Labels: Cleanup

#1499 Move navigation portlet into core
  CHANGES.rst
  bika/lims/browser/configure.zcml
  bika/lims/browser/portlets/__init__.py
  bika/lims/browser/portlets/configure.zcml
  bika/lims/browser/portlets/navigation.py
  bika/lims/browser/portlets/templates/plone.app.portlets.portlets.navigation.pt
  bika/lims/browser/portlets/templates/plone.app.portlets.portlets.navigation_recurse.pt
Labels: Cleanup

#1507 Support for semi-colon character separator in CCEmails field
  CHANGES.rst
  bika/lims/browser/analysisrequest/add2.py
  bika/lims/browser/fields/__init__.py
  bika/lims/browser/fields/emailsfield.py
  bika/lims/browser/publish/emailview.py
  bika/lims/browser/publish/reports_listing.py
  bika/lims/content/analysisrequest.py
  bika/lims/content/client.py
Labels: Addition

#1509 Services don't get selected when a profile/template is selected in Add Sample
  bika/lims/browser/analysisrequest/templates/ar_add2.pt
  bika/lims/browser/js/bika.lims.analysisrequest.add.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Bug, P0: Critical

#1508 Do not try to render InstrumentQCFailuresViewlet to non-lab personnel
  CHANGES.rst
  bika/lims/browser/viewlets/configure.zcml
Labels: Enhancement

#1511 Links to partitions for Internal Use are displayed in partitions viewlet
  CHANGES.rst
  bika/lims/browser/analyses/view.py
  bika/lims/browser/viewlets/analysisrequest.py
Labels: Bug, P2: Very Important

#1510 Error when viewing a Sample w/o Batch as client contact
  CHANGES.rst
  bika/lims/adapters/widgetvisibility.py
Labels: Bug, P0: Critical

#1512 QC Analyses listing appears empty in Sample view
  CHANGES.rst
  bika/lims/browser/analyses/qc.py
  bika/lims/content/analysisrequest.py
Labels: Bug, Cleanup, P1: Urgent

#1492 Dynamic Analysis Specifications
  bika/lims/adapters/configure.zcml
  bika/lims/adapters/dynamicresultsrange.py
  bika/lims/browser/configure.zcml
  bika/lims/browser/dynamic_analysisspec.py
  bika/lims/browser/dynamic_analysisspec.zcml
  bika/lims/browser/images/dynamic_analysisspec.png
  bika/lims/browser/images/dynamic_analysisspec_big.png
  bika/lims/browser/viewlets/configure.zcml
  bika/lims/browser/viewlets/dynamic_specs.py
  bika/lims/browser/viewlets/templates/dynamic_specs_viewlet.pt
  bika/lims/browser/widgets/analysisspecificationwidget.py
  bika/lims/content/abstractroutineanalysis.py
  bika/lims/content/analysisspec.py
  bika/lims/content/dynamic_analysisspec.py
  bika/lims/controlpanel/bika_analysisspecs.py
  bika/lims/controlpanel/configure.zcml
  bika/lims/controlpanel/dynamic_analysisspecs.py
  bika/lims/interfaces/__init__.py
  bika/lims/profiles/default/controlpanel.xml
  bika/lims/profiles/default/types.xml
  bika/lims/profiles/default/types/DynamicAnalysisSpec.xml
  bika/lims/profiles/default/types/DynamicAnalysisSpecs.xml
  bika/lims/profiles/default/workflows.xml
  bika/lims/setuphandlers.py
  bika/lims/tests/doctests/DynamicAnalysisSpec.rst
  bika/lims/upgrade/v01_03_003.py
  bika/lims/validators.py
Labels: Addition, P3: Important, Version 1.3
