Repository senaite/senaite.core, pull requests merged in 2021-05, with the labels that each got.

#1797 Fix Auto Import Log View and ID generation
  CHANGES.rst
  src/bika/lims/browser/resultsimport/autoimportlogs.py
  src/bika/lims/content/autoimportlog.py
  src/bika/lims/interfaces/__init__.py
Labels: Bug, Cleanup, To port

#1802 Adapter hook for confirmation when creating a Sample
  CHANGES.rst
  bika/lims/browser/analysisrequest/add2.py
  bika/lims/browser/analysisrequest/templates/ar_add2.pt
  bika/lims/browser/js/bika.lims.analysisrequest.add.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee
  bika/lims/interfaces/__init__.py
Labels: Version 1.3

#1801 Updated openpyxl to latest Python 2.x compatible version
  CHANGES.rst
  setup.py
  src/bika/lims/content/dynamic_analysisspec.py
  src/senaite/core/exportimport/load_setup_data.py
  src/senaite/core/exportimport/setupdata/__init__.py
  src/senaite/core/tests/doctests/DynamicAnalysisSpec.rst
Labels: P1: Urgent

#1810 Revert changes of PR #1767
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
Labels: Bug
