Repository senaite/senaite.core, pull requests merged in 2021-11, with the labels that each got.

#1866 Fix error when invalidating samples with copies of analyses (1.3.x)
  CHANGES.rst
  bika/lims/tests/doctests/WorkflowAnalysisRequestInvalidate.rst
  bika/lims/utils/analysisrequest.py
Labels: Bug, P0: Critical, Version 1.3

#1865 Fix indexing of temporary objects resulting in orphan entries in catalog
  CHANGES.rst
  src/senaite/core/configure.zcml
  src/senaite/core/patches/__init__.py
  src/senaite/core/patches/archetypes.py
  src/senaite/core/patches/configure.zcml
Labels: Bug, P2: Very Important, To port

#1867 Fix error when invalidating sample with copies of analyses
  CHANGES.rst
  src/bika/lims/utils/analysisrequest.py
  src/senaite/core/tests/doctests/WorkflowAnalysisRequestInvalidate.rst
Labels: Bug, P0: Critical, Version 2.0

#1864 Added UID reference field/widget for Dexterity Contents
  CHANGES.rst
  src/senaite/core/browser/static/bundles/main.js
  src/senaite/core/browser/static/bundles/main.js.map
  src/senaite/core/interfaces/__init__.py
  src/senaite/core/schema/README.rst
  src/senaite/core/schema/__init__.py
  src/senaite/core/schema/configure.zcml
  src/senaite/core/schema/fields.py
  src/senaite/core/schema/interfaces.py
  src/senaite/core/schema/uidreferencefield.py
  src/senaite/core/schema/uidreferencefield.txt
  src/senaite/core/tests/test_schema_fields.py
  src/senaite/core/z3cform/configure.zcml
  src/senaite/core/z3cform/datamanager.py
  src/senaite/core/z3cform/error.py
  src/senaite/core/z3cform/interfaces.py
  src/senaite/core/z3cform/widgets/configure.zcml
  src/senaite/core/z3cform/widgets/uidreference.py
  src/senaite/core/z3cform/widgets/uidreference.zcml
  src/senaite/core/z3cform/widgets/uidreference_display.pt
  src/senaite/core/z3cform/widgets/uidreference_hidden.pt
  src/senaite/core/z3cform/widgets/uidreference_input.pt
  webpack/app/senaite.core.js
  webpack/app/widgets/uidreferencewidget/api.js
  webpack/app/widgets/uidreferencewidget/components/ReferenceField.js
  webpack/app/widgets/uidreferencewidget/components/ReferenceResults.js
  webpack/app/widgets/uidreferencewidget/components/References.js
  webpack/app/widgets/uidreferencewidget/widget.js
Labels: Addition

#1868 Fix indexing of temporary objects resulting in orphan entries in catalog (port #1865)
  CHANGES.rst
  bika/lims/monkey/__init__.py
  bika/lims/monkey/archetypes.py
  bika/lims/monkey/configure.zcml
Labels: Performance

#1873 Fix issues with new UID reference field for dexterity types
  src/senaite/core/schema/uidreferencefield.py
  src/senaite/core/z3cform/widgets/uidreference.py
Labels: Bug

#1874 Support for `%(context_uid)s` wildcard in calculation formulas
  CHANGES.rst
  src/bika/lims/content/abstractanalysis.py
Labels: Addition

#1876 Hide contents listing for dexterity containers
  CHANGES.rst
  src/senaite/core/browser/dexterity/configure.zcml
  src/senaite/core/browser/dexterity/templates/container.pt
Labels: Addition, Enhancement

#1877 Fix missing catalog mappings after migration
  src/bika/lims/setuphandlers.py
  src/senaite/core/upgrade/v02_00_001.py
Labels: Bug

#1878 Fix two dimension results parser for Analyses containing a dash in the name
  CHANGES.rst
  src/senaite/core/exportimport/instruments/generic/two_dimension.py
Labels: Bug

#1882 Fix catalog query in analysis category modified handler
  CHANGES.rst
  src/bika/lims/subscribers/objectmodified.py
Labels: Bug

#1883 Fix possible XSS in remarks field
  CHANGES.rst
  src/bika/lims/browser/fields/remarksfield.py
Labels: Bug

#1885 Fix APIError when a retest analysis source is removed
  CHANGES.rst
  bika/lims/browser/fields/aranalysesfield.py
  bika/lims/content/abstractanalysis.py
Labels: Bug, Version 1.3

#1886 Use the current timestamp instead of the client name for report archive download
  CHANGES.rst
  src/bika/lims/browser/workflow/client.py
Labels: Enhancement
