Repository senaite/senaite.core, pull requests merged in 2021-08, with the labels that each got.

#1831 Added adapter for custom validation of records in Sample Add form
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
  src/bika/lims/interfaces/__init__.py
Labels: Addition

#1833 Added an 'extra_inline_buttons' metal slot on edit macro
  CHANGES.rst
  src/senaite/core/skins/senaite_templates/edit_macros.pt
Labels: Addition

#1834 Fix `SamplePoint` content type does not implement `ISamplePoint`
  CHANGES.rst
  src/bika/lims/content/samplepoint.py
Labels: Bug

#1839 Allow sample partitions in submitted states
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/browser/fields/aranalysesfield.py
  src/bika/lims/browser/partition_magic.py
  src/bika/lims/browser/templates/partition_magic.pt
  src/bika/lims/utils/analysisrequest.py
  src/bika/lims/workflow/analysisrequest/guards.py
  src/senaite/core/profiles/default/workflows/senaite_sample_workflow/definition.xml
  src/senaite/core/upgrade/v02_00_001.py
Labels: Enhancement
