Repository senaite/senaite.core, pull requests merged in 2021-06, with the labels that each got.

#1811 Datagrid field and widget for Dexterity types
  CHANGES.rst
  setup.py
  src/senaite/core/interfaces/datamanager.py
  src/senaite/core/schema/fields.py
  src/senaite/core/schema/interfaces.py
  src/senaite/core/z3cform/configure.zcml
  src/senaite/core/z3cform/interfaces.py
  src/senaite/core/z3cform/static/datagrid.css
  src/senaite/core/z3cform/static/datagrid.js
  src/senaite/core/z3cform/widgets/configure.zcml
  src/senaite/core/z3cform/widgets/datagrid.py
  src/senaite/core/z3cform/widgets/datagrid.zcml
  src/senaite/core/z3cform/widgets/datagrid_display.pt
  src/senaite/core/z3cform/widgets/datagrid_input.pt
  src/senaite/core/z3cform/widgets/datagridrow_display.pt
  src/senaite/core/z3cform/widgets/datagridrow_input.pt
Labels: Addition

#1812 Support html messages on Add sample custom confirmation dialog
  CHANGES.rst
  bika/lims/browser/analysisrequest/templates/ar_add2.pt
Labels: To port, Version 1.3

#1813 Fix barcode is not rendered when stickers preview is called directly
  CHANGES.rst
  bika/lims/browser/templates/stickers_preview.pt
Labels: Bug, Version 1.3

#1814 Fix inconsistent behavior of Add sample form confirmation actions
  CHANGES.rst
  bika/lims/browser/js/bika.lims.analysisrequest.add.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Bug, To port, Version 1.3

#1815 Hide unit display after fields in manage analyses listing
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/manage_analyses.py
Labels: Bug

#1816 Fix duplicated rejection reasons in rejection viewlet (sample view)
  CHANGES.rst
  bika/lims/content/analysisrequest.py
Labels: Bug, Version 1.3

#1817 Fix duplicated rejection reasons in rejection viewlet (sample view) (2.x)
  CHANGES.rst
  src/bika/lims/content/analysisrequest.py
Labels: Bug, Version 2.0

#1819 Fix rejection report is attached as a ".bin" file in notification email (2.x)
  CHANGES.rst
  src/bika/lims/api/mail.py
  src/bika/lims/utils/analysisrequest.py
Labels: Bug, Version 2.0

#1818 Fix rejection report is attached as a ".bin" file in notification email
  CHANGES.rst
  bika/lims/api/mail.py
  bika/lims/utils/analysisrequest.py
Labels: Bug, Version 1.3

#1820 Fix dynamic analysis specification listing error for empty excel columns
  CHANGES.rst
  src/bika/lims/browser/dynamic_analysisspec.py
Labels: Bug
