Repository senaite/senaite.core, pull requests merged in 2021-07, with the labels that each got.

#1821 API support for supermodel objects
  .travis.yml
  CHANGES.rst
  README.rst
  src/bika/lims/api/__init__.py
  src/senaite/core/tests/doctests/API.rst
  src/senaite/core/tests/layers.py
Labels: Enhancement, To port

#1826 Fix TypeError when creating Dynamic Analysis Specifications
  CHANGES.rst
  src/bika/lims/content/dynamic_analysisspec.py
Labels: Bug, Version 2.0

#1825 Fix dynamic analysis specification listing error for empty excel columns (1.3.x)
  CHANGES.rst
  bika/lims/browser/dynamic_analysisspec.py
  bika/lims/content/dynamic_analysisspec.py
Labels: Bug, Version 1.3

#1824 Support html messages on Add sample custom confirmation dialog (2.x)
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/templates/ar_add2.pt
Labels: Enhancement, Version 2.0

#1823 Fix inconsistent behavior of Add sample form confirmation actions (2.x)
  CHANGES.rst
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.add.js
  src/senaite/core/browser/static/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Bug, Version 2.0

#1827 Fix categories don't show up automatically on Analysis Service creation
  CHANGES.rst
  bika/lims/content/abstractbaseanalysis.py
Labels: Bug, Version 1.3

#1828 Fix categories don't show up automatically on Analysis Service creation (2.x)
  CHANGES.rst
  src/bika/lims/content/abstractbaseanalysis.py
Labels: Bug, Version 2.0

#1829 Fix API create for Dexterity types (1.3.x)
  CHANGES.rst
  bika/lims/api/__init__.py
Labels: Bug, Version 1.3

#1830 Allow to override datepicker's dateformat via locales
  CHANGES.rst
  buildout.cfg
  src/bika/lims/browser/__init__.py
  src/senaite/core/skins/senaite_templates/senaite_widgets/datetimewidget.js
Labels: Enhancement
