Repository senaite/senaite.core, pull requests merged in 2021-02, with the labels that each got.

#1767 Disallow results entry when sample modification is not allowed
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
Labels: Security

#1770 Fix `TypeError` exception when no interims are set in calculation
  src/bika/lims/validators.py
Labels: Bug

#1772 Sample dispatch workflow
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/bika/lims/api/snapshot.py
  src/bika/lims/permissions.py
  src/bika/lims/permissions.zcml
  src/bika/lims/profiles/default/rolemap.xml
  src/bika/lims/workflow/__init__.py
  src/bika/lims/workflow/analysisrequest/events.py
  src/bika/lims/workflow/analysisrequest/guards.py
  src/senaite/core/adapters/configure.zcml
  src/senaite/core/adapters/sample.py
  src/senaite/core/browser/samples/configure.zcml
  src/senaite/core/browser/samples/dispatch_samples.py
  src/senaite/core/browser/samples/templates/dispatch_samples.pt
  src/senaite/core/browser/samples/view.py
  src/senaite/core/browser/viewlets/configure.zcml
  src/senaite/core/browser/viewlets/sample_dispatched.py
  src/senaite/core/browser/viewlets/templates/sample_dispatched_viewlet.pt
  src/senaite/core/profiles/default/workflows/senaite_sample_workflow/definition.xml
  src/senaite/core/tests/doctests/API.rst
  src/senaite/core/tests/doctests/API_snapshot.rst
  src/senaite/core/tests/doctests/WorkflowSampleDispatch.rst
Labels: Addition, P1: Urgent

#1773 Integrated upgrade step notification events
  CHANGES.rst
  src/senaite/core/events/__init__.py
  src/senaite/core/events/upgrade.py
  src/senaite/core/upgrade/__init__.py
Labels: Enhancement

#1774 Fix Lab clerk can edit items from setup folder
  CHANGES.rst
  bika/lims/browser/controlpanel.py
  bika/lims/browser/templates/setupview.pt
  bika/lims/profiles/default/rolemap.xml
  bika/lims/profiles/default/workflows/senaite_setup_workflow/definition.xml
  bika/lims/tests/doctests/API.rst
  bika/lims/tests/doctests/Permissions.rst
  bika/lims/upgrade/v01_03_005.py
Labels: To port

#1775 Sample add form tal:expressions refactored
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/templates/ar_add2.pt
Labels: Enhancement

#1776 Move time calculation into cache key function
  CHANGES.rst
  src/senaite/core/browser/globals/theme.py
Labels: Bug

#1777 Fix APIError when a retest analysis source was removed from a sample
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/manage_analyses.py
  src/bika/lims/browser/fields/aranalysesfield.py
  src/bika/lims/content/abstractanalysis.py
Labels: Bug

#1778 Added Datamanager Adapters for Analysis and Sample
  CHANGES.rst
  src/senaite/core/configure.zcml
  src/senaite/core/datamanagers/__init__.py
  src/senaite/core/datamanagers/analysis.py
  src/senaite/core/datamanagers/configure.zcml
  src/senaite/core/datamanagers/sample.py
  src/senaite/core/interfaces/__init__.py
  src/senaite/core/interfaces/datamanager.py
  src/senaite/core/tests/doctests/DataManagerAnalysis.rst
  src/senaite/core/tests/doctests/DataManagerSample.rst
Labels: Addition
