Repository senaite/senaite.core, pull requests merged in 2021-12, with the labels that each got.

#1893 Removed unused field PasswordLifeTime
  CHANGES.rst
  src/bika/lims/content/bikasetup.py
Labels: Cleanup

#1895 Disable native form validation in header table
  CHANGES.rst
  src/bika/lims/browser/templates/header_table.pt
Labels: Enhancement

#1896 Custom date and time widget
  CHANGES.rst
  src/bika/lims/browser/__init__.py
  src/bika/lims/content/instrumentcertification.py
  src/senaite/core/browser/static/bundles/main.css
  src/senaite/core/browser/static/bundles/main.css.map
  src/senaite/core/browser/widgets/datetimewidget.py
  src/senaite/core/skins/senaite_templates/senaite_widgets/datetimewidget.js
  src/senaite/core/skins/senaite_templates/senaite_widgets/datetimewidget.pt
  webpack/app/scss/forms.scss
Labels: Enhancement

#1897 Support date and number fields copy in sample add form
  CHANGES.rst
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.add.js
  src/senaite/core/browser/static/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Enhancement

#1901 Improved style for datetimewidget w/o hard coded width
  src/senaite/core/browser/static/bundles/main.css
  src/senaite/core/browser/static/bundles/main.css.map
  src/senaite/core/skins/senaite_templates/senaite_widgets/datetimewidget.pt
  webpack/app/scss/forms.scss
Labels: Bug

#1900 Fix snapshot listing fails on orphan catalog entries
  CHANGES.rst
  src/bika/lims/api/snapshot.py
Labels: Bug, Enhancement

#1902 Ensure `get_tool` returns a tool when a name is set as the default param
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/senaite/core/tests/doctests/API.rst
Labels: Bug
