Repository senaite/senaite.core, pull requests merged in 2021-01, with the labels that each got.

#1720 Fix UnicodeDecodeError for Instrument Import Log View
  CHANGES.rst
  src/bika/lims/browser/instrument.py
Labels: Bug

#1722 Fix UnicodeDecodeError in Analyses Listing Instruments Vocabulary
  src/bika/lims/browser/analyses/view.py
Labels: Bug

#1723 Allow installation of senaite.core for 1.x upgrade
  src/senaite/core/configure.zcml
  src/senaite/core/profiles/default/types.xml
  src/senaite/core/setuphandlers.py
  src/senaite/core/upgrade/utils.py
Labels: Cleanup, Enhancement

#1724 Purge stale metadata and indexes from analysis catalog
  CHANGES.rst
  src/bika/lims/browser/worksheet/views/results.py
  src/bika/lims/catalog/analysis_catalog.py
  src/bika/lims/catalog/analysisrequest_catalog.py
  src/bika/lims/content/abstractanalysis.py
  src/bika/lims/content/abstractbaseanalysis.py
  src/bika/lims/content/abstractroutineanalysis.py
  src/bika/lims/workflow/duplicateanalysis/events.py
  src/bika/lims/workflow/indexes.py
  src/senaite/core/tests/doctests/WorksheetApplyTemplate.rst
  src/senaite/core/upgrade/v02_00_000.py
Labels: Cleanup

#1726 Content rules control panel templates styled
  CHANGES.rst
  src/senaite/core/browser/configure.zcml
  src/senaite/core/browser/contentrules/__init__.py
  src/senaite/core/browser/contentrules/configure.zcml
  src/senaite/core/browser/contentrules/controlpanel.py
  src/senaite/core/browser/contentrules/elements.py
  src/senaite/core/browser/contentrules/templates/controlpanel.pt
  src/senaite/core/browser/contentrules/templates/manage-elements.pt
Labels: Enhancement

#1727 Cleanup Controlpanel Items
  CHANGES.rst
  src/bika/lims/__init__.py
  src/bika/lims/controlpanel/bika_analysiscategories.py
  src/bika/lims/controlpanel/bika_analysisservices.py
  src/bika/lims/controlpanel/bika_artemplates.py
  src/bika/lims/controlpanel/bika_batchlabels.py
  src/bika/lims/controlpanel/bika_containers.py
  src/bika/lims/controlpanel/bika_containertypes.py
  src/bika/lims/controlpanel/bika_identifiertypes.py
  src/bika/lims/controlpanel/bika_idserver.py
  src/bika/lims/controlpanel/bika_instruments.py
  src/bika/lims/controlpanel/bika_instrumenttypes.py
  src/bika/lims/controlpanel/bika_labproducts.py
  src/bika/lims/controlpanel/bika_manufacturers.py
  src/bika/lims/controlpanel/bika_preservations.py
  src/bika/lims/controlpanel/bika_reflexrulefolder.py
  src/bika/lims/controlpanel/bika_sampleconditions.py
  src/bika/lims/controlpanel/bika_samplematrices.py
  src/bika/lims/controlpanel/bika_samplepoints.py
  src/bika/lims/controlpanel/bika_sampletypes.py
  src/bika/lims/controlpanel/bika_samplingdeviations.py
  src/bika/lims/controlpanel/bika_samplingrounds.py
  src/bika/lims/controlpanel/bika_setupitems.py
  src/bika/lims/controlpanel/bika_srtemplates.py
  src/bika/lims/controlpanel/bika_storagelocations.py
  src/bika/lims/controlpanel/bika_subgroups.py
  src/bika/lims/controlpanel/configure.zcml
  src/bika/lims/utils/__init__.py
Labels: Cleanup, Enhancement

#1729 Show navigation controlpanel
  src/senaite/core/profiles/default/controlpanel.xml
  src/senaite/core/profiles/default/registry.xml
  src/senaite/core/upgrade/v02_00_000.py
Labels: Enhancement

#1731 Remove `notifyModified` method from analyses
  CHANGES.rst
  setup.py
  src/senaite/core/upgrade/v02_00_000.py
Labels: Bug, Cleanup

#1732 Readonly Transactions
  CHANGES.rst
  src/senaite/core/browser/form/ajax.py
  src/senaite/core/decorators/__init__.py
Labels: Bug

#1734 Allow to drag&drop images in tinymce
  CHANGES.rst
  src/senaite/core/browser/static/bundles/main.js
  src/senaite/core/browser/static/bundles/main.js.map
  webpack/app/senaite.core.js
Labels: Enhancement

#1737 Fix: formatDateQuery does not add the timezone for queries
  CHANGES.rst
  bika/lims/utils/__init__.py
Labels: To port

#1751 Fix typos and naming in import template
  CHANGES.rst
  src/senaite/core/exportimport/import.pt
Labels: Cleanup

#1752 Improve memory consumption of upgrade steop
  src/senaite/core/upgrade/v02_00_000.py
Labels: Enhancement

#1753 Fixed indexing of partitions and missing metadata generation
  CHANGES.rst
  src/bika/lims/catalog/indexers/__init__.py
  src/bika/lims/catalog/indexers/analysisrequest.py
Labels: Bug, Cleanup

#1754 Fix KeyError in calculation validator
  CHANGES.rst
  src/bika/lims/validators.py
Labels: Bug
