Repository senaite/senaite.core, pull requests merged in 2022-01, with the labels that each got.

#1903 Added date and time field/widget for Dexterity contents
  .scrutinizer.yml
  CHANGES.rst
  src/senaite/core/api/dtime.py
  src/senaite/core/schema/__init__.py
  src/senaite/core/schema/datetimefield.py
  src/senaite/core/schema/datetimefield.txt
  src/senaite/core/schema/fields.py
  src/senaite/core/schema/interfaces.py
  src/senaite/core/tests/doctests/API_datetime.rst
  src/senaite/core/z3cform/interfaces.py
  src/senaite/core/z3cform/static/datetimewidget.css
  src/senaite/core/z3cform/static/datetimewidget.js
  src/senaite/core/z3cform/widgets/configure.zcml
  src/senaite/core/z3cform/widgets/datetimewidget.py
  src/senaite/core/z3cform/widgets/datetimewidget.txt
  src/senaite/core/z3cform/widgets/datetimewidget.zcml
  src/senaite/core/z3cform/widgets/datetimewidget_display.pt
  src/senaite/core/z3cform/widgets/datetimewidget_hidden.pt
  src/senaite/core/z3cform/widgets/datetimewidget_input.pt
Labels: Enhancement

#1905 Fix empty field in sample add form when using edit accessor
  CHANGES.rst
  buildout.cfg
  src/bika/lims/browser/analysisrequest/add2.py
Labels: Bug

#1906 Fix traceback in auditlog view when context is a Dexterity type
  CHANGES.rst
  bika/lims/browser/auditlog.py
Labels: Bug, P0: Critical, Version 1.3

#1907 Fix datetime field/widget shows current date and time if empty
  CHANGES.rst
  src/senaite/core/api/dtime.py
  src/senaite/core/schema/datetimefield.py
  src/senaite/core/tests/doctests/API_datetime.rst
  src/senaite/core/z3cform/widgets/datetimewidget.py
Labels: Bug, P1: Urgent

#1908 Added searchable text querystring converter to catalog API
  CHANGES.rst
  src/senaite/core/api/catalog.py
  src/senaite/core/tests/doctests/API_catalog.rst
Labels: Addition

#1909 Allow to navigate and select with arrow keys in dexterity reference widget
  CHANGES.rst
  src/senaite/core/browser/static/bundles/main.js
  src/senaite/core/browser/static/bundles/main.js.map
  webpack/app/widgets/uidreferencewidget/components/ReferenceField.js
  webpack/app/widgets/uidreferencewidget/components/ReferenceResults.js
  webpack/app/widgets/uidreferencewidget/widget.js
Labels: Enhancement

#1910 Avoid parse errors for ZCTextIndex
  src/senaite/core/api/catalog.py
  src/senaite/core/tests/doctests/API_catalog.rst
Labels: Bug

#1912 Fixed typo in sample view
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/templates/analysisrequest_view.pt
Labels: Bug

#1914 Provide context, widget and fieldname for callable base queries in AT reference widgets
  CHANGES.rst
  src/senaite/core/browser/widgets/referencewidget.py
Labels: Enhancement

#1915 Support list queries in dx reference widget
  CHANGES.rst
  src/senaite/core/browser/static/bundles/main.js
  src/senaite/core/browser/static/bundles/main.js.map
  webpack/app/widgets/uidreferencewidget/api.js
Labels: Enhancement

#1916 Provide the request record to object info adapters in the sample add form
  CHANGES.rst
  src/bika/lims/adapters/addsample.py
  src/bika/lims/browser/analysisrequest/add2.py
Labels: Enhancement

#1917 Fix wrong context in reference widget lookups
  CHANGES.rst
  src/senaite/core/browser/widgets/referencewidget.py
Labels: Bug

#1918 Fix stale combobox items displayed when search query changed
  CHANGES.rst
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.add.js
  src/senaite/core/browser/static/js/coffee/bika.lims.analysisrequest.add.coffee
  src/senaite/core/browser/widgets/referencewidget.py
  src/senaite/core/skins/senaite_templates/senaite_widgets/referencewidget.js
Labels: Bug

#1920 Fix indexed attributes not set when adding a new index with catalog API
  CHANGES.rst
  src/senaite/core/api/catalog.py
Labels: Bug

#1923 Use native date input fields in reports
  CHANGES.rst
  src/bika/lims/browser/reports/selection_macros/select_daterange.pt
Labels: Bug

#1924 Fix viewlet rendering error on login screen
  CHANGES.rst
  src/senaite/core/profiles/default/viewlets.xml
  src/senaite/core/upgrade/v02_02_000.py
Labels: Bug

#1925 Fix sample transition in listings
  CHANGES.rst
  src/bika/lims/browser/workflow/analysisrequest.py
  src/bika/lims/workflow/analysisrequest/events.py
  src/senaite/core/browser/samples/view.py
  src/senaite/core/datamanagers/sample.py
Labels: Bug

#1928 Added `on_change` hook for methods in analyses listings
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/browser/worksheet/views/analyses.py
Labels: Enhancement

#1927 Analysis attachment is copied on retest
  CHANGES.rst
  src/bika/lims/utils/analysis.py
Labels: Bug
