Repository senaite/senaite.core, pull requests merged in 2022-06, with the labels that each got.

#2003 Do not compute dynamic local permissions unless the principal is a user
  src/senaite/core/adapters/localroles.py
Labels: Enhancement

#2004 Added behavior to allow sharing objects across clients users
  CHANGES.rst
  src/bika/lims/profiles/default/rolemap.xml
  src/senaite/core/adapters/configure.zcml
  src/senaite/core/adapters/localroles.py
  src/senaite/core/behaviors/__init__.py
  src/senaite/core/behaviors/clientshareable.py
  src/senaite/core/behaviors/configure.zcml
  src/senaite/core/behaviors/utils.py
  src/senaite/core/configure.zcml
  src/senaite/core/schema/uidreferencefield.py
Labels: Addition

#2002 Allow string results for calculation dependencies
  CHANGES.rst
  src/bika/lims/content/abstractanalysis.py
Labels: Enhancement

#2009 Fix missing keyword in analysis profile view
  CHANGES.rst
  src/bika/lims/browser/widgets/analysisprofileanalyseswidget.py
Labels: Bug

#2010 Fix TypeError in Analyses Listing View
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
Labels: Bug

#2013 Fix ValueError in uidreferencefield when context is not a IBehavior
  CHANGES.rst
  src/senaite/core/schema/uidreferencefield.py
Labels: Bug

#2014 Remove `zopyx.txng3.ext` requirement
  setup.py
Labels: Bug

#2017 Performance: Fix base catalog interface
  src/senaite/core/catalog/base_catalog.py
  src/senaite/core/catalog/indexer/generic.py
Labels: Bug

#2021 Reduced logging when creating samples
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
  src/bika/lims/browser/fields/historyawarereferencefield.py
  src/bika/lims/content/analysisrequest.py
  src/bika/lims/decorators.py
  src/bika/lims/monkey/Widget.py
Labels: Cleanup

#2023 Render hyperlinks for reference widget targets in view/edit mode
  CHANGES.rst
  src/bika/lims/browser/header_table.py
  src/bika/lims/browser/invoice.py
  src/bika/lims/browser/invoice.zcml
  src/bika/lims/content/analysisrequest.py
  src/senaite/core/skins/senaite_templates/senaite_widgets/referencewidget.pt
Labels: Enhancement

#2024 Cannot create partitions from samples in received status
  CHANGES.rst
  src/bika/lims/permissions.py
  src/bika/lims/permissions.zcml
  src/bika/lims/profiles/default/rolemap.xml
  src/bika/lims/workflow/analysisrequest/guards.py
  src/senaite/core/profiles/default/workflows/senaite_sample_workflow/definition.xml
  src/senaite/core/tests/doctests/WorkflowAnalysisRequestCreatePartitions.rst
  src/senaite/core/upgrade/v02_03_000.py
Labels: Bug, P0: Critical

#2026 Fix LabManager and LabClerk cannot add preservations
  CHANGES.rst
  src/bika/lims/profiles/default/rolemap.xml
Labels: Bug

#2027 Fix Manufacturer is not displayed in Reference Samples listing
  CHANGES.rst
  src/bika/lims/browser/referencesample.py
Labels: Bug

#2028 Fix Definition is not displayed in Reference Samples listing
  CHANGES.rst
  src/bika/lims/browser/referencesample.py
Labels: Bug

#2025 Fix analyst unchanged in analyses listing after worksheet reassignment
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/content/abstractanalysis.py
  src/senaite/core/catalog/analysis_catalog.py
  src/senaite/core/upgrade/v02_03_000.py
Labels: Bug

#2029 Fix AttributeError in Manufacturer's Instruments view
  CHANGES.rst
  src/bika/lims/browser/manufacturer.py
Labels: Bug

#2030 Fix Email address is not displayed in clients listing
  CHANGES.rst
  src/bika/lims/browser/clientfolder.py
Labels: Bug

#2031 Make the "Other reasons" text area from rejection view wider
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/templates/reject_samples.pt
Labels: Enhancement
