Repository senaite/senaite.core, pull requests merged in 2022-07, with the labels that each got.

#2032 Fix add-on stickers not displayed in sample type admitted stickers
  CHANGES.rst
  src/bika/lims/browser/widgets/sampletypestickerswidget.py
  src/bika/lims/content/sampletype.py
  src/bika/lims/skins/bika/bika_widgets/sampletypestickerswidget.js
  src/senaite/core/browser/form/adapters/configure.zcml
  src/senaite/core/browser/form/adapters/sampletype.py
Labels: Bug, Cleanup

#2033 Fix blurry Barcode and QRCode in stickers
  CHANGES.rst
  src/bika/lims/barcode.py
  src/bika/lims/configure.zcml
  src/senaite/core/browser/static/bundles/legacy.js
  src/senaite/core/browser/static/js/bika.lims.utils.barcode.js
  src/senaite/core/tests/test_barcode_entry.py
Labels: Enhancement, Cleanup

#2043 Fix printed time does not get updated on re-Print
  CHANGES.rst
  src/bika/lims/browser/workflow/analysisrequest.py
Labels: Bug

#2034 Fix error in sample view when ccemails is None (#1674 port)
  CHANGES.rst
  bika/lims/browser/analysisrequest/__init__.py
Labels: Version 1.3

#2035 Fix Attribute Error when creating invoice PDF (#1683 port)
  CHANGES.rst
  bika/lims/browser/analysisrequest/invoice.py
  bika/lims/browser/analysisrequest/templates/invoice_content.pt
Labels: Version 1.3

#2036 Show only active dynamic analysisspecs in reference widget (#1684 port)
  CHANGES.rst
  bika/lims/content/analysisspec.py
Labels: Version 1.3

#2037 Removed add button in auditlog listing view (#1714 port)
  CHANGES.rst
  bika/lims/browser/auditlog.py
Labels: Version 1.3

#2038 Fix UnicodeDecodeError for Instrument Import Log View (#1720 port)
  CHANGES.rst
  bika/lims/browser/instrument.py
Labels: Version 1.3

#2039 Fix items not filtered by Worksheet Template's method in (#1990 port)
  CHANGES.rst
  bika/lims/browser/worksheet/views/add_analyses.py
Labels: Version 1.3

#2040 Fix analysis hidden status erases on results submit (#1998 port)
  CHANGES.rst
  bika/lims/browser/workflow/analysis.py
Labels: Version 1.3

#2045 Fix instrument types instruments view
  CHANGES.rst
  src/bika/lims/browser/instrumenttype.py
Labels: Bug

#2047 Make resultsinterpretations template to rely on the viewlet for departments retrieval
  CHANGES.rst
  src/senaite/core/browser/viewlets/resultsinterpretation.py
  src/senaite/core/browser/viewlets/templates/resultsinterpretation.pt
Labels: Cleanup

#2048 Fix catalog logging counter duplicates
  CHANGES.rst
  src/senaite/core/catalog/base_catalog.py
Labels: Bug

#2058 Filter 'Interpretation templates' in sample view by template and type
  CHANGES.rst
  src/senaite/core/browser/viewlets/resultsinterpretation.py
  src/senaite/core/content/interpretationtemplate.py
  src/senaite/core/interfaces/__init__.py
  src/senaite/core/profiles/default/types/InterpretationTemplate.xml
  src/senaite/core/upgrade/v02_03_000.py
Labels: Addition

#2050 Fix ProfileKey is not shown in Profiles table (#1987 port)
  CHANGES.rst
  bika/lims/controlpanel/bika_analysisprofiles.py
Labels: Version 1.3

#2051 Fix missing keyword in analysis profile view (#2009 port)
  CHANGES.rst
  bika/lims/browser/widgets/analysisprofileanalyseswidget.py
Labels: Version 1.3

#2054 Fix AttributeError in Manufacturer's Instruments view (#2029 port)
  CHANGES.rst
  bika/lims/browser/manufacturer.py
Labels: Version 1.3

#2056 Fix printed time does not get updated on re-print (#2043 port)
  CHANGES.rst
  bika/lims/browser/workflow/analysisrequest.py
Labels: Version 1.3

#2057 Make "Other reasons" text area from rejection view wider (#2031 port)
  CHANGES.rst
  bika/lims/browser/analysisrequest/templates/reject_samples.pt
Labels: Version 1.3

#2059 Fix Definition not displayed in Reference Samples listing (#2028 port)
  CHANGES.rst
  bika/lims/browser/referencesample.py
Labels: Version 1.3

#2060 Performance: Avoid to catalog temporary objects (#2015 + #2018 ports)
  CHANGES.rst
  bika/lims/api/__init__.py
  bika/lims/monkey/__init__.py
  bika/lims/monkey/archetypes.py
  bika/lims/monkey/catalog.py
  bika/lims/monkey/configure.zcml
  bika/lims/monkey/dexterity.py
  bika/lims/tests/doctests/API.rst
Labels: Version 1.3

#2061 Fire notifications when UID references are created/destroyed
  CHANGES.rst
  src/senaite/core/events/uidreference.py
  src/senaite/core/schema/configure.zcml
  src/senaite/core/schema/uidreferencefield.py
Labels: Addition, Enhancement

#2062 Fix listing not updated after instrument assignment in Worksheet's view
  CHANGES.rst
  src/senaite/core/browser/static/bundles/legacy.js
  src/senaite/core/browser/static/js/bika.lims.worksheet.js
  src/senaite/core/browser/static/js/coffee/bika.lims.worksheet.coffee
Labels: Bug, To port

#2064 Fix Traceback for SENAITE Setup during installation
  src/bika/lims/content/bikasetup.py
  src/senaite/core/setuphandlers.py
Labels: Bug, P0: Critical

#2065 Fix "Create Worksheet" modal visible for samples w/o unassigned analyses
  CHANGES.rst
  src/senaite/core/browser/samples/view.py
Labels: Bug

#2066 Fix samples w/o active analyses are displayed under "unassigned" filter
  CHANGES.rst
  src/senaite/core/catalog/indexer/sample.py
  src/senaite/core/upgrade/v02_03_000.py
Labels: Bug, To port

#2069 Replace ParentAnalysisRequest ReferenceField by UIDReferenceField
  CHANGES.rst
  src/bika/lims/content/analysisrequest.py
  src/senaite/core/catalog/indexer/sample.py
  src/senaite/core/upgrade/v02_03_000.py
Labels: Enhancement, Cleanup, To port

#2071 Move sample reports to report catalog, add batch ID and email sent flag to listing
  CHANGES.rst
  src/bika/lims/browser/publish/reports_listing.py
  src/senaite/core/catalog/indexer/arreport.py
  src/senaite/core/catalog/indexer/configure.zcml
  src/senaite/core/catalog/report_catalog.py
  src/senaite/core/setuphandlers.py
  src/senaite/core/upgrade/v02_03_000.py
Labels: Addition, Enhancement

#2072 Refactor report filename generation to own method
  CHANGES.rst
  src/bika/lims/browser/publish/downloadview.py
  src/bika/lims/browser/publish/emailview.py
Labels: Cleanup

#2074 Allow to disable global Auditlogging
  CHANGES.rst
  src/bika/lims/content/bikasetup.py
  src/senaite/core/browser/viewlets/auditlog.py
  src/senaite/core/browser/viewlets/configure.zcml
  src/senaite/core/browser/viewlets/templates/auditlog_disabled.pt
  src/senaite/core/content/senaitesetup.py
  src/senaite/core/patches/catalog.py
Labels: Enhancement
