Repository senaite/senaite.core, pull requests merged in 2022-05, with the labels that each got.

#1992 Fix Generic Setup XML export/import adapters for Dexterity fields
  CHANGES.rst
  src/senaite/core/exportimport/genericsetup/adapters.py
  src/senaite/core/exportimport/genericsetup/configure.zcml
Labels: Bug, Enhancement

#1994 Support for dynamic assignment of Local Roles for context and principal
  CHANGES.rst
  src/senaite/core/adapters/configure.zcml
  src/senaite/core/adapters/localroles.py
  src/senaite/core/interfaces/__init__.py
Labels: Addition

#1995 Dynamic assingment of "Owner" role for Client Contacts
  CHANGES.rst
  src/bika/lims/content/contact.py
  src/senaite/core/adapters/configure.zcml
  src/senaite/core/adapters/localroles.py
  src/senaite/core/upgrade/v02_02_000.py
Labels: Enhancement

#1997 Fix conditions are not set when adding analyses manually via manage analyses view
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/browser/fields/aranalysesfield.py
  src/bika/lims/content/abstractroutineanalysis.py
  src/senaite/core/browser/modals/analysis.py
  src/senaite/core/browser/modals/templates/set_analysis_conditions.pt
  src/senaite/core/upgrade/v02_02_000.py
Labels: Bug
