Repository senaite/senaite.core, pull requests merged in 2022-11, with the labels that each got.

#2178 AT Queryselect Widget
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
  src/bika/lims/browser/analysisrequest/templates/ar_add2.pt
  src/senaite/core/browser/static/bundles/senaite.core.widgets.css
  src/senaite/core/browser/static/bundles/senaite.core.widgets.css.map
  src/senaite/core/browser/static/bundles/senaite.core.widgets.js
  src/senaite/core/browser/static/bundles/senaite.core.widgets.js.map
  src/senaite/core/browser/static/css/bika.lims.analysisrequest.add.css
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.add.js
  src/senaite/core/browser/static/js/coffee/bika.lims.analysisrequest.add.coffee
  src/senaite/core/browser/widgets/__init__.py
  src/senaite/core/browser/widgets/queryselect.py
  src/senaite/core/skins/senaite_templates/senaite_widgets/queryselectwidget.pt
  webpack/app/widgets/components/SearchField.js
  webpack/app/widgets/components/SearchResults.css
  webpack/app/widgets/components/SearchResults.js
  webpack/app/widgets/queryselect/widget.js
Labels: Enhancement

#2179 Fix Traceback when removing a Worksheet
  CHANGES.rst
  src/bika/lims/workflow/worksheet/events.py
  src/bika/lims/workflow/worksheet/guards.py
Labels: Bug, P0: Critical, To port

#2180 Rely on analysis permission when displaying results
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/content/abstractanalysis.py
  src/bika/lims/profiles/default/rolemap.xml
  src/senaite/core/profiles/default/workflows/senaite_sample_workflow/definition.xml
Labels: Enhancement

#2181 Fix overflow of selected values for queryselect/uidreference widgets
  src/senaite/core/z3cform/widgets/queryselect/display.pt
  src/senaite/core/z3cform/widgets/uidreference/display.pt
Labels: Bug

#2193 Fix analyst cannot import results from instruments
  CHANGES.rst
  src/senaite/core/browser/form/configure.zcml
Labels: Bug
