Repository senaite/senaite.core, pull requests merged in 2022-08, with the labels that each got.

#2076 Fix style of selected language in dropdown
  CHANGES.rst
  src/senaite/core/browser/viewlets/templates/languageselector.pt
Labels: Bug

#2075 Allow to override logo and styles in new SENAITE Setup
  CHANGES.rst
  src/senaite/core/browser/globals/configure.zcml
  src/senaite/core/browser/globals/sitelogo.py
  src/senaite/core/browser/viewlets/toolbar.py
  src/senaite/core/content/senaitesetup.py
Labels: Enhancement

#2082 Include sample ID in form ID for lab, field and qc analyses listings
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/tables.py
Labels: Enhancement

#2083 Lookup workflow action redirect URL from request first
  CHANGES.rst
  src/bika/lims/browser/workflow/__init__.py
Labels: Enhancement

#2089 Fix LDL/UDL cut-off and exponential float conversion
  CHANGES.rst
  src/bika/lims/content/abstractanalysis.py
  src/bika/lims/content/abstractbaseanalysis.py
  src/senaite/core/tests/test_limitdetections.py
Labels: Bug, P1: Urgent

#2090 Add support for dates before 1900
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/bika/lims/browser/__init__.py
  src/bika/lims/content/abstractbaseanalysis.py
  src/senaite/core/api/dtime.py
  src/senaite/core/browser/samples/view.py
  src/senaite/core/browser/widgets/datetimewidget.py
  src/senaite/core/content/senaitesetup.py
  src/senaite/core/tests/doctests/API_datetime.rst
  src/senaite/core/z3cform/widgets/datetimewidget.py
Labels: Bug, Enhancement, P1: Urgent, Cleanup

#2094 Skip Auditlog catalog if disabled for DX types catalog multiplexer
  CHANGES.rst
  src/senaite/core/catalog/catalog_multiplex_processor.py
Labels: Enhancement, Performance, To port

#2095 Fix rounded uncertainty value is stored in the database
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
Labels: Bug, P1: Urgent, To port

#2096 Convert uncertainty field to string
  src/bika/lims/api/__init__.py
  src/bika/lims/content/abstractanalysis.py
  src/bika/lims/content/abstractroutineanalysis.py
  src/bika/lims/utils/analysis.py
  src/senaite/core/tests/doctests/API.rst
  src/senaite/core/tests/doctests/Uncertainties.rst
  src/senaite/core/tests/test_manualuncertainty.py
  src/senaite/core/upgrade/v02_03_000.py
Labels: Addition, Enhancement, Cleanup

#2097 Fix Attribute Error in Multi- Sample Add form when current user is linked to a client contact
  CHANGES.rst
  src/senaite/core/browser/widgets/referencewidget.py
  src/senaite/core/skins/senaite_templates/senaite_widgets/referencewidget.pt
Labels: Bug

#2101 Add help text for numeric result
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
Labels: Enhancement, P4: Nice To Have

#2103 Convert LDL/UDL fields to string
  CHANGES.rst
  src/bika/lims/content/abstractbaseanalysis.py
  src/senaite/core/upgrade/v02_03_000.py
Labels: Enhancement, P2: Very Important

#2104 Fix result formatting when result is below LDL or above UDL
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/bika/lims/content/abstractanalysis.py
  src/bika/lims/utils/__init__.py
  src/senaite/core/tests/doctests/API.rst
  src/senaite/core/tests/doctests/Uncertainties.rst
Labels: Bug, P3: Important, Cleanup

#2106 Allow to disable global Auditlogging (#2074 #2094 ports)
  CHANGES.rst
  bika/lims/browser/viewlets/auditlog.py
  bika/lims/browser/viewlets/configure.zcml
  bika/lims/browser/viewlets/templates/auditlog_disabled.pt
  bika/lims/catalog/catalog_multiplex_processor.py
  bika/lims/content/bikasetup.py
  bika/lims/monkey/catalog.py
Labels: Version 1.3

#2107 Replace Worksheet's Analysis ReferenceField by UIDReferenceField (#2022 port)
  CHANGES.rst
  bika/lims/content/abstractanalysis.py
  bika/lims/content/worksheet.py
  bika/lims/upgrade/v01_03_006.py
Labels: Version 1.3

#2108 Replace ParentAnalysisRequest ReferenceField by UIDReferenceField (#2069 port)
  CHANGES.rst
  bika/lims/content/analysisrequest.py
  bika/lims/upgrade/v01_03_006.py
Labels: Version 1.3

#2111 Replace header table with customizable sample header viewlet
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/__init__.py
  src/bika/lims/browser/analysisrequest/templates/analysisrequest_view.pt
  src/bika/lims/browser/analysisrequest/view.py
  src/bika/lims/browser/header_table.py
  src/bika/lims/browser/templates/header_table.pt
  src/senaite/core/browser/samples/configure.zcml
  src/senaite/core/browser/samples/manage_sample_fields.py
  src/senaite/core/browser/samples/templates/manage_sample_fields.pt
  src/senaite/core/browser/static/bundles/main.css
  src/senaite/core/browser/static/bundles/main.css.map
  src/senaite/core/browser/viewlets/configure.zcml
  src/senaite/core/browser/viewlets/interfaces.py
  src/senaite/core/browser/viewlets/sampleheader.py
  src/senaite/core/browser/viewlets/templates/sampleheader.pt
  src/senaite/core/profiles/default/registry.xml
  src/senaite/core/profiles/default/viewlets.xml
  src/senaite/core/registry/__init__.py
  src/senaite/core/registry/controlpanel.py
  src/senaite/core/registry/schema.py
  webpack/app/scss/forms.scss
Labels: Addition, Enhancement, Cleanup

#2114 Allow Multi Analysis Results Entry
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
  src/bika/lims/browser/stickers.py
  src/bika/lims/browser/templates/stickers_preview.pt
  src/bika/lims/content/bikasetup.py
  src/bika/lims/permissions.py
  src/bika/lims/permissions.zcml
  src/bika/lims/workflow/analysisrequest/guards.py
  src/senaite/core/adapters/configure.zcml
  src/senaite/core/adapters/sample.py
  src/senaite/core/browser/contentmenu/view.py
  src/senaite/core/browser/samples/configure.zcml
  src/senaite/core/browser/samples/multi_results.py
  src/senaite/core/browser/samples/templates/multi_results.pt
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.add.js
  src/senaite/core/browser/static/js/coffee/bika.lims.analysisrequest.add.coffee
  src/senaite/core/content/senaitesetup.py
  src/senaite/core/profiles/default/rolemap.xml
  src/senaite/core/profiles/default/workflows/senaite_sample_workflow/definition.xml
Labels: Addition, Cleanup

#2115 Fix insufficient privileges for instrument QC viewlet
  CHANGES.rst
  src/bika/lims/browser/viewlets/configure.zcml
Labels: Bug, P3: Important, To port

#2116 Fix allow sample partitions in submitted states
  src/senaite/core/profiles/default/workflows/senaite_sample_workflow/definition.xml
  src/senaite/core/tests/doctests/WorkflowAnalysisRequestCreatePartitions.rst
Labels: Regression

#2117 Customized User/Groups Preferences in Site Configuration
  CHANGES.rst
  src/senaite/core/browser/configure.zcml
  src/senaite/core/browser/usergroup/__init__.py
  src/senaite/core/browser/usergroup/configure.zcml
  src/senaite/core/browser/usergroup/templates/account-configlet.pt
  src/senaite/core/browser/usergroup/templates/usergroups_groupdetails.pt
  src/senaite/core/browser/usergroup/templates/usergroups_groupmembership.pt
  src/senaite/core/browser/usergroup/templates/usergroups_groupsoverview.pt
  src/senaite/core/browser/usergroup/templates/usergroups_usermembership.pt
  src/senaite/core/browser/usergroup/templates/usergroups_usersoverview.pt
  src/senaite/core/browser/usergroup/userdatapanel.py
  src/senaite/core/browser/usergroup/usergroups_groupsoverview.py
  src/senaite/core/browser/usergroup/usergroups_usersoverview.py
  src/senaite/core/config/roles.py
  src/senaite/core/skins/senaite_images/site_icon.png
Labels: Enhancement, Cleanup

#2118 Customized Quickinstaller Configlet
  CHANGES.rst
  src/senaite/core/browser/configure.zcml
  src/senaite/core/browser/quickinstaller/__init__.py
  src/senaite/core/browser/quickinstaller/configure.zcml
  src/senaite/core/browser/quickinstaller/quickinstaller.py
  src/senaite/core/browser/quickinstaller/templates/quickinstaller.pt
Labels: Enhancement, Cleanup

#2119 Fix linked client contact user can not see existing samples
  CHANGES.rst
  src/bika/lims/browser/templates/login_details.pt
  src/bika/lims/content/contact.py
Labels: Bug, Cleanup
