Repository senaite/senaite.core, pull requests merged in 2022-12, with the labels that each got.

#2196 Order sample analyses by sortable title on get per default
  CHANGES.rst
  src/bika/lims/browser/fields/aranalysesfield.py
Labels: Enhancement

#2198 Use portal as relative path for sticker icons (#2197 port)
  CHANGES.rst
  bika/lims/browser/analysisrequest/templates/analysisrequest_manage_results.pt
  bika/lims/browser/analysisrequest/templates/analysisrequest_view.pt
  bika/lims/browser/analysisrequest/templates/analysisrequests.pt
  bika/lims/browser/analysisrequest/templates/ar_add2.pt
  bika/lims/browser/templates/stickers/readme.txt
  bika/lims/browser/worksheet/templates/results.pt
  bika/lims/profiles/default/types/AnalysisRequest.xml
  bika/lims/profiles/default/types/Batch.xml
  bika/lims/profiles/default/types/Invoice.xml
  bika/lims/profiles/default/types/ReferenceSample.xml
  bika/lims/profiles/default/types/SupplyOrder.xml
  bika/lims/profiles/default/types/Worksheet.xml
  bika/lims/upgrade/v01_03_006.py
Labels: Version 1.3

#2202 Fix detection limit set manually is not displayed on result save
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/content/abstractanalysis.py
Labels: Bug

#2204 Fix traceback when retracting an analysis with a detection limit
  CHANGES.rst
  src/bika/lims/content/abstractanalysis.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/tests/doctests/WorkflowAnalysisRetract.rst
  src/senaite/core/tests/test_calculations.py
  src/senaite/core/upgrade/v02_04_000.py
  src/senaite/core/upgrade/v02_04_000.zcml
Labels: Bug

#2208 Remove `default_method` from AnalysisRequest's Contact field
  CHANGES.rst
  src/bika/lims/content/analysisrequest.py
  src/bika/lims/content/client.py
Labels: Cleanup, Performance, To port

#2207 Support for file upload on analysis (pre) conditions
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/browser/analysisrequest/add2.py
  src/bika/lims/content/abstractroutineanalysis.py
  src/bika/lims/content/analysisservice.py
  src/bika/lims/content/attachment.py
  src/senaite/core/browser/modals/analysis.py
  src/senaite/core/browser/modals/templates/set_analysis_conditions.pt
Labels: Addition

#2211 Remove `Profile` field (stale) from AnalysisRequest
  CHANGES.rst
  src/bika/lims/content/analysisrequest.py
  src/senaite/core/exportimport/setupdata/__init__.py
Labels: Cleanup

#2212 Improve performance of legacy AT `UIDReferenceField`'s getter
  CHANGES.rst
  src/bika/lims/browser/fields/uidreferencefield.py
Labels: Performance, To port

#2213 Purge ComputedField fields from AnalysisRequest related with Profiles
  CHANGES.rst
  src/bika/lims/content/analysisrequest.py
  src/senaite/core/browser/samples/view.py
  src/senaite/core/catalog/sample_catalog.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_04_000.py
  src/senaite/core/upgrade/v02_04_000.zcml
Labels: Cleanup, Performance, To port

#2215 Fix ParseError when search term contains parenthesis in widget search
  CHANGES.rst
  src/bika/lims/adapters/referencewidgetvocabulary.py
Labels: Bug

#2214 Remove `DefaultContainerType` field (stale) from AnalysisRequest
  CHANGES.rst
  src/bika/lims/content/analysisrequest.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_04_000.py
  src/senaite/core/upgrade/v02_04_000.zcml
Labels: Cleanup

#2217 Fix traceback when creating multiple samples with attachments
  src/bika/lims/browser/analysisrequest/add2.py
Labels: Bug

#2218 Improve performance of legacy AT `UIDReferenceField`'s setter
  CHANGES.rst
  src/bika/lims/browser/fields/uidreferencefield.py
Labels: Cleanup, Performance, To port

#2209 Migrate AnalysisRequest's ReferenceField fields to UIDReferenceField
  CHANGES.rst
  src/bika/lims/content/analysisrequest.py
  src/bika/lims/content/attachment.py
  src/bika/lims/idserver.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_04_000.py
  src/senaite/core/upgrade/v02_04_000.zcml
Labels: Cleanup, Performance
