Repository senaite/senaite.core, pull requests merged in 2022-10, with the labels that each got.

#2158 Fix traceback when accessing registry
  CHANGES.rst
  src/senaite/core/browser/bootstrap/bootstrap.py
Labels: Bug, P3: Important

#2160 Allow indexed attributes for ZCTextIndex in catalog API
  CHANGES.rst
  src/senaite/core/api/catalog.py
Labels: Enhancement

#2162 Allow to create samples without analyses
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
  src/bika/lims/content/bikasetup.py
  src/senaite/core/content/senaitesetup.py
Labels: Enhancement

#2163 Cleanup `get*UID` functions to prevent unnecessary searches and instantiations
  src/bika/lims/content/abstractanalysis.py
  src/bika/lims/content/abstractbaseanalysis.py
  src/bika/lims/content/abstractroutineanalysis.py
  src/bika/lims/content/analysis.py
  src/bika/lims/content/duplicateanalysis.py
  src/bika/lims/content/worksheet.py
  src/bika/lims/content/worksheettemplate.py
Labels: Cleanup

#2166 Fix partitions not displaying complete list of Interpretation Templates
  CHANGES.rst
  src/senaite/core/browser/viewlets/resultsinterpretation.py
Labels: Bug

#2167 Added data-name to field attributes
  src/senaite/core/z3cform/widgets/phone.py
Labels: Bug

#2169 Fix field error indication in sample header
  CHANGES.rst
  src/senaite/core/browser/viewlets/sampleheader.py
  src/senaite/core/browser/viewlets/templates/sampleheader.pt
Labels: Bug

#2170 Replace `filter_by_user` instance variable by `show_only_mine` function in worksheets listing
  src/bika/lims/browser/worksheet/views/folder.py
Labels: Cleanup

#2172 Fix SuperModel import error
  CHANGES.rst
  src/bika/lims/validators.py
Labels: Bug, P0: Critical

#2173 Fix UnicodeDecodeError when a required condition is empty in add form
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
Labels: Bug, P0: Critical

#2174 Force a transaction.commit every 1000 samples on upgrade
  bika/lims/upgrade/v01_03_006.py
Labels: Version 1.3
