Repository senaite/senaite.core, pull requests merged in 2022-02, with the labels that each got.

#1930 Ensure valid timezone in DX datetime field setter
  CHANGES.rst
  src/senaite/core/api/dtime.py
  src/senaite/core/schema/datetimefield.py
  src/senaite/core/schema/datetimefield.txt
  src/senaite/core/tests/doctests/API_datetime.rst
Labels: Bug, P0: Critical

#1932 Fix cannot attach documents to individual analyses in Worksheet context
  CHANGES.rst
  src/bika/lims/browser/worksheet/ajax.py
  src/bika/lims/browser/worksheet/configure.zcml
  src/bika/lims/content/abstractanalysis.py
  src/senaite/core/browser/attachment/attachment.py
  src/senaite/core/browser/static/bundles/legacy.js
  src/senaite/core/browser/static/bundles/main.css.map
  src/senaite/core/browser/static/bundles/main.js.map
  src/senaite/core/browser/static/js/bika.lims.utils.attachments.js
  src/senaite/core/browser/static/js/coffee/bika.lims.utils.attachments.coffee
  src/senaite/core/browser/viewlets/attachments.py
  src/senaite/core/browser/viewlets/templates/worksheet_attachments.pt
Labels: Bug, P1: Urgent

#1933 Added SENAITE maintenance scripts
  CHANGES.rst
  setup.py
  src/senaite/core/decorators/__init__.py
  src/senaite/core/scripts/__init__.py
  src/senaite/core/scripts/_reindex.py
  src/senaite/core/scripts/_upgrade_sites.py
  src/senaite/core/scripts/_zope_passwd.py
  src/senaite/core/scripts/utils.py
Labels: Addition

#1936 Do not display capture date when no result or default result
  CHANGES.rst
  src/bika/lims/browser/fields/aranalysesfield.py
  src/bika/lims/content/abstractanalysis.py
  src/bika/lims/workflow/analysis/events.py
Labels: Bug

#1935 Allow to edit analysis (pre) conditions
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/browser/analysisrequest/manage_analyses.py
  src/bika/lims/browser/analysisrequest/templates/ar_add2.pt
  src/bika/lims/browser/publish/reports_listing.py
  src/bika/lims/browser/worksheet/views/analyses_transposed.py
  src/bika/lims/content/abstractroutineanalysis.py
  src/bika/lims/permissions.py
  src/bika/lims/permissions.zcml
  src/bika/lims/profiles/default/rolemap.xml
  src/senaite/core/browser/modals/analysis.py
  src/senaite/core/browser/modals/configure.zcml
  src/senaite/core/browser/modals/templates/set_analysis_conditions.pt
  src/senaite/core/browser/static/bundles/legacy.js
  src/senaite/core/browser/static/js/bika.lims.site.js
  src/senaite/core/browser/static/js/coffee/bika.lims.site.coffee
  src/senaite/core/profiles/default/workflows/senaite_analysis_workflow/definition.xml
  src/senaite/core/upgrade/v02_02_000.py
Labels: Enhancement

#1938 Converted sample interpretation and remarks widgets into viewlets
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/templates/analysisrequest_results_interpretation.pt
  src/bika/lims/browser/analysisrequest/templates/analysisrequest_view.pt
  src/bika/lims/browser/analysisrequest/view.py
  src/senaite/core/browser/viewlets/configure.zcml
  src/senaite/core/browser/viewlets/interfaces.py
  src/senaite/core/browser/viewlets/remarks.py
  src/senaite/core/browser/viewlets/resultsinterpretation.py
  src/senaite/core/browser/viewlets/templates/remarks.pt
  src/senaite/core/browser/viewlets/templates/resultsinterpretation.pt
Labels: Enhancement, Cleanup

#1942 Fix tab styling in email log popup
  CHANGES.rst
  src/bika/lims/browser/templates/analysisreport_info.pt
Labels: Bug
