Repository senaite/senaite.core, pull requests merged in 2022-04, with the labels that each got.

#1911 Converted Container to Dexterity Contents
  CHANGES.rst
  src/bika/lims/browser/fields/partitionsetupfield.py
  src/bika/lims/browser/partition_magic.py
  src/bika/lims/content/analysisrequest.py
  src/bika/lims/content/container.py
  src/bika/lims/profiles/default/factorytool.xml
  src/bika/lims/profiles/default/structure/bika_setup/.objects
  src/bika/lims/profiles/default/structure/bika_setup/.preserve
  src/bika/lims/profiles/default/structure/bika_setup/bika_containers/.properties
  src/bika/lims/profiles/default/types.xml
  src/bika/lims/profiles/default/types/Container.xml
  src/bika/lims/profiles/default/types/Containers.xml
  src/bika/lims/setuphandlers.py
  src/senaite/core/browser/controlpanel/configure.zcml
  src/senaite/core/browser/controlpanel/samplecontainers.py
  src/senaite/core/browser/form/adapters/data_import.py
  src/senaite/core/configure.zcml
  src/senaite/core/content/samplecontainer.py
  src/senaite/core/content/samplecontainers.py
  src/senaite/core/exportimport/setupdata/__init__.py
  src/senaite/core/interfaces/__init__.py
  src/senaite/core/migration/__init__.py
  src/senaite/core/migration/configure.zcml
  src/senaite/core/migration/migrator.py
  src/senaite/core/migration/utils.py
  src/senaite/core/profiles/default/types.xml
  src/senaite/core/profiles/default/types/SampleContainer.xml
  src/senaite/core/profiles/default/types/SampleContainers.xml
  src/senaite/core/profiles/default/workflows.xml
  src/senaite/core/setuphandlers.py
  src/senaite/core/tests/test_barcode_entry.py
  src/senaite/core/upgrade/utils.py
  src/senaite/core/upgrade/v02_00_000.py
  src/senaite/core/upgrade/v02_02_000.py
Labels: Python 3

#1961 Added `geo` api that relies on `pycountry` for retrieval of countries and subdivisions
  CHANGES.rst
  docs/doctests.rst
  setup.py
  src/bika/lims/api/__init__.py
  src/bika/lims/browser/widgets/addresswidget.py
  src/bika/lims/content/bikasetup.py
  src/senaite/core/api/geo.py
  src/senaite/core/locales/__init__.py
  src/senaite/core/tests/doctests/API.rst
  src/senaite/core/tests/doctests/API_geo.rst
Labels: Cleanup

#1963 Hide custom set-remarks transition when global remarks are disabled in setup
  CHANGES.rst
  src/bika/lims/browser/worksheet/views/analyses.py
Labels: Bug

#1964 Fix add samples URL in batch context for Clients
  CHANGES.rst
  src/senaite/core/browser/viewlets/add_samples.py
Labels: Bug

#1966 Fix to set analysis results in batchbooks
  CHANGES.rst
  src/bika/lims/browser/batch/batchbook.py
  src/bika/lims/interfaces/__init__.py
  src/senaite/core/datamanagers/sample.py
Labels: Bug

#1970 Better error messages in sample add form
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.add.js
  src/senaite/core/browser/static/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Enhancement

#1975 Fix IndexError in Unit formatter
  CHANGES.rst
  src/bika/lims/content/abstractbaseanalysis.py
  src/bika/lims/utils/__init__.py
Labels: Bug

#1978 Unify field sizes in sample view
  CHANGES.rst
  src/bika/lims/content/analysisrequest.py
Labels: Cleanup

#1982 Fix IndexError in Unit formatter (#1975 + #1980 port)
  CHANGES.rst
  bika/lims/content/abstractbaseanalysis.py
  bika/lims/utils/__init__.py
Labels: Version 1.3

#1983 Better error messages in sample add form (#1970 port)
  CHANGES.rst
  bika/lims/browser/analysisrequest/add2.py
  bika/lims/browser/js/bika.lims.analysisrequest.add.js
  bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Version 1.3

#1984 Fix default roles for client field in samples (#1968 port)
  CHANGES.rst
  bika/lims/profiles/default/rolemap.xml
Labels: Version 1.3

#1985 Disallow client users to create sample partitions (#1965 port)
  CHANGES.rst
  bika/lims/workflow/analysisrequest/guards.py
Labels: Version 1.3

#1986 Fixed error with sampler mail (#1941 port)
  CHANGES.rst
  bika/lims/content/analysisrequest.py
Labels: Version 1.3
