Repository senaite/senaite.core, pull requests merged in 2022-03, with the labels that each got.

#1944 Add handler for "content_status_modify"-like requests
  CHANGES.rst
  src/bika/lims/browser/workflow/configure.zcml
  src/senaite/core/browser/static/bundles/legacy.js
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.js
  src/senaite/core/browser/static/js/coffee/bika.lims.analysisrequest.coffee
Labels: Enhancement

#1952 Open analysis specification ranges
  CHANGES.rst
  src/bika/lims/browser/widgets/analysisspecificationwidget.py
  src/bika/lims/validators.py
Labels: Enhancement

#1953 Allow custom id formatting regardless of portal type
  CHANGES.rst
  src/bika/lims/idserver.py
  src/bika/lims/interfaces/__init__.py
Labels: Enhancement, P1: Urgent

#1931 Removed archetypes.schemaextender from senaite.core
  CHANGES.rst
  setup.py
  src/bika/lims/browser/fields/__init__.py
  src/bika/lims/browser/fields/proxyfield.py
  src/bika/lims/content/subgroup.py
  src/bika/lims/fields.py
  src/bika/lims/interfaces/__init__.py
  src/bika/lims/utils/analysis.py
Labels: Cleanup, Python 3
