Repository senaite/senaite.core, pull requests merged in 2022-09, with the labels that each got.

#2123 Add Sample Form: Save and Copy Action
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
  src/bika/lims/browser/analysisrequest/templates/ar_add2.pt
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.add.js
  src/senaite/core/browser/static/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Addition, Enhancement

#2127 Fix instrument expiry date display in listing view
  CHANGES.rst
  src/bika/lims/controlpanel/bika_instruments.py
Labels: Bug

#2128 Fix referenceresults widget view mode
  src/bika/lims/browser/widgets/referenceresultswidget.py
Labels: Bug

#2129 Fix Traceback when invalidating a Sample with Remarks
  CHANGES.rst
  src/bika/lims/browser/fields/remarksfield.py
  src/bika/lims/utils/analysisrequest.py
  src/senaite/core/tests/doctests/WorkflowAnalysisRequestInvalidate.rst
Labels: Bug, P0: Critical

#2131 Allow to edit the analysis service sort keys in the services listing
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/controlpanel/bika_analysisservices.py
  src/senaite/core/datamanagers/analysisservice.py
  src/senaite/core/datamanagers/configure.zcml
Labels: P4: Nice To Have

#2136 Fix unit overlapping with additional icons
  src/bika/lims/browser/analyses/view.py
Labels: Bug, UI & UX

#2130 Catalog mapping for Samples and Analyses
  CHANGES.rst
  src/senaite/core/setuphandlers.py
  src/senaite/core/tests/doctests/Catalogs.rst
  src/senaite/core/upgrade/v02_03_000.py
Labels: Regression

#2138 Always redirect multi-results to samples view
  src/senaite/core/adapters/sample.py
Labels: Enhancement

#2139 Fix LabClerk cannot create partitions from received samples
  CHANGES.rst
  src/senaite/core/profiles/default/workflows/senaite_sample_workflow/definition.xml
Labels: Bug, P0: Critical

#2137 Dynamic Workflow Menu
  CHANGES.rst
  src/senaite/core/browser/contentmenu/configure.zcml
  src/senaite/core/browser/contentmenu/interfaces.py
  src/senaite/core/browser/contentmenu/menu_provider.py
  src/senaite/core/browser/static/bundles/main.js
  src/senaite/core/browser/static/bundles/main.js.map
  webpack/app/senaite.core.js
Labels: Enhancement

#2140 Allow to enable/disable analysis categories for samples
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/content/bikasetup.py
  src/senaite/core/content/senaitesetup.py
Labels: Enhancement

#2143 Fix Traceback when using reaodnly_transaction decorator for objects with no __name__
  CHANGES.rst
  src/senaite/core/decorators/__init__.py
Labels: Bug

#2144 Fix Multi Results Action is displayed for Clients, but raises a Permission Error
  src/senaite/core/profiles/default/rolemap.xml
Labels: Bug

#2142 Ajax submit transition page refresh
  src/senaite/core/browser/bootstrap/bootstrap.py
  src/senaite/core/browser/static/bundles/main.js
  src/senaite/core/browser/static/bundles/main.js.map
  webpack/app/senaite.core.js
Labels: Enhancement

#2146 Fix "No object found for UID: <laboratory_uid>" in report preview
  CHANGES.rst
  src/senaite/core/setuphandlers.py
  src/senaite/core/upgrade/v02_03_000.py
Labels: Bug

#2147 Remove stale function workflow.getReviewHistory
  CHANGES.rst
  src/bika/lims/content/abstractanalysis.py
  src/bika/lims/workflow/__init__.py
  src/senaite/core/tests/doctests/AnalysisTurnaroundTime.rst
  src/senaite/core/tests/doctests/WorkflowAnalysisMultiVerify.rst
  src/senaite/core/tests/doctests/WorkflowDuplicateAnalysisMultiVerify.rst
  src/senaite/core/tests/doctests/WorkflowReferenceAnalysisBlankMultiVerify.rst
  src/senaite/core/tests/doctests/WorkflowReferenceAnalysisControlMultiVerify.rst
Labels: Cleanup

#2148 Performance: prioritize raw getter for AllowedInstruments field
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/content/abstractanalysis.py
  src/bika/lims/content/abstractbaseanalysis.py
Labels: Cleanup

#2149 Performance: prioritize raw getter for AllowedMethods field
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/content/abstractanalysis.py
  src/bika/lims/content/analysisservice.py
Labels: Cleanup

#2150 Improve the creation process of AT content types
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/bika/lims/subscribers/batch.py
  src/bika/lims/subscribers/configure.zcml
  src/senaite/core/tests/doctests/API.rst
  src/senaite/core/tests/doctests/BatchClientAssignment.rst
Labels: Enhancement

#2151 Added api.copy_object function for both DX and AT types
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/senaite/core/tests/doctests/API.rst
Labels: Addition
