Repository senaite/senaite.core, pull requests merged in 2023-12, with the labels that each got.

#2439 Fix analysis template view shows hidden subfields for sample partitions
  CHANGES.rst
  src/senaite/core/skins/senaite_templates/senaite_widgets/recordswidget.pt
Labels: Bug

#2440 Fix multi Code_128_1x48mm sticker renders only 1 PDF
  CHANGES.rst
  src/bika/lims/browser/templates/stickers/Code_128_1x72mm.pt
Labels: Bug

#2443 Fix missing required marker in edit forms
  CHANGES.rst
  src/senaite/core/browser/static/bundles/senaite.core.css
  src/senaite/core/browser/static/bundles/senaite.core.css.map
  webpack/app/scss/forms.scss
Labels: Bug

#2444 Fix reference widget search uses JSON encoded query
  CHANGES.rst
  src/senaite/core/adapters/referencewidget/vocabularies.py
Labels: Bug

#2448 Fix open filter is not visible to analysts in worksheets listing
  CHANGES.rst
  src/bika/lims/browser/worksheet/views/folder.py
Labels: Bug

#2449 Fix Mine button from worksheets listing does not filter by current user
  CHANGES.rst
  src/bika/lims/browser/worksheet/views/folder.py
Labels: Bug

#2450 Fix search bar from worksheet listing does not work
  CHANGES.rst
  src/senaite/core/catalog/indexer/configure.zcml
  src/senaite/core/catalog/indexer/worksheet.py
  src/senaite/core/catalog/worksheet_catalog.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_05_000.py
  src/senaite/core/upgrade/v02_05_000.zcml
Labels: Bug

#2452 Fix reference definition range validation
  CHANGES.rst
  src/bika/lims/browser/widgets/referenceresultswidget.py
  src/bika/lims/content/referencedefinition.py
  src/bika/lims/content/referencesample.py
  src/bika/lims/validators.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_05_000.py
  src/senaite/core/upgrade/v02_05_000.zcml
Labels: Bug

#2453 Fix worksheets are not uncatalogued when deleted
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/bika/lims/workflow/worksheet/events.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/tests/doctests/API.rst
  src/senaite/core/upgrade/v02_05_000.py
  src/senaite/core/upgrade/v02_05_000.zcml
Labels: Bug

#2454 Fix analyses not filtered by selected WST services
  CHANGES.rst
  src/bika/lims/browser/worksheet/templates/add_analyses.pt
  src/bika/lims/browser/worksheet/views/add_analyses.py
Labels: Bug

#2455 Fix users/groups overview batch navigation styling
  CHANGES.rst
  src/senaite/core/browser/batching/__init__.py
  src/senaite/core/browser/batching/configure.zcml
  src/senaite/core/browser/batching/templates/batchnavigation.pt
  src/senaite/core/browser/configure.zcml
  src/senaite/core/browser/usergroup/templates/usergroups_groupmembership.pt
  src/senaite/core/browser/usergroup/templates/usergroups_groupsoverview.pt
  src/senaite/core/browser/usergroup/templates/usergroups_usermembership.pt
  src/senaite/core/browser/usergroup/templates/usergroups_usersoverview.pt
Labels: Bug

#2457 Fix duplicate filter buttons in WS add-analyses listing
  src/bika/lims/browser/worksheet/views/add_analyses.py
Labels: Bug 🐞

#2456 Remove groups from user add form
  CHANGES.rst
  src/senaite/core/browser/configure.zcml
  src/senaite/core/browser/users/__init__.py
  src/senaite/core/browser/users/configure.zcml
  src/senaite/core/browser/users/register.py
  src/senaite/core/browser/users/templates/newuser_form.pt
Labels: Improvement 🔧
