Repository senaite/senaite.core, pull requests merged in 2023-02, with the labels that each got.

#2246 Update ReactJS to version 18.2.0
  CHANGES.rst
  src/senaite/core/browser/static/modules/react-dom/react-dom-server.browser.development.js
  src/senaite/core/browser/static/modules/react-dom/react-dom-server.browser.production.min.js
  src/senaite/core/browser/static/modules/react-dom/react-dom-test-utils.development.js
  src/senaite/core/browser/static/modules/react-dom/react-dom-test-utils.production.min.js
  src/senaite/core/browser/static/modules/react-dom/react-dom-unstable-fizz.browser.development.js
  src/senaite/core/browser/static/modules/react-dom/react-dom-unstable-fizz.browser.production.min.js
  src/senaite/core/browser/static/modules/react-dom/react-dom-unstable-native-dependencies.development.js
  src/senaite/core/browser/static/modules/react-dom/react-dom-unstable-native-dependencies.production.min.js
  src/senaite/core/browser/static/modules/react-dom/react-dom.development.js
  src/senaite/core/browser/static/modules/react-dom/react-dom.production.min.js
  src/senaite/core/browser/static/modules/react-dom/react-dom.profiling.min.js
  src/senaite/core/browser/static/modules/react/react.development.js
  src/senaite/core/browser/static/modules/react/react.production.min.js
  src/senaite/core/browser/static/modules/react/react.profiling.min.js
  webpack/package.json
  webpack/webpack.config.js
  webpack/yarn.lock
Labels: Enhancement

#2247 Fix `AttributeError` when running upgrade 240x with stale brains
  CHANGES.rst
  src/senaite/core/upgrade/v02_04_000.py
Labels: Bug

#2249 Fix APIError: None is not supported (upgrade 1.3.6)
  CHANGES.rst
  bika/lims/upgrade/v01_03_006.py
Labels: Bug

#2248 Fix AttributeError in grade step 2416
  src/senaite/core/upgrade/v02_04_000.py
Labels: Bug

#2250 Fix cannot set string result with greater than ">" or less than "<" symbols
  CHANGES.rst
  src/bika/lims/content/abstractanalysis.py
Labels: Bug

#2251 Fix UnicodeDecodeError in report email form
  CHANGES.rst
  src/bika/lims/browser/publish/emailview.py
Labels: Bug, P1: Urgent

#2252 Fix TypeError when accessing the DX setup folder
  src/bika/lims/content/bikasetup.py
Labels: Bug

#2253 Allow to flush referencefields in sample header
  CHANGES.rst
  src/senaite/core/browser/viewlets/sampleheader.py
  src/senaite/core/browser/viewlets/templates/sampleheader.pt
Labels: Bug, P2: Very Important

#2254 Fix attachments to be ignored are included in email results view
  CHANGES.rst
  src/bika/lims/browser/publish/emailview.py
Labels: Bug

#2257 Fix UnicodeEncode error when viewing report objects
  CHANGES.rst
  src/senaite/core/browser/fields/records.py
Labels: Bug

#2256 Do not keep DX UID reference field back-references per default
  CHANGES.rst
  src/senaite/core/schema/uidreferencefield.py
  src/senaite/core/schema/uidreferencefield.txt
Labels: Enhancement

#2201 Allow manual selection of units on results entry
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/content/abstractbaseanalysis.py
Labels: Enhancement

#2260 Fix sample-header flushes multi-reference fields
  src/senaite/core/browser/viewlets/sampleheader.py
Labels: Bug, P1: Urgent

#2255 Fix attachments from retracted/rejected analyses are not ignored in email results view
  CHANGES.rst
  src/bika/lims/browser/publish/emailview.py
  src/bika/lims/workflow/analysis/events.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_04_000.py
  src/senaite/core/upgrade/v02_04_000.zcml
Labels: Bug

#2261 Fix KeyError in Worksheet analyses listing
  src/bika/lims/browser/analyses/view.py
Labels: Bug

#2262 Simplify attachment render in report options to single checkbox
  CHANGES.rst
  src/bika/lims/browser/analysisreport.py
  src/bika/lims/browser/analysisrequest/add2.py
  src/bika/lims/browser/publish/emailview.py
  src/bika/lims/browser/publish/templates/email.pt
  src/bika/lims/config.py
  src/bika/lims/content/analysisrequest.py
  src/bika/lims/content/attachment.py
  src/bika/lims/workflow/analysis/events.py
  src/senaite/core/browser/attachment/attachment.py
  src/senaite/core/browser/viewlets/attachments.py
  src/senaite/core/browser/viewlets/templates/attachments.pt
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_04_000.py
  src/senaite/core/upgrade/v02_04_000.zcml
Labels: Enhancement

#2263 Move upgrade step 2418 after 2419
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_04_000.py
  src/senaite/core/upgrade/v02_04_000.zcml
Labels: Bug
