Repository senaite/senaite.core, pull requests merged in 2023-06, with the labels that each got.

#2317 Drop travis in favor of Github actions in 1.3.x
  .github/workflows/build-and-test.yml
  .travis.yml
  README.rst
  buildout.cfg
  requirements.txt
  setup.py
  travis.cfg
Labels: Version 1.3

#2320 Performance: prioritize raw getter for AllowedMethods field (#2149 port)
  CHANGES.rst
  bika/lims/content/abstractanalysis.py
Labels: Version 1.3

#2322 Cleanup getUID functions to prevent unnecessary searches and instantiations (#2163 port)
  CHANGES.rst
  bika/lims/content/abstractanalysis.py
  bika/lims/content/abstractbaseanalysis.py
  bika/lims/content/abstractroutineanalysis.py
  bika/lims/content/analysis.py
  bika/lims/content/duplicateanalysis.py
  bika/lims/content/worksheet.py
  bika/lims/content/worksheettemplate.py
Labels: Version 1.3

#2324 Improve performance of legacy AT UIDReferenceField's getter (#2212 port)
  CHANGES.rst
  bika/lims/browser/fields/uidreferencefield.py
  bika/lims/content/analysisrequest.py
  bika/lims/content/attachment.py
  bika/lims/exportimport/setupdata/__init__.py
  bika/lims/idserver.py
  bika/lims/profiles/default/metadata.xml
  bika/lims/upgrade/configure.zcml
  bika/lims/upgrade/v01_03_006.py
  bika/lims/upgrade/v01_03_006.zcml
Labels: Version 1.3

#2325 Purge ComputedField fields from AnalysisRequest related with Profiles (#2213 port)
  CHANGES.rst
  bika/lims/browser/analysisrequest/analysisrequests.py
  bika/lims/catalog/analysisrequest_catalog.py
  bika/lims/content/analysisrequest.py
Labels: Version 1.3

#2326 Improve performance of legacy AT `UIDReferenceField`'s setter (#2218 port)
  CHANGES.rst
  bika/lims/browser/fields/uidreferencefield.py
Labels: Version 1.3

#2327 Migrate ReferenceField fields from setup types to UIDReferenceField (#2219)
  CHANGES.rst
  bika/lims/browser/fields/uidreferencefield.py
  bika/lims/content/abstractanalysis.py
  bika/lims/content/analysisrequest.py
  bika/lims/content/analysisservice.py
  bika/lims/content/calculation.py
  bika/lims/profiles/default/metadata.xml
  bika/lims/upgrade/v01_03_006.py
  bika/lims/upgrade/v01_03_006.zcml
Labels: Version 1.3

#2328 Migrate ReferenceField fields from setup types to UIDReferenceField (port #2221)
  CHANGES.rst
  bika/lims/browser/widgets/referenceresultswidget.py
  bika/lims/content/abstractbaseanalysis.py
  bika/lims/content/abstractroutineanalysis.py
  bika/lims/content/analysiscategory.py
  bika/lims/content/analysisprofile.py
  bika/lims/content/analysisrequest.py
  bika/lims/content/analysisservice.py
  bika/lims/content/arreport.py
  bika/lims/content/artemplate.py
  bika/lims/content/attachment.py
  bika/lims/content/autoimportlog.py
  bika/lims/content/batch.py
  bika/lims/content/bikasetup.py
  bika/lims/content/calculation.py
  bika/lims/content/client.py
  bika/lims/content/contact.py
  bika/lims/content/container.py
  bika/lims/content/department.py
  bika/lims/content/instrument.py
  bika/lims/content/instrumentcalibration.py
  bika/lims/content/instrumentcertification.py
  bika/lims/content/instrumentmaintenancetask.py
  bika/lims/content/instrumentscheduledtask.py
  bika/lims/content/instrumentvalidation.py
  bika/lims/content/invoice.py
  bika/lims/content/labcontact.py
  bika/lims/content/method.py
  bika/lims/content/referencesample.py
  bika/lims/content/reflexrule.py
  bika/lims/content/rejectanalysis.py
  bika/lims/content/report.py
  bika/lims/content/samplepoint.py
  bika/lims/content/sampletype.py
  bika/lims/content/supplyorder.py
  bika/lims/content/worksheet.py
  bika/lims/content/worksheettemplate.py
  bika/lims/idserver.py
  bika/lims/profiles/default/metadata.xml
  bika/lims/subscribers/objectmodified.py
  bika/lims/upgrade/v01_03_006.py
  bika/lims/upgrade/v01_03_006.zcml
Labels: Version 1.3

#2329 Fix read endpoint from internal api does not return uid for uidreference (#2235 port)
  CHANGES.rst
  bika/lims/jsonapi/__init__.py
Labels: Version 1.3

#2331 Little improvement of getRaw function from legacy uidreference field
  CHANGES.rst
  bika/lims/browser/fields/uidreferencefield.py
Labels: Version 1.3

#2333 Fix AttributeError when running upgrade 13603 with stale brains
  bika/lims/upgrade/v01_03_006.py
Labels: Version 1.3

#2336 Fix barcodes not rendered in the pdf when "Inside-Out" Virtual Hosting
  CHANGES.rst
  bika/lims/utils/__init__.py
Labels: Bug, Version 1.3

#2342 Improve reference widget rendering for non existing or empty UIDs/references
  src/senaite/core/browser/static/bundles/senaite.core.widgets.js
  src/senaite/core/browser/static/bundles/senaite.core.widgets.js.map
  src/senaite/core/browser/widgets/queryselect.py
  src/senaite/core/browser/widgets/referencewidget.py
  src/senaite/core/skins/senaite_templates/senaite_widgets/referencewidget.pt
  src/senaite/core/z3cform/widgets/queryselect/display.pt
  src/senaite/core/z3cform/widgets/queryselect/widget.py
  src/senaite/core/z3cform/widgets/uidreference/display.pt
  src/senaite/core/z3cform/widgets/uidreference/widget.py
  webpack/app/widgets/components/SelectedValues.js
Labels: Enhancement

#2344 Fix error on sample copy when fields are hidden
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
  src/bika/lims/browser/analysisrequest/templates/ar_add2.pt
Labels: Bug, P1: Urgent

#2345 Retrieve setup items by object
  CHANGES.rst
  src/senaite/core/browser/controlpanel/setupview.py
  src/senaite/core/browser/controlpanel/templates/setupview.pt
Labels: Enhancement

#2343 Allow to define the sorting criteria for Result Options
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/content/abstractbaseanalysis.py
Labels: Addition

#2346 Fix unauthorized error when accessing dispatch/partition sample view with shared client role
  CHANGES.rst
  src/bika/lims/browser/configure.zcml
  src/senaite/core/browser/samples/configure.zcml
  src/senaite/core/browser/samples/partition_magic.py
  src/senaite/core/browser/samples/templates/partition_magic.pt
Labels: Bug

#2347 Remove unused inline validation view
  CHANGES.rst
  src/bika/lims/browser/configure.zcml
  src/bika/lims/browser/validation.py
Labels: Cleanup
