Repository senaite/senaite.core, pull requests merged in 2023-03, with the labels that each got.

#2264 Collapsible analyses listings in sample view
  CHANGES.rst
  src/senaite/core/browser/viewlets/sampleanalyses.py
  src/senaite/core/browser/viewlets/templates/sampleanalyses.pt
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/profiles/default/registry.xml
  src/senaite/core/registry/schema.py
  src/senaite/core/upgrade/v02_04_000.py
  src/senaite/core/upgrade/v02_04_000.zcml
Labels: Enhancement

#2265 Change sample analysis column order for better results capturing
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/browser/analysisrequest/tables.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/registry/schema.py
  src/senaite/core/upgrade/v02_04_000.zcml
Labels: Enhancement

#2266 Change worksheet analysis column order for better results capturing
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/browser/worksheet/views/analyses.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/profiles/default/registry.xml
  src/senaite/core/registry/schema.py
  src/senaite/core/upgrade/v02_04_000.zcml
Labels: Enhancement

#2268 Add samplepoint information to worksheet slot header
  CHANGES.rst
  src/bika/lims/browser/worksheet/templates/slot_header.pt
  src/bika/lims/browser/worksheet/views/analyses.py
Labels: Enhancement

#2272 Allow to configure the position of additional value columns
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/senaite/core/registry/schema.py
Labels: Enhancement, Cleanup

#2273 Improve performance for sample listing index
  CHANGES.rst
  src/senaite/core/api/catalog.py
  src/senaite/core/catalog/indexer/sample.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/tests/doctests/API_catalog.rst
  src/senaite/core/upgrade/v02_05_000.py
  src/senaite/core/upgrade/v02_05_000.zcml
Labels: Enhancement, Cleanup

#2275 Fix wrong result when "Result options" with "String result" setting enabled
  CHANGES.rst
  src/bika/lims/content/abstractanalysis.py
  src/senaite/core/tests/doctests/ResultOptions.rst
Labels: Bug

#2276 Senaite labels
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/senaite/core/api/label.py
  src/senaite/core/behaviors/configure.zcml
  src/senaite/core/behaviors/label.py
  src/senaite/core/browser/configure.zcml
  src/senaite/core/browser/controlpanel/configure.zcml
  src/senaite/core/browser/controlpanel/labels.py
  src/senaite/core/browser/controlpanel/setupview.py
  src/senaite/core/browser/label/__init__.py
  src/senaite/core/browser/label/configure.zcml
  src/senaite/core/browser/label/labeled_objects.py
  src/senaite/core/browser/label/templates/object_labels.pt
  src/senaite/core/browser/static/assets/icons/label.svg
  src/senaite/core/browser/static/assets/icons/labels.svg
  src/senaite/core/browser/widgets/queryselect.py
  src/senaite/core/catalog/__init__.py
  src/senaite/core/catalog/base_catalog.py
  src/senaite/core/catalog/indexer/configure.zcml
  src/senaite/core/catalog/indexer/label.py
  src/senaite/core/catalog/label_catalog.py
  src/senaite/core/config/fields.py
  src/senaite/core/configure.zcml
  src/senaite/core/content/label.py
  src/senaite/core/content/labels.py
  src/senaite/core/extender/__init__.py
  src/senaite/core/extender/configure.zcml
  src/senaite/core/extender/label.py
  src/senaite/core/interfaces/__init__.py
  src/senaite/core/interfaces/catalog.py
  src/senaite/core/patches/archetypes.py
  src/senaite/core/patches/configure.zcml
  src/senaite/core/patches/dexterity.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/profiles/default/registry.xml
  src/senaite/core/profiles/default/types.xml
  src/senaite/core/profiles/default/types/Label.xml
  src/senaite/core/profiles/default/types/Labels.xml
  src/senaite/core/profiles/default/workflows.xml
  src/senaite/core/registry/configure.zcml
  src/senaite/core/registry/schema.py
  src/senaite/core/registry/subscribers.py
  src/senaite/core/setuphandlers.py
  src/senaite/core/skins/senaite_templates/senaite_widgets/queryselectwidget.pt
  src/senaite/core/tests/doctests/API.rst
  src/senaite/core/tests/doctests/API_label.rst
  src/senaite/core/upgrade/v02_05_000.py
  src/senaite/core/upgrade/v02_05_000.zcml
  src/senaite/core/z3cform/widgets/queryselect/widget.py
Labels: Addition

#2280 Remove custom date rendering in sample header
  CHANGES.rst
  src/senaite/core/browser/viewlets/sampleheader.py
Labels: Cleanup

#2279 Allow all custom transitions in sample report listing
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/published_results.py
  src/bika/lims/browser/publish/reports_listing.py
  src/bika/lims/browser/workflow/configure.zcml
  src/bika/lims/configure.zcml
  src/bika/lims/permissions.py
  src/bika/lims/permissions.zcml
  src/senaite/core/api/catalog.py
  src/senaite/core/catalog/report_catalog.py
  src/senaite/core/permissions/__init__.py
  src/senaite/core/permissions/configure.zcml
  src/senaite/core/permissions/sample/__init__.py
  src/senaite/core/permissions/sample/configure.zcml
  src/senaite/core/permissions/sample/permissions.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_05_000.py
  src/senaite/core/upgrade/v02_05_000.zcml
Labels: Bug, Enhancement, Cleanup

#2284 Fix the email sent on sample rejection is not text/html
  CHANGES.rst
  src/bika/lims/utils/analysisrequest.py
  src/senaite/core/tests/doctests/API_mail.rst
Labels: Bug

#2285 Fix string results with html characters not displayed after submit
  CHANGES.rst
  src/bika/lims/content/abstractanalysis.py
  src/senaite/core/tests/doctests/StringResult.rst
Labels: Bug
