Repository senaite/senaite.core, pull requests merged in 2023-10, with the labels that each got.

#2401 Fix OverflowError when calculating datetime.min date for left-hand TZs
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/senaite/core/api/dtime.py
  src/senaite/core/browser/fields/datetime.py
  src/senaite/core/tests/doctests/API_datetime.rst
Labels: Bug

#2402 Fix user cannot enter future date for DateSampled when sampling workflow is enabled
  CHANGES.rst
  src/bika/lims/content/analysisrequest.py
Labels: Bug

#2391 Universal ASTM JSON Consumer and Importer
  src/senaite/core/adapters/configure.zcml
  src/senaite/core/astm/README.md
  src/senaite/core/astm/__init__.py
  src/senaite/core/astm/configure.zcml
  src/senaite/core/astm/consumer.py
  src/senaite/core/astm/importer.py
  src/senaite/core/configure.zcml
  src/senaite/core/interfaces/__init__.py
Labels: Enhancement

#2400 Add Transposed Multi Results Form
  CHANGES.rst
  src/bika/lims/browser/worksheet/views/analyses.py
  src/senaite/core/browser/modals/configure.zcml
  src/senaite/core/browser/samples/configure.zcml
  src/senaite/core/browser/samples/multi_results_classic.py
  src/senaite/core/browser/samples/multi_results_transposed.py
  src/senaite/core/browser/samples/templates/multi_results.pt
Labels: Addition, Enhancement

#2407 Fix analyses sort order in Transposed Multi Results Form
  CHANGES.rst
  src/senaite/core/browser/samples/multi_results_transposed.py
Labels: Bug

#2410 Fix order of choices for interims on data entry is not preserved
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
Labels: Bug

#2409 Fix empty results get interpreted as 0.0 by 2-Dimensional-CSV importer
  src/senaite/core/exportimport/instruments/generic/samples/2dimension.csv
  src/senaite/core/exportimport/instruments/generic/two_dimension.py
  src/senaite/core/tests/files/instruments/generic.two_dimension.csv
Labels: Bug, P2: Very Important

#2413 Fix select custom value for queryselect widget
  CHANGES.rst
  src/senaite/core/browser/static/bundles/senaite.core.widgets.js
  src/senaite/core/browser/static/bundles/senaite.core.widgets.js.map
  webpack/app/widgets/components/SearchResults.js
  webpack/app/widgets/queryselect/widget.js
Labels: Bug
