Repository senaite/senaite.core, pull requests merged in 2023-09, with the labels that each got.

#2369 Allow to set a custom comment for when a result is out of range
  CHANGES.rst
  src/bika/lims/browser/fields/resultrangefield.py
  src/bika/lims/browser/widgets/analysisspecificationwidget.py
  src/bika/lims/content/analysisspec.py
  src/senaite/core/browser/static/bundles/senaite.core.css
  src/senaite/core/browser/static/bundles/senaite.core.css.map
  webpack/app/scss/forms.scss
Labels: Enhancement

#2368 Drop usage of portal_catalog tool
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/bika/lims/api/snapshot.py
  src/bika/lims/browser/__init__.py
  src/bika/lims/browser/department/ajax.py
  src/bika/lims/browser/fields/uidreferencefield.py
  src/bika/lims/browser/instrument.py
  src/bika/lims/browser/pricelist.py
  src/bika/lims/jsonapi/create.py
  src/bika/lims/jsonapi/read.py
  src/bika/lims/jsonapi/remove.py
  src/bika/lims/subscribers/pricelist.py
  src/bika/lims/vocabularies/__init__.py
  src/senaite/core/adapters/referencewidget/vocabularies.py
  src/senaite/core/browser/widgets/referencewidget.py
  src/senaite/core/exportimport/instruments/resultsimport.py
  src/senaite/core/exportimport/setupdata/__init__.py
  src/senaite/core/patches/catalog.py
  src/senaite/core/patches/configure.zcml
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/schema/README.rst
  src/senaite/core/setuphandlers.py
  src/senaite/core/tests/doctests/API.rst
  src/senaite/core/upgrade/utils.py
  src/senaite/core/upgrade/v02_05_000.py
  src/senaite/core/upgrade/v02_05_000.zcml
  src/senaite/core/z3cform/widgets/queryselect/README.md
Labels: Enhancement, Cleanup

#2372 Generate unique ID for DX types on object creation
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/bika/lims/configure.zcml
  src/bika/lims/idserver.py
  src/bika/lims/interfaces/__init__.py
  src/bika/lims/profiles/default/componentregistry.xml
  src/bika/lims/profiles/default/types/DynamicAnalysisSpecs.xml
  src/bika/lims/subscribers/configure.zcml
  src/bika/lims/subscribers/objectadded.py
  src/bika/lims/utils/analysisrequest.py
  src/senaite/core/behaviors/configure.zcml
  src/senaite/core/browser/controlpanel/labels.py
  src/senaite/core/browser/dexterity/add.py
  src/senaite/core/catalog/catalog_multiplex_processor.py
  src/senaite/core/configure.zcml
  src/senaite/core/idserver/__init__.py
  src/senaite/core/idserver/alphanumber.py
  src/senaite/core/idserver/configure.zcml
  src/senaite/core/idserver/idchooser.py
  src/senaite/core/idserver/idserver.py
  src/senaite/core/interfaces/__init__.py
  src/senaite/core/patches/catalog.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/profiles/default/types/Labels.xml
  src/senaite/core/profiles/default/types/SampleContainers.xml
  src/senaite/core/tests/doctests/API.rst
  src/senaite/core/tests/doctests/Alphanumber.rst
  src/senaite/core/tests/doctests/IDServer.rst
  src/senaite/core/tests/doctests/InstrumentCalibrationCertificationAndValidation.rst
  src/senaite/core/upgrade/v02_05_000.py
  src/senaite/core/upgrade/v02_05_000.zcml
Labels: Enhancement, PR: Not Ready, Performance

#2374 Keep Subject index in portal_catalog
  src/senaite/core/setuphandlers.py
Labels: Bug

#2377 Fix imports for moved idserver module
  CHANGES.rst
  src/bika/lims/content/analysiscategory.py
  src/bika/lims/content/analysisprofile.py
  src/bika/lims/content/analysisservice.py
  src/bika/lims/content/analysisspec.py
  src/bika/lims/content/arreport.py
  src/bika/lims/content/artemplate.py
  src/bika/lims/content/attachment.py
  src/bika/lims/content/attachmenttype.py
  src/bika/lims/content/autoimportlog.py
  src/bika/lims/content/batch.py
  src/bika/lims/content/batchlabel.py
  src/bika/lims/content/calculation.py
  src/bika/lims/content/client.py
  src/bika/lims/content/contact.py
  src/bika/lims/content/container.py
  src/bika/lims/content/containertype.py
  src/bika/lims/content/department.py
  src/bika/lims/content/identifiertype.py
  src/bika/lims/content/instrument.py
  src/bika/lims/content/instrumentcalibration.py
  src/bika/lims/content/instrumentcertification.py
  src/bika/lims/content/instrumentlocation.py
  src/bika/lims/content/instrumentmaintenancetask.py
  src/bika/lims/content/instrumentscheduledtask.py
  src/bika/lims/content/instrumenttype.py
  src/bika/lims/content/instrumentvalidation.py
  src/bika/lims/content/invoice.py
  src/bika/lims/content/labcontact.py
  src/bika/lims/content/labproduct.py
  src/bika/lims/content/manufacturer.py
  src/bika/lims/content/method.py
  src/bika/lims/content/multifile.py
  src/bika/lims/content/preservation.py
  src/bika/lims/content/pricelist.py
  src/bika/lims/content/referencedefinition.py
  src/bika/lims/content/referencesample.py
  src/bika/lims/content/samplecondition.py
  src/bika/lims/content/samplematrix.py
  src/bika/lims/content/samplepoint.py
  src/bika/lims/content/sampletype.py
  src/bika/lims/content/samplingdeviation.py
  src/bika/lims/content/storagelocation.py
  src/bika/lims/content/subgroup.py
  src/bika/lims/content/supplier.py
  src/bika/lims/content/suppliercontact.py
  src/bika/lims/content/worksheet.py
  src/bika/lims/content/worksheettemplate.py
  src/bika/lims/jsonapi/create.py
  src/senaite/core/exportimport/instruments/resultsimport.py
  src/senaite/core/exportimport/setupdata/__init__.py
Labels: Cleanup

#2382 Fix missing fields in client edit mode and listing
  CHANGES.rst
  src/bika/lims/adapters/configure.zcml
  src/bika/lims/adapters/widgetvisibility.py
  src/bika/lims/browser/clientfolder.py
  src/senaite/core/tests/doctests/ShowPrices.rst
Labels: Bug

#2379 Add listing adapter for sample workflow "receive" transition
  CHANGES.rst
  src/senaite/core/browser/configure.zcml
  src/senaite/core/browser/listing/__init__.py
  src/senaite/core/browser/listing/configure.zcml
  src/senaite/core/browser/listing/workflow.py
Labels: Addition, Enhancement

#2384 Fix reference widget lookups
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/bika/lims/content/abstractbaseanalysis.py
  src/bika/lims/content/analysiscategory.py
  src/bika/lims/content/analysisrequest.py
  src/bika/lims/content/analysisspec.py
  src/bika/lims/content/arreport.py
  src/bika/lims/content/artemplate.py
  src/bika/lims/content/attachment.py
  src/bika/lims/content/autoimportlog.py
  src/bika/lims/content/batch.py
  src/bika/lims/content/bikasetup.py
  src/bika/lims/content/calculation.py
  src/bika/lims/content/client.py
  src/bika/lims/content/contact.py
  src/bika/lims/content/container.py
  src/bika/lims/content/containertype.py
  src/bika/lims/content/department.py
  src/bika/lims/content/instrument.py
  src/bika/lims/content/instrumentcalibration.py
  src/bika/lims/content/instrumentcertification.py
  src/bika/lims/content/instrumentscheduledtask.py
  src/bika/lims/content/instrumentvalidation.py
  src/bika/lims/content/labcontact.py
  src/bika/lims/content/laboratory.py
  src/bika/lims/content/method.py
  src/bika/lims/content/referencesample.py
  src/bika/lims/content/samplematrix.py
  src/bika/lims/content/samplepoint.py
  src/bika/lims/content/sampletype.py
  src/bika/lims/content/worksheettemplate.py
  src/senaite/core/adapters/referencewidget/dataproviders.py
  src/senaite/core/browser/form/adapters/labcontact.py
  src/senaite/core/browser/static/bundles/senaite.core.js
  src/senaite/core/browser/static/bundles/senaite.core.js.map
  src/senaite/core/browser/static/bundles/senaite.core.widgets.js
  src/senaite/core/browser/static/bundles/senaite.core.widgets.js.map
  src/senaite/core/browser/widgets/referencewidget.py
  src/senaite/core/z3cform/widgets/queryselect/widget.py
  src/senaite/core/z3cform/widgets/uidreference/widget.py
  webpack/app/components/editform.js
  webpack/app/widgets/components/SelectedValues.js
  webpack/app/widgets/queryselect/widget.js
Labels: Bug, P2: Very Important, Cleanup

#2388 Fix QC sample IDs are the same accross worksheets
  CHANGES.rst
  src/bika/lims/content/worksheet.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_05_000.py
  src/senaite/core/upgrade/v02_05_000.zcml
Labels: Bug

#2392 Fix display of orphan method instruments
  CHANGES.rst
  src/bika/lims/content/method.py
Labels: Bug

#2393 Allow empty analysis method selection
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
Labels: Bug

#2394 Ajax support for transitions retract and retest
  CHANGES.rst
  src/senaite/core/browser/listing/configure.zcml
  src/senaite/core/browser/listing/workflow/__init__.py
  src/senaite/core/browser/listing/workflow/analysis.py
  src/senaite/core/browser/listing/workflow/sample.py
Labels: Enhancement

#2396 Add after sequential transition event handler
  CHANGES.rst
  src/senaite/core/browser/static/bundles/senaite.core.js
  src/senaite/core/browser/static/bundles/senaite.core.js.map
  webpack/app/senaite.core.js
Labels: Enhancement, Cleanup
