Repository senaite/senaite.core, pull requests merged in 2023-04, with the labels that each got.

#2296 Handle attribute error for unsupported label types
  src/senaite/core/api/label.py
Labels: Bug

#2297 Fix wrong characters on sample invalidation emails
  CHANGES.rst
  src/bika/lims/browser/workflow/analysisrequest.py
  src/bika/lims/utils/__init__.py
Labels: Bug

#2299 Fix KeyError: 'prefs_main_template' after installation
  CHANGES.rst
  src/bika/lims/profiles/default/skins.xml
Labels: Bug

#2300 Re-add searchable text provider adapters for sample catalog listing_searchable_text index
  CHANGES.rst
  src/senaite/core/catalog/indexer/sample.py
Labels: Regression

#2301 Use client groups for local role sharing
  CHANGES.rst
  src/bika/lims/browser/templates/login_details.pt
  src/bika/lims/content/client.py
  src/bika/lims/content/contact.py
  src/bika/lims/profiles/default/types/Client.xml
  src/senaite/core/adapters/configure.zcml
  src/senaite/core/adapters/localroles.py
  src/senaite/core/browser/configure.zcml
  src/senaite/core/browser/sharing/__init__.py
  src/senaite/core/browser/sharing/configure.zcml
  src/senaite/core/browser/sharing/sharing.py
  src/senaite/core/browser/sharing/templates/client_sharing.pt
  src/senaite/core/configure.zcml
  src/senaite/core/permissions/__init__.py
  src/senaite/core/permissions/configure.zcml
  src/senaite/core/permissions/localroles.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/profiles/default/registry.xml
  src/senaite/core/registry/schema.py
  src/senaite/core/subscribers/__init__.py
  src/senaite/core/subscribers/client.py
  src/senaite/core/subscribers/configure.zcml
  src/senaite/core/tests/doctests/ContactUser.rst
  src/senaite/core/tests/doctests/Permissions.rst
  src/senaite/core/upgrade/v02_05_000.py
  src/senaite/core/upgrade/v02_05_000.zcml
Labels: Addition, Enhancement
