Repository senaite/senaite.core, pull requests merged in 2024-06, with the labels that each got.

#2570 Use reference widget API in sample add form
  CHANGES.rst
  src/senaite/core/browser/static/bundles/senaite.core.widgets.js
  src/senaite/core/browser/static/bundles/senaite.core.widgets.js.map
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.add.js
  src/senaite/core/browser/static/js/coffee/bika.lims.analysisrequest.add.coffee
  webpack/app/senaite.core.widgets.js
  webpack/app/widgets/queryselect/widget.js
  webpack/app/widgets/renderer.js
Labels: Improvement 🔧, Cleanup 🧹

#2576 Fix analyses and services are re-indexed after modifying category
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/browser/analysisrequest/add2.py
  src/bika/lims/browser/referencesample.py
  src/bika/lims/browser/worksheet/views/add_analyses.py
  src/bika/lims/controlpanel/bika_analysisservices.py
  src/senaite/core/catalog/analysis_catalog.py
  src/senaite/core/catalog/setup_catalog.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/subscribers/analysiscategory.py
  src/senaite/core/subscribers/configure.zcml
  src/senaite/core/upgrade/v02_06_000.py
  src/senaite/core/upgrade/v02_06_000.zcml
Labels: Cleanup 🧹

#2578 Fix setup DX folders are not indexed in `uid_catalog`
  CHANGES.rst
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/profiles/default/types/AnalysisCategories.xml
  src/senaite/core/profiles/default/types/AnalysisProfiles.xml
  src/senaite/core/profiles/default/types/BatchLabels.xml
  src/senaite/core/profiles/default/types/ContainerTypes.xml
  src/senaite/core/profiles/default/types/Departments.xml
  src/senaite/core/profiles/default/types/InstrumentLocations.xml
  src/senaite/core/profiles/default/types/InstrumentTypes.xml
  src/senaite/core/profiles/default/types/InterpretationTemplates.xml
  src/senaite/core/profiles/default/types/Labels.xml
  src/senaite/core/profiles/default/types/Manufacturers.xml
  src/senaite/core/profiles/default/types/SampleConditions.xml
  src/senaite/core/profiles/default/types/SampleContainers.xml
  src/senaite/core/profiles/default/types/SampleMatrices.xml
  src/senaite/core/profiles/default/types/SamplePoints.xml
  src/senaite/core/profiles/default/types/SamplePreservations.xml
  src/senaite/core/profiles/default/types/SampleTemplates.xml
  src/senaite/core/profiles/default/types/Samples.xml
  src/senaite/core/profiles/default/types/SamplingDeviations.xml
  src/senaite/core/profiles/default/types/Setup.xml
  src/senaite/core/profiles/default/types/StorageLocations.xml
  src/senaite/core/profiles/default/types/SubGroups.xml
  src/senaite/core/upgrade/v02_06_000.py
  src/senaite/core/upgrade/v02_06_000.zcml
Labels: Bug 🐞

#2580 Fix instrument import log message when field value is set
  src/senaite/core/exportimport/instruments/importer.py
Labels: Bug 🐞

#2582 Do not override dependent values with empties
  CHANGES.rst
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.add.js
  src/senaite/core/browser/static/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Bug 🐞
