Repository senaite/senaite.core, pull requests merged in 2024-05, with the labels that each got.

#2543 Fix AttributeError for Instrument Adapters
  CHANGES.rst
  src/senaite/core/browser/form/adapters/data_import.py
Labels: Bug 🐞

#2539 Add User Profile / Password Reset
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/bika/lims/content/contact.py
  src/bika/lims/content/person.py
  src/senaite/core/browser/configure.zcml
  src/senaite/core/browser/user/__init__.py
  src/senaite/core/browser/user/configure.zcml
  src/senaite/core/browser/user/passwordpanel.py
  src/senaite/core/browser/user/personalpreferences.py
  src/senaite/core/browser/user/register.py
  src/senaite/core/browser/user/templates/account-configlet.pt
  src/senaite/core/browser/user/templates/account-panel.pt
  src/senaite/core/browser/user/templates/newuser_form.pt
  src/senaite/core/browser/user/userdatapanel.py
  src/senaite/core/browser/usergroup/configure.zcml
  src/senaite/core/browser/users/configure.zcml
  src/senaite/core/browser/viewlets/templates/toolbar.pt
  src/senaite/core/profiles/default/actions.xml
  src/senaite/core/profiles/default/controlpanel.xml
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/profiles/default/userschema.xml
  src/senaite/core/profiles/default/workflows/senaite_clientcontact_workflow/definition.xml
  src/senaite/core/profiles/default/workflows/senaite_labcontact_workflow/definition.xml
  src/senaite/core/subscribers/configure.zcml
  src/senaite/core/subscribers/contact.py
  src/senaite/core/tests/doctests/API.rst
  src/senaite/core/tests/doctests/Permissions.rst
  src/senaite/core/upgrade/v02_06_000.py
  src/senaite/core/upgrade/v02_06_000.zcml
  src/senaite/core/workflow/__init__.py
  src/senaite/core/z3cform/widgets/basewidget.py
Labels: Addition ➕

#2546 Add `move_object` function in the API
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/senaite/core/tests/doctests/API.rst
Labels: Addition ➕

#2547 Add `get_user_email` function in the `api`
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/bika/lims/browser/__init__.py
  src/bika/lims/content/analysisrequest.py
  src/bika/lims/utils/__init__.py
  src/senaite/core/catalog/sample_catalog.py
  src/senaite/core/tests/doctests/API.rst
Labels: Improvement 🔧, Cleanup 🧹

#2548 Remove `SamplerFullName` from sample and metadata
  CHANGES.rst
  src/bika/lims/content/analysisrequest.py
  src/senaite/core/browser/samples/view.py
  src/senaite/core/catalog/sample_catalog.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_06_000.py
  src/senaite/core/upgrade/v02_06_000.zcml
Labels: Cleanup 🧹

#2541 Allow to change the "From" address for sample report outgoing emails
  CHANGES.rst
  src/bika/lims/browser/publish/emailview.py
  src/bika/lims/content/bikasetup.py
  src/senaite/core/content/senaitesetup.py
Labels: Addition ➕

#2549 Fix contact fullname is not updated in samples listing after edition
  CHANGES.rst
  src/bika/lims/content/analysisrequest.py
  src/senaite/core/browser/samples/view.py
  src/senaite/core/catalog/sample_catalog.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_06_000.py
  src/senaite/core/upgrade/v02_06_000.zcml
Labels: Bug 🐞

#2558 Fix ValueError when upgrading from <=2614 to >=2617
  CHANGES.rst
  src/senaite/core/upgrade/v02_06_000.py
Labels: Bug 🐞, P0: Critical

#2559 Fix line breaks are not displayed for text-like results
  CHANGES.rst
  src/bika/lims/content/abstractanalysis.py
Labels: Bug 🐞

#2560 Fix no available profiles in add form after sample type and/or client change
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
Labels: Bug 🐞, P0: Critical

#2555 Instrument Results Importer/Parser improvements and fixtures
  CHANGES.rst
  src/bika/lims/content/instrument.py
  src/senaite/core/exportimport/auto_import_results.py
  src/senaite/core/exportimport/dataimport.py
  src/senaite/core/exportimport/import.pt
  src/senaite/core/exportimport/import_results.pt
  src/senaite/core/exportimport/instruments/README.md
  src/senaite/core/exportimport/instruments/__init__.py
  src/senaite/core/exportimport/instruments/generic/two_dimension.py
  src/senaite/core/exportimport/instruments/importer.py
  src/senaite/core/exportimport/instruments/instrument.pt
  src/senaite/core/exportimport/instruments/instrument.py
  src/senaite/core/exportimport/instruments/logger.py
  src/senaite/core/exportimport/instruments/myself/__init__.py
  src/senaite/core/exportimport/instruments/myself/myinstrument/__init__.py
  src/senaite/core/exportimport/instruments/myself/myinstrument/samples/sample.csv
  src/senaite/core/exportimport/instruments/nuclisens/easyq.py
  src/senaite/core/exportimport/instruments/parser.py
  src/senaite/core/exportimport/instruments/resultsimport.py
  src/senaite/core/exportimport/instruments/utils.py
  src/senaite/core/tests/doctests/AutoImportResults.rst
  src/senaite/core/tests/doctests/InstrumentResultsImport.rst
  src/senaite/core/tests/doctests/InstrumentsImportInterface.rst
Labels: Improvement 🔧, Cleanup 🧹, Python 3

#2562 Increased field size and allowed input length for instrument import folder path
  CHANGES.rst
  src/bika/lims/content/instrument.py
Labels: Improvement 🔧, Cleanup 🧹

#2565 Added GPSCoordinates widget and field
  CHANGES.rst
  src/senaite/core/api/geo.py
  src/senaite/core/browser/static/assets/icons/gpslocation.svg
  src/senaite/core/schema/__init__.py
  src/senaite/core/schema/gpscoordinatesfield.py
  src/senaite/core/schema/gpscoordinatesfield.txt
  src/senaite/core/schema/interfaces.py
  src/senaite/core/tests/doctests/API_geo.rst
  src/senaite/core/z3cform/interfaces.py
  src/senaite/core/z3cform/widgets/configure.zcml
  src/senaite/core/z3cform/widgets/gpscoordinates/__init__.py
  src/senaite/core/z3cform/widgets/gpscoordinates/configure.zcml
  src/senaite/core/z3cform/widgets/gpscoordinates/display.pt
  src/senaite/core/z3cform/widgets/gpscoordinates/hidden.pt
  src/senaite/core/z3cform/widgets/gpscoordinates/input.pt
  src/senaite/core/z3cform/widgets/gpscoordinates/widget.py
Labels: Addition ➕

#2564 Flush dependent fields in sample add form only if the current value is not allowed
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
  src/bika/lims/browser/analysisrequest/templates/ar_add2.pt
  src/senaite/core/browser/static/bundles/senaite.core.js
  src/senaite/core/browser/static/bundles/senaite.core.js.map
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.add.js
  src/senaite/core/browser/static/js/coffee/bika.lims.analysisrequest.add.coffee
  webpack/app/components/coffee/site.coffee
  webpack/app/components/site.js
Labels: Improvement 🔧

#2566 Migrate SamplePoint Latitude and Longitude fields to Location (GPSCoordinates)
  CHANGES.rst
  src/senaite/core/api/geo.py
  src/senaite/core/content/samplepoint.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/schema/gpscoordinatesfield.py
  src/senaite/core/tests/doctests/API_geo.rst
  src/senaite/core/upgrade/v02_06_000.py
  src/senaite/core/upgrade/v02_06_000.zcml
Labels: Improvement 🔧, Cleanup 🧹
