Repository senaite/senaite.core, pull requests merged in 2024-04, with the labels that each got.

#2522 Fix user who retest is not considered a verifier
  CHANGES.rst
  src/bika/lims/content/abstractanalysis.py
  src/senaite/core/tests/doctests/WorkflowAnalysisRetest.rst
Labels: Bug 🐞

#2525 Fix UnicodeDecodeError during Department DX Migration
  CHANGES.rst
  src/senaite/core/content/department.py
Labels: Bug 🐞

#2528 Fix relative paths of section icons in sample view
  CHANGES.rst
  src/senaite/core/browser/viewlets/templates/remarks.pt
  src/senaite/core/browser/viewlets/templates/resultsinterpretation.pt
  src/senaite/core/browser/viewlets/templates/sampleanalyses.pt
Labels: Improvement 🔧

#2526 Highlight edit tabs with errors in red
  CHANGES.rst
  src/senaite/core/skins/senaite_templates/edit_macros.pt
Labels: Bug 🐞, P4: Nice To Have

#2523 Fix getting ResultsRange field
  CHANGES.rst
  src/bika/lims/adapters/dynamicresultsrange.py
  src/bika/lims/browser/fields/resultrangefield.py
Labels: Bug 🐞

#2527 Fix clients groups are displayed on labcontact's user creation form
  CHANGES.rst
  src/bika/lims/browser/contact.py
  src/bika/lims/content/client.py
  src/senaite/core/catalog/client_catalog.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_06_000.py
  src/senaite/core/upgrade/v02_06_000.zcml
Labels: Improvement 🔧

#2524 Allow to edit the result capture date
  CHANGES.rst
  src/bika/lims/browser/analyses/view.py
  src/bika/lims/browser/worksheet/views/analyses.py
  src/bika/lims/content/abstractanalysis.py
  src/bika/lims/content/bikasetup.py
  src/senaite/core/browser/static/bundles/senaite.core.css
  src/senaite/core/browser/static/bundles/senaite.core.css.map
  src/senaite/core/content/senaitesetup.py
  webpack/app/scss/listings.scss
  webpack/app/scss/senaite.core.scss
Labels: Improvement 🔧

#2531 Fix sample points are not filtered by type on sample creation or edition
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
  src/bika/lims/content/analysisrequest.py
  src/bika/lims/content/samplepoint.py
  src/senaite/core/catalog/indexer/configure.zcml
  src/senaite/core/catalog/indexer/samplepoint.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_06_000.zcml
Labels: Bug 🐞

#2532 Fix disappear of the hidden mark for retested analyses
  CHANGES.rst
  src/bika/lims/utils/analysis.py
Labels: Bug 🐞

#2534 Fix client-specific sample templates are displayed under setup
  CHANGES.rst
  src/senaite/core/browser/clients/client/sampletemplates/view.py
  src/senaite/core/browser/controlpanel/sampletemplates/view.py
Labels: Bug 🐞

#2535 Fix client-specific profiles are displayed under setup
  CHANGES.rst
  src/bika/lims/browser/client/__init__.py
  src/bika/lims/browser/client/configure.zcml
  src/senaite/core/browser/clients/client/analysisprofiles/__init__.py
  src/senaite/core/browser/clients/client/analysisprofiles/configure.zcml
  src/senaite/core/browser/clients/client/analysisprofiles/view.py
  src/senaite/core/browser/clients/client/configure.zcml
  src/senaite/core/browser/controlpanel/analysisprofiles/view.py
Labels: Bug 🐞

#2536 Fix counts from control-panel includes client-specific items
  CHANGES.rst
  src/senaite/core/browser/controlpanel/setupview.py
Labels: Bug 🐞
