Repository senaite/senaite.core, pull requests merged in 2024-02, with the labels that each got.

#2482 Added DurationField and DurationWidget for Dexterity types
  CHANGES.rst
  src/senaite/core/schema/__init__.py
  src/senaite/core/schema/durationfield.py
  src/senaite/core/schema/durationfield.txt
  src/senaite/core/schema/interfaces.py
  src/senaite/core/z3cform/interfaces.py
  src/senaite/core/z3cform/widgets/configure.zcml
  src/senaite/core/z3cform/widgets/duration/__init__.py
  src/senaite/core/z3cform/widgets/duration/configure.zcml
  src/senaite/core/z3cform/widgets/duration/display.pt
  src/senaite/core/z3cform/widgets/duration/hidden.pt
  src/senaite/core/z3cform/widgets/duration/input.pt
  src/senaite/core/z3cform/widgets/duration/widget.py
  src/senaite/core/z3cform/widgets/durationwidget.txt
Labels: Content Migration ♻️

#2484 Disable CSRF protection in SENAITE
  CHANGES.rst
  src/senaite/core/interfaces/__init__.py
Labels: Improvement 🔧

#2486 Fix Traceback on "Manage analyses" when dynamic specs assigned
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/manage_analyses.py
Labels: Bug 🐞

#2487 Fix ValueError when creating new Dexterity contents
  CHANGES.rst
  src/bika/lims/api/snapshot.py
Labels: Bug 🐞

#2485 More informative progress of the sample analyses states
  CHANGES.rst
  src/senaite/core/browser/samples/view.py
  src/senaite/core/browser/static/bundles/senaite.core.css
  src/senaite/core/browser/static/bundles/senaite.core.css.map
  webpack/app/scss/senaite.core.scss
Labels: Improvement 🔧

#2490 Fix TypeError when creating a DX object that once was from AT type
  CHANGES.rst
  src/senaite/core/browser/controlpanel/sampleconditions/view.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_06_000.py
  src/senaite/core/upgrade/v02_06_000.zcml
Labels: Content Migration ♻️

#2491 Add setting to show/hide the laboratory name in login page
  CHANGES.rst
  src/bika/lims/content/bikasetup.py
  src/senaite/core/browser/login/login.py
  src/senaite/core/browser/login/templates/login.pt
  src/senaite/core/content/senaitesetup.py
Labels: Addition ➕

#2493 Add listing widget for Dexterity records field
  CHANGES.rst
  src/senaite/core/schema/configure.zcml
  src/senaite/core/schema/traversal.py
  src/senaite/core/z3cform/interfaces.py
  src/senaite/core/z3cform/widgets/configure.zcml
  src/senaite/core/z3cform/widgets/listing.txt
  src/senaite/core/z3cform/widgets/listing/__init__.py
  src/senaite/core/z3cform/widgets/listing/configure.zcml
  src/senaite/core/z3cform/widgets/listing/display.pt
  src/senaite/core/z3cform/widgets/listing/hidden.pt
  src/senaite/core/z3cform/widgets/listing/input.pt
  src/senaite/core/z3cform/widgets/listing/view.py
  src/senaite/core/z3cform/widgets/listing/widget.py
Labels: Addition ➕

#2494 Cleanup UID catalog and remove orphan temporary objects
  CHANGES.rst
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/setuphandlers.py
  src/senaite/core/upgrade/v02_06_000.py
  src/senaite/core/upgrade/v02_06_000.zcml
Labels: Cleanup 🧹

#2495 Fix dynamic analysisspecs are not linked to keywords containing only numbers
  CHANGES.rst
  src/bika/lims/content/dynamic_analysisspec.py
Labels: Bug 🐞

#2496 Fix non existing department ID is rendered as link in listing
  CHANGES.rst
  src/senaite/core/browser/controlpanel/departments/view.py
  src/senaite/core/content/department.py
Labels: Bug 🐞

#2498 Fix services widget not found when creating new profiles
  CHANGES.rst
  src/senaite/core/browser/widgets/analysisprofileswidget.py
  src/senaite/core/schema/traversal.py
  src/senaite/core/z3cform/widgets/listing.txt
  src/senaite/core/z3cform/widgets/listing/view.py
  src/senaite/core/z3cform/widgets/listing/widget.py
Labels: Bug 🐞

#2503 Fix traceback on upgrade step 2610 while cleaning up uid_catalog
  CHANGES.rst
  src/senaite/core/upgrade/v02_06_000.py
Labels: Bug 🐞

#2504 Fix subfield_sizes have no effect when rendering RecordField
  CHANGES.rst
  src/senaite/core/browser/fields/record.py
  src/senaite/core/browser/fields/records.py
  src/senaite/core/skins/senaite_templates/senaite_widgets/recordswidget.pt
Labels: Bug 🐞

#2505 Fix UnicodeDecodeError when migrating Analysis Profiles
  CHANGES.rst
  src/senaite/core/content/analysisprofile.py
  src/senaite/core/upgrade/v02_06_000.py
Labels: Bug 🐞, P2: Very Important

#2506 Migrate Client located Analysis Profiles to DX
  src/senaite/core/migration/migrator.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_06_000.py
  src/senaite/core/upgrade/v02_06_000.zcml
Labels: P2: Very Important, Content Migration ♻️

#2509 Allow analysis profiles to be filtered by sample type
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
  src/bika/lims/content/analysisrequest.py
  src/senaite/core/browser/controlpanel/analysisprofiles/view.py
  src/senaite/core/catalog/indexer/analysisprofile.py
  src/senaite/core/catalog/indexer/configure.zcml
  src/senaite/core/content/analysisprofile.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_06_000.py
  src/senaite/core/upgrade/v02_06_000.zcml
Labels: Addition ➕

#2508 Fix specification values for hide min/max not stored on save
  CHANGES.rst
  src/bika/lims/browser/widgets/analysisspecificationwidget.py
Labels: Bug 🐞

#2510 Fix Add action of the Client located Analysis Profiles Listing
  CHANGES.rst
  src/bika/lims/browser/client/views/analysisprofiles.py
  src/senaite/core/browser/form/adapters/configure.zcml
  src/senaite/core/browser/static/bundles/senaite.core.js
  src/senaite/core/browser/static/bundles/senaite.core.js.map
  webpack/app/components/editform.js
Labels: Bug 🐞, P2: Very Important
