Repository senaite/senaite.core, pull requests merged in 2024-01, with the labels that each got.

#2462 Fix manually deselected references in sample add form can not be set anymore
  CHANGES.rst
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.add.js
  src/senaite/core/browser/static/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Bug 🐞

#2411 Multiselection with duplicates support for interim fields
  CHANGES.rst
  src/bika/lims/browser/fields/interimfieldsfield.py
Labels: Addition ➕

#2417 Use dtime.to_DT instead of api.to_date
  CHANGES.rst
  src/bika/lims/browser/auditlog.py
  src/senaite/core/catalog/indexer/auditlog.py
  src/senaite/core/exportimport/instruments/resultsimport.py
Labels: Cleanup 🧹

#2434 Add string support for interim fields
  CHANGES.rst
  src/bika/lims/browser/fields/interimfieldsfield.py
  src/bika/lims/validators.py
Labels: Addition ➕

#2435 Add datetime support interim fields
  CHANGES.rst
  src/bika/lims/browser/fields/interimfieldsfield.py
Labels: Addition ➕

#2442 Show partitions initially collapsed in partition preview mode
  CHANGES.rst
  src/senaite/core/browser/samples/templates/partition_magic.pt
Labels: Improvement 🔧

#2458 Allow portal_type as a parameter for api.get_icon function
  CHANGES.rst
  src/bika/lims/api/__init__.py
  src/senaite/core/tests/doctests/API.rst
Labels: Improvement 🔧

#2464 Fix contact assigned to multiple clients cannot see samples from other clients
  CHANGES.rst
  src/senaite/core/browser/samples/view.py
Labels: Bug 🐞

#2467 Support for prioritized specs when using dynamic specifications
  CHANGES.rst
  src/bika/lims/adapters/dynamicresultsrange.py
  src/senaite/core/tests/doctests/DynamicAnalysisSpec.rst
Labels: Improvement 🔧

#2470 Fix min/max shifted on negative result and % error
  CHANGES.rst
  src/bika/lims/browser/widgets/referenceresultswidget.py
Labels: Bug 🐞

#2468 Make the prepublish guard to rely on interfaces instead of statuses
  CHANGES.rst
  src/bika/lims/workflow/analysisrequest/guards.py
Labels: Cleanup 🧹

#2469 Rename the permission "Reject" to "senaite.core: Transition: Reject Analysis"
  CHANGES.rst
  src/senaite/core/permissions/__init__.py
  src/senaite/core/permissions/analysis/__init__.py
  src/senaite/core/permissions/analysis/configure.zcml
  src/senaite/core/permissions/analysis/permissions.py
  src/senaite/core/permissions/configure.zcml
  src/senaite/core/profiles/default/rolemap.xml
  src/senaite/core/profiles/default/workflows/senaite_analysis_workflow/definition.xml
  src/senaite/core/tests/doctests/WorkflowAnalysisReject.rst
  src/senaite/core/upgrade/v02_06_000.py
  src/senaite/core/upgrade/v02_06_000.zcml
Labels: Improvement 🔧, Cleanup 🧹

#2472 Fix "Reject" permission from analysis workflow is not updated
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/upgrade/v02_06_000.py
Labels: Bug 🐞
