Repository senaite/senaite.core, pull requests merged in 2024-10, with the labels that each got.

#2623 Fix inactive services are added via profile on sample creation or edition
  CHANGES.rst
  src/bika/lims/content/analysisservice.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/tests/doctests/AnalysisServiceInactivation.rst
  src/senaite/core/upgrade/v02_06_000.py
  src/senaite/core/upgrade/v02_06_000.zcml
Labels: Bug 🐞

#2625 Fix sizing of listing widgets
  CHANGES.rst
  src/senaite/core/browser/dexterity/templates/widget.pt
Labels: Bug 🐞

#2626 Change to new instrument imports that were introduced with #2555
  CHANGES.rst
  src/senaite/core/exportimport/instruments/__init__.py
  src/senaite/core/exportimport/instruments/abaxis/vetscan/__init__.py
  src/senaite/core/exportimport/instruments/abbott/m2000rt/m2000rt.py
  src/senaite/core/exportimport/instruments/alere/pima/__init__.py
  src/senaite/core/exportimport/instruments/beckmancoulter/access/__init__.py
  src/senaite/core/exportimport/instruments/biodrop/ulite/__init__.py
  src/senaite/core/exportimport/instruments/cobasintegra/model_400_plus/__init__.py
  src/senaite/core/exportimport/instruments/eltra/cs/__init__.py
  src/senaite/core/exportimport/instruments/facscalibur/calibur/__init__.py
  src/senaite/core/exportimport/instruments/foss/fiastar/__init__.py
  src/senaite/core/exportimport/instruments/foss/winescan/__init__.py
  src/senaite/core/exportimport/instruments/generic/two_dimension.py
  src/senaite/core/exportimport/instruments/genexpert/genexpert.py
  src/senaite/core/exportimport/instruments/horiba/jobinyvon/importer.py
  src/senaite/core/exportimport/instruments/horiba/jobinyvon/parser.py
  src/senaite/core/exportimport/instruments/lachat/quickchem.py
  src/senaite/core/exportimport/instruments/lifetechnologies/qubit/__init__.py
  src/senaite/core/exportimport/instruments/metler/toledo/dl55.py
  src/senaite/core/exportimport/instruments/nuclisens/easyq.py
  src/senaite/core/exportimport/instruments/panalytical/omnia/__init__.py
  src/senaite/core/exportimport/instruments/rigaku/supermini/__init__.py
  src/senaite/core/exportimport/instruments/rochecobas/taqman/model48.py
  src/senaite/core/exportimport/instruments/rochecobas/taqman/model96.py
  src/senaite/core/exportimport/instruments/sealanalytical/aq2/__init__.py
  src/senaite/core/exportimport/instruments/shimadzu/gcms/qp2010se.py
  src/senaite/core/exportimport/instruments/shimadzu/gcms/tq8030.py
  src/senaite/core/exportimport/instruments/shimadzu/icpe/multitype.py
  src/senaite/core/exportimport/instruments/shimadzu/nexera/LC2040C.py
  src/senaite/core/exportimport/instruments/shimadzu/nexera/LCMS8050.py
  src/senaite/core/exportimport/instruments/sysmex/xs/__init__.py
  src/senaite/core/exportimport/instruments/sysmex/xt/__init__.py
  src/senaite/core/exportimport/instruments/sysmex/xt/i1800.py
  src/senaite/core/exportimport/instruments/tescan/tima/__init__.py
  src/senaite/core/exportimport/instruments/thermoscientific/arena/__init__.py
  src/senaite/core/exportimport/instruments/thermoscientific/gallery/__init__.py
  src/senaite/core/exportimport/instruments/thermoscientific/multiskan/__init__.py
  src/senaite/core/exportimport/instruments/varian/vistapro/icp.py
Labels: Cleanup 🧹

#2627 Skip workflow transition for temporary analyses
  CHANGES.rst
  src/bika/lims/subscribers/analysis.py
Labels: Improvement 🔧

#2633 Fix DateTimeError when using API's to_DT and to_dt functions
  CHANGES.rst
  src/senaite/core/api/dtime.py
  src/senaite/core/tests/doctests/API_datetime.rst
Labels: Bug 🐞

#2634 Pin et-xmlfile to a Python 2 compatible version
  CHANGES.rst
  setup.py
Labels: dependencies

#2630 Fix references from sample templates are not kept when partitioning
  CHANGES.rst
  src/senaite/core/browser/samples/partition_magic.py
  src/senaite/core/content/sampletemplate.py
Labels: Bug 🐞
