Repository senaite/senaite.core, pull requests merged in 2025-07, with the labels that each got.

#2760 Fix UnicodeDecodeError in instrument importer when processing field values
  CHANGES.rst
  src/senaite/core/exportimport/instruments/importer.py
Labels: Bug 🐞

#2761 Fix AT decimal widget allows commas
  CHANGES.rst
  src/bika/lims/content/abstractbaseanalysis.py
  src/bika/lims/content/bikasetup.py
  src/bika/lims/content/instrumentmaintenancetask.py
  src/senaite/core/browser/static/bundles/legacy.js
  src/senaite/core/browser/static/js/senaite.core.site.js
  src/senaite/core/skins/senaite_templates/senaite_widgets/decimal.pt
Labels: Bug 🐞

#2762 Fix performance of analysis dependency calculations
  CHANGES.rst
  src/bika/lims/api/analysis.py
  src/bika/lims/api/analysisservice.py
  src/bika/lims/browser/analysisrequest/templates/ar_add2.pt
  src/bika/lims/content/abstractroutineanalysis.py
  src/bika/lims/content/analysisrequest.py
  src/bika/lims/content/analysisservice.py
  src/bika/lims/content/calculation.py
  src/bika/lims/content/referenceanalysis.py
  src/bika/lims/workflow/analysisservice/guards.py
  src/senaite/core/browser/static/js/senaite.core.analysisrequest.add.coffee
  src/senaite/core/browser/static/js/senaite.core.analysisrequest.add.js
  src/senaite/core/catalog/analysis_catalog.py
  src/senaite/core/catalog/indexer/configure.zcml
  src/senaite/core/catalog/indexer/routineanalysis.py
  src/senaite/core/datamanagers/content/analysis.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/tests/doctests/API_analysis.rst
  src/senaite/core/tests/doctests/API_analysisservice.rst
  src/senaite/core/tests/doctests/ARAnalysesFieldWithPartitions.rst
  src/senaite/core/tests/doctests/Calculations.rst
  src/senaite/core/tests/doctests/InstrumentResultsImport.rst
  src/senaite/core/upgrade/v02_07_000.py
  src/senaite/core/upgrade/v02_07_000.zcml
Labels: Bug 🐞, Improvement 🔧, P3: Important

#2768 Pin magnitude to a Python 2 compatible version
  CHANGES.rst
  setup.py
Labels: dependencies
