Repository senaite/senaite.core, pull requests merged in 2025-04, with the labels that each got.

#2695 Support for `relativedelta` and `ymd` in `api.dtime`
  CHANGES.rst
  src/senaite/core/api/dtime.py
  src/senaite/core/tests/doctests/API_datetime.rst
Labels: Addition ➕

#2694 Add version wrapper for AT and DX contents
  CHANGES.rst
  src/senaite/core/adapters/configure.zcml
  src/senaite/core/adapters/versionwrapper.py
  src/senaite/core/browser/fields/record.py
  src/senaite/core/interfaces/__init__.py
  src/senaite/core/tests/doctests/VersionWrapper.rst
Labels: Addition ➕

#2707 Fix analyst permission for auto results import
  CHANGES.rst
  src/bika/lims/profiles/default/rolemap.xml
  src/senaite/core/permissions/__init__.py
  src/senaite/core/permissions/configure.zcml
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/profiles/default/rolemap.xml
  src/senaite/core/setuphandlers.py
  src/senaite/core/tests/doctests/AutoImportResults.rst
  src/senaite/core/upgrade/v02_07_000.py
  src/senaite/core/upgrade/v02_07_000.zcml
Labels: Bug 🐞, Cleanup 🧹

#2705 Fix instruments not filtered by method in WS template edit view
  CHANGES.rst
  src/senaite/core/browser/form/adapters/__init__.py
  src/senaite/core/browser/form/adapters/worksheettemplate.py
  src/senaite/core/browser/static/bundles/senaite.core-4ac5732.js
  src/senaite/core/browser/static/bundles/senaite.core-4ac5732.js.map
  webpack/app/components/editform.js
Labels: Bug 🐞

#2708 Fix QR code has no embedded ID
  CHANGES.rst
  src/senaite/core/browser/stickers/templates/stickers/QR_1x14mmx39mm.pt
Labels: Bug 🐞
