Repository senaite/senaite.core, pull requests merged in 2025-06, with the labels that each got.

#2740 Support for analysis conditions in results reports
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/templates/ar_add2.pt
  src/bika/lims/content/abstractroutineanalysis.py
  src/bika/lims/content/analysisservice.py
  src/senaite/core/browser/modals/templates/set_analysis_conditions.pt
Labels: Improvement 🔧

#2755 Remove dependency handling from sample add form
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
  src/bika/lims/browser/analysisrequest/templates/ar_add2.pt
  src/senaite/core/browser/static/js/senaite.core.analysisrequest.add.coffee
  src/senaite/core/browser/static/js/senaite.core.analysisrequest.add.js
Labels: Bug 🐞, Cleanup 🧹

#2756 Fix reindex behavior in setup_core_catalogs
  CHANGES.rst
  src/senaite/core/setuphandlers.py
Labels: Bug 🐞
