Repository senaite/senaite.core, pull requests merged in 2025-03, with the labels that each got.

#2683 Fix temporary batch title
  CHANGES.rst
  src/bika/lims/content/batch.py
Labels: Bug 🐞

#2684 Fix Traceback for unicode titled instruments
  CHANGES.rst
  src/senaite/core/exportimport/dataimport.py
Labels: Bug 🐞

#2685 Fix missing default instrument import template
  CHANGES.rst
  src/senaite/core/browser/form/adapters/data_import.py
  src/senaite/core/exportimport/instruments/templates/default.pt
Labels: Bug 🐞

#2687 Remove legacy and obsolete rejection.js
  CHANGES.rst
  src/senaite/core/browser/static/bundles/legacy.js
  src/senaite/core/browser/static/js/bika.lims.loader.js
  src/senaite/core/browser/static/js/bika.lims.rejection.js
  webpack/webpack.config.js
Labels: Cleanup 🧹

#2682 Added Limit of Quantification (LOQ) for services and analyses
  CHANGES.rst
  src/bika/lims/content/abstractanalysis.py
  src/bika/lims/content/abstractbaseanalysis.py
  src/bika/lims/utils/analysis.py
  src/bika/lims/validators.py
  src/senaite/core/profiles/default/metadata.xml
  src/senaite/core/tests/doctests/Limits.rst
  src/senaite/core/tests/doctests/Uncertainties.rst
  src/senaite/core/tests/test_decimal-sci-notation.py
  src/senaite/core/tests/test_decimalmark-sci-notation.py
  src/senaite/core/tests/test_limitdetections.py
  src/senaite/core/upgrade/v02_06_000.py
  src/senaite/core/upgrade/v02_06_000.zcml
Labels: Addition ➕, Cleanup 🧹

#2689 Fix 2-Dimensional CSV import interface
  CHANGES.rst
  src/senaite/core/exportimport/instruments/generic/two_dimension.py
  src/senaite/core/exportimport/instruments/importer.py
  src/senaite/core/exportimport/instruments/parser.py
  src/senaite/core/tests/doctests/AbbottM2000rtImportInterface.rst
  src/senaite/core/tests/doctests/AutoImportResults.rst
Labels: Bug 🐞, Improvement 🔧

#2691 Fix APIError on upgrade step 2659 (init_loq)
  CHANGES.rst
  src/senaite/core/upgrade/v02_06_000.py
Labels: Bug 🐞

#2690 Support date and datetime on result entry
  CHANGES.rst
  src/bika/lims/content/abstractanalysis.py
  src/bika/lims/content/abstractbaseanalysis.py
  src/bika/lims/validators.py
  src/senaite/core/api/dtime.py
  src/senaite/core/browser/form/adapters/analysisservice.py
  src/senaite/core/i18n.py
  src/senaite/core/tests/doctests/API_datetime.rst
  src/senaite/core/tests/doctests/DatetimeResult.rst
Labels: Addition ➕

#2693 Fix UnicodeDecode Error on CSV Instrument Import
  src/senaite/core/exportimport/instruments/importer.py
  src/senaite/core/exportimport/instruments/logger.py
Labels: Bug 🐞

#2696 Fix error when removing a Worksheet from inside its view
  CHANGES.rst
  src/bika/lims/setuphandlers.py
  src/senaite/core/browser/configure.zcml
  src/senaite/core/browser/workflow/__init__.py
  src/senaite/core/browser/workflow/configure.zcml
  src/senaite/core/browser/workflow/worksheet.py
  src/senaite/core/setuphandlers.py
Labels: Bug 🐞

#2692 Refactor Sticker Functionality
  CHANGES.rst
  src/bika/lims/adapters/configure.zcml
  src/bika/lims/adapters/stickers.py
  src/bika/lims/browser/configure.zcml
  src/bika/lims/browser/stickers.zcml
  src/bika/lims/browser/templates/stickers/Code_39_1x72mm.pt
  src/bika/lims/browser/templates/stickers_preview.pt
  src/bika/lims/content/bikasetup.py
  src/bika/lims/content/sampletype.py
  src/bika/lims/interfaces/__init__.py
  src/bika/lims/vocabularies/__init__.py
  src/senaite/core/adapters/configure.zcml
  src/senaite/core/adapters/stickers.py
  src/senaite/core/browser/configure.zcml
  src/senaite/core/browser/form/adapters/sampletype.py
  src/senaite/core/browser/stickers/__init__.py
  src/senaite/core/browser/stickers/configure.zcml
  src/senaite/core/browser/stickers/static/stickers.css
  src/senaite/core/browser/stickers/static/stickers.js
  src/senaite/core/browser/stickers/templates/stickers.pt
  src/senaite/core/browser/stickers/templates/stickers/Code_128_1x48mm.css
  src/senaite/core/browser/stickers/templates/stickers/Code_128_1x48mm.pt
  src/senaite/core/browser/stickers/templates/stickers/Code_128_1x72mm.css
  src/senaite/core/browser/stickers/templates/stickers/Code_128_1x72mm.pt
  src/senaite/core/browser/stickers/templates/stickers/Code_39_1x54mm.css
  src/senaite/core/browser/stickers/templates/stickers/Code_39_1x54mm.pt
  src/senaite/core/browser/stickers/templates/stickers/Code_39_1x72mm.css
  src/senaite/core/browser/stickers/templates/stickers/Code_39_1x72mm.pt
  src/senaite/core/browser/stickers/templates/stickers/Code_39_2ix1i.css
  src/senaite/core/browser/stickers/templates/stickers/Code_39_2ix1i.pt
  src/senaite/core/browser/stickers/templates/stickers/Code_39_40x20mm.css
  src/senaite/core/browser/stickers/templates/stickers/Code_39_40x20mm.pt
  src/senaite/core/browser/stickers/templates/stickers/Code_93_2x38mm.css
  src/senaite/core/browser/stickers/templates/stickers/Code_93_2x38mm.pt
  src/senaite/core/browser/stickers/templates/stickers/DIN_Address_40x85mm.css
  src/senaite/core/browser/stickers/templates/stickers/DIN_Address_40x85mm.pt
  src/senaite/core/browser/stickers/templates/stickers/QR_1x14mmx39mm.css
  src/senaite/core/browser/stickers/templates/stickers/QR_1x14mmx39mm.pt
  src/senaite/core/browser/stickers/templates/stickers/batch/Code_39_40x20mm.css
  src/senaite/core/browser/stickers/templates/stickers/batch/Code_39_40x20mm.pt
  src/senaite/core/browser/stickers/templates/stickers/readme.txt
  src/senaite/core/browser/stickers/templates/stickers/referencesample/Code_39_40x20mm.css
  src/senaite/core/browser/stickers/templates/stickers/referencesample/Code_39_40x20mm.pt
  src/senaite/core/browser/stickers/templates/stickers/worksheet/Code_39_40x20mm.css
  src/senaite/core/browser/stickers/templates/stickers/worksheet/Code_39_40x20mm.pt
  src/senaite/core/browser/stickers/templates/stickers_preview.pt
  src/senaite/core/browser/stickers/view.py
  src/senaite/core/content/configure.zcml
  src/senaite/core/content/sampletype.py
  src/senaite/core/interfaces/__init__.py
  src/senaite/core/interfaces/stickers.py
  src/senaite/core/tests/doctests/Stickers.rst
  src/senaite/core/vocabularies/configure.zcml
  src/senaite/core/vocabularies/stickers.py
  src/senaite/core/vocabularies/stickertemplates.py
Labels: Improvement 🔧

#2699 Add search filter by term for services in add sample form
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/templates/ar_add2.pt
  src/senaite/core/browser/static/js/bika.lims.analysisrequest.add.js
  src/senaite/core/browser/static/js/coffee/bika.lims.analysisrequest.add.coffee
Labels: Addition ➕

#2698 Custom contact widget in user profile
  CHANGES.rst
  src/senaite/core/browser/user/userdatapanel.py
Labels: Bug 🐞, Improvement 🔧

#2697 Allow to remove users
  CHANGES.rst
  src/senaite/core/browser/usergroup/templates/usergroups_usersoverview.pt
  src/senaite/core/browser/usergroup/usergroups_usersoverview.py
Labels: Improvement 🔧

#2700 Fix missing condition fieldname in sample add form statusmessage
  CHANGES.rst
  src/bika/lims/browser/analysisrequest/add2.py
Labels: Bug 🐞
